import type { GuideUpdate } from "@/lib/guide/types";

/**
 * Structured What’s New feed (login popup only — not listed in the public guide).
 * Newest first. Platform-audience rows never reach location staff.
 */
export const WHATS_NEW_ENTRIES: GuideUpdate[] = [
  {
    id: "upd_2026_10_31_quote_monthly_package",
    date: "2026-09-02",
    title: "Quotes include monthly software from intake",
    summary:
      "Create/send quote builds a package from intake (and the AI interview). Setup is never the only line.",
    body: "Pipeline quote builder rebuilds from Get pricing answers: package name, features they asked for, monthly software, optional setup, entities and stations, expires-on. Processing (Quantum / cash-discount) stays a separate note. Paid package dollars are Plans & billing forms. Start onboarding still needs an accepted monthly package quote unless OVERRIDE + reason.",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "quote-contract",
    tags: ["quote", "saas", "intake"],
  },
  {
    id: "upd_2026_10_30_receipts_whitepaper",
    date: "2026-10-30",
    title: "Receipts by vendor · white paper lockstep",
    summary:
      "Guest receipts group lines under the operator name. White paper and Operators Guide stay in lockstep.",
    body: "Pay or Check prints one guest receipt under the location name. On a multi-operator check, lines group by vendor. Each entity is its own Quantum Payments merchant; the guest still tenders once; capture splits. Prime the tablet from the owner workspace, then PIN-only. Closeout is not clock-out. Public Guide stays operations only. Landing Guide link stays operator-only.",
    roles: "all",
    surfaces: ["settings"],
    audience: "all",
    topicId: "receipts-by-vendor",
    tags: ["guide", "white paper", "receipts", "payments"],
  },
  {
    id: "upd_2026_10_29_tip_pooling_modes",
    date: "2026-10-29",
    title: "Tip pools: individual, tip-out, FOH / bar / team / dual",
    summary:
      "Location (and employer) setting covers every common house type. Combine mix-based tip-out with a pool. Closeout and payroll CSV show net by person and pool.",
    body: "Settings → Cash drawers (Labor / HR inherit or override). Modes: individual; individual + mix-based tip-out; FOH pool; bar pool (all wells or per well); team pool; dual food/drink from ticket line ownership. Contribution, split (hours / points / equal / sales / manual), include/exclude roles, managers excluded by default, settle at shift or pay period. Auto-grat stays, enters the pool, or splits. Service charge is house or % to staff — never labeled a tip unless you check it. Payout uses cash-at-close vs paycheck. Pooling rules vary by state; Summex calculates policy only — not legal advice and not a payroll run.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["settings", "reports"],
    audience: "all",
    topicId: "tip-pooling",
    tags: ["tips", "pool", "closeout", "payroll"],
  },
  {
    id: "upd_2026_10_28_cc_tip_payout",
    date: "2026-10-28",
    title: "CC tips: cash at close vs paycheck",
    summary:
      "Location (and employer entity) setting: cash out card tips at closeout, put them on the hours file, or settle only declared cash.",
    body: "Settings → Cash drawers, wells & banks (Labor / HR can inherit or override per employer). cash_at_close: cash due includes card tips, paid from the drawer or safe; payroll export does not add them again; blind expected includes that paid-out. paycheck: card tips are informational at closeout; cash due from card tips is $0; they go on the ADP / Intuit / CSV hours file. cash_tips_only_at_close: only declared cash tips settle in person; card tips always export. Summex does not run payroll.",
    roles: ["owner_manager", "server", "host_operator"],
    surfaces: ["settings", "reports"],
    audience: "all",
    topicId: "server-closeout",
    tags: ["tips", "closeout", "payroll", "cash"],
  },
  {
    id: "upd_2026_10_27_staffing_recs_location",
    date: "2026-10-27",
    title: "Realtime staffing cut / hold / add",
    summary:
      "Location settings drive live cut, hold, and add recs. Accept is not a clock-out — notify them to close out.",
    body: "Settings → Staffing recs (also Labor → Rules): on/off, min headcount, labor % target and high alert, sales-per-labor-hour floor, idle minutes, no-cut open/close padding and rush lock, lookahead from reservations and waitlist. Notify manager, host, and/or expo. Optional add-staff when waitlist, quoted wait, or ODS depth exceeds thresholds. The engine uses sales velocity vs the same daypart baseline, open tables, ODS, waitlist, reservations, clocked roles, and a labor $ proxy. Recommendations only. Never auto clock-out.",
    roles: ["owner_manager", "host_operator", "vendor_operator", "server", "kitchen_bar"],
    surfaces: ["floor", "settings"],
    audience: "all",
    topicId: "staffing-recs",
    tags: ["staffing", "labor", "cut", "add"],
  },
  {
    id: "upd_2026_10_26_intake_monthly_quotes",
    date: "2026-10-26",
    title: "Quotes include monthly software from intake",
    summary:
      "Create/send quote now builds a package from intake: monthly software, optional setup, processing as a separate note.",
    body: "A proposal must list the package, features from intake, monthly software $, optional setup, entities/stations, and expires-on. Base counter + kitchen display is $0 / mo; paid packages add monthly. Setup cannot be the only line. Onboarding waits until that monthly package is accepted (admin OVERRIDE + reason to skip).",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "quote-contract",
    tags: ["quote", "intake", "pricing"],
  },
  {
    id: "upd_2026_10_25_white_paper_lockstep",
    date: "2026-10-25",
    title: "White paper matches the Operators Guide",
    summary:
      "Shareable white paper rewritten for per-entity Quantum merchants, gift ledger, device roles, cash/tips, and training vs live.",
    body: "The product white paper now matches production and this guide: each entity is its own Quantum Payments merchant (Finix rail; guest never sees Finix); one guest check with split capture and receipts grouped by vendor; gift is the Summex ledger; stations are order / ODS / host, primed once then PIN-only; cash models and mix-based tip-out; training vs live. Public /guide stays operations-only. Landing Guide link stays the Operators Guide.",
    roles: ["owner_manager"],
    surfaces: ["reports", "settings"],
    audience: "all",
    topicId: "white-paper",
    tags: ["guide", "white paper", "payments", "devices"],
  },
  {
    id: "upd_2026_10_24_scheduled_ops_jobs",
    date: "2026-10-24",
    title: "Scheduled AI ops jobs",
    summary:
      "Hourly, nightly, weekly, pay-period, and monthly packs. Real xAI or skipped — never invented insights, never auto clock-out, never invented card charges.",
    body: "Settings → Scheduled AI ops jobs. While open: floor integrity, labor pulse (cut/hold/add only), gate feed, gift bursts, unreachable Ethernet printers. Nightly: exception pack, blind counts, tips, tender/void-comp outliers, Quantum capture vs line split, cost flash, staffing postmortem, house Z ack or hard-block. Weekly: peer flags, schedule vs sales, drawer trend, recipe variance, gift liability, training leftovers. Pay period: hours and CC tips vs cash-at-close for ADP/Intuit/CSV — Summex is not payroll. Monthly: risk digest (review queue), daypart baselines, vendor price creep, Quantum fees/chargebacks when present, menu stars/dogs, HR packet reminder, unseen devices. Steam-style bar entities see bar cost/sales; Diamond-style food see food; host sees the house pack. Missing xAI key queues skipped. Email printable pack when Resend is on; else inbox.",
    roles: ["owner_manager"],
    surfaces: ["reports", "settings"],
    audience: "all",
    topicId: "ops-jobs",
    tags: ["AI", "jobs", "exceptions", "cost", "staffing"],
  },
  {
    id: "upd_2026_10_23_table_check_integrity",
    date: "2026-10-23",
    title: "Table/check integrity and nightly exception pack",
    summary:
      "No nameless unassigned. Named holds. Empty table cannot drop an open check. House Z waits on the nightly pack.",
    body: "Transfer a check to a named server (they must accept) or park it in manager hold, walkout, bar tab, or left to close — always with a reason and an owner (person or house). Marking a table empty while a check is open moves that check to Left to close and flags; it never disappears. Empty + open check is a warning color on the floor. The nightly pack (Home, Cash, Reports → Nightly exception pack) lists open checks, occupied-no-check, empty/dirty with check open, stale open, cash-not-closed, late-comp cash, hold buckets, and clock-out with open checks. House Z cannot complete until those are cleared or a manager acknowledges with a reason (hard-block is optional).",
    roles: ["owner_manager"],
    surfaces: ["floor", "reports", "settings"],
    audience: "all",
    topicId: "floor-tables",
    tags: ["floor", "checks", "nightly", "Z close"],
  },
  {
    id: "upd_2026_10_22_late_comp_cash",
    date: "2026-10-22",
    title: "Late-comp + cash-close flags",
    summary:
      "Long-open checks that take a large comp then close cash are queued for manager review. Optional dual-control and cash block.",
    body: "Settings → Loss prevention: open longer than N minutes (default 180), stacked comps over $X or Y% of the check, then cash within T minutes (default 5). Also flags last send hours earlier + only a comp then cash. The queue shows open, close, dwell, comp $, approver, tender, and seconds from comp to close. Default is flag only — cash still closes. Dual-control (off by default) requires a shift lead or pending/remote on late-window comps even if a manager PIN was used at the stand. Hard-block cash after a late comp is off by default.",
    roles: ["owner_manager"],
    surfaces: ["floor", "reports", "settings"],
    audience: "all",
    topicId: "loss-prevention",
    tags: ["comp", "cash", "exceptions", "audit"],
  },
  {
    id: "upd_2026_10_21_shift_lead_approvals",
    date: "2026-10-21",
    title: "Shift-lead, pending, and remote approvals",
    summary:
      "When no manager is on the floor: shift-lead gates with $ caps, hold-for-approval, on-call SMS, optional break-glass.",
    body: "Settings → Loss prevention: name which roles may approve void/comp/discount/no-sale and their $ cap. Gift adjust, paid-check reopen, and tender-swap stay manager-only unless you grant them. Servers can request approval — the action is held; Home shows the queue. On-call is notified in-app and by SMS when Twilio is on. Approve or deny with PIN and attribution. Fired ODS tickets stay in kitchen until deny; policy is leave or auto-void. Break-glass is off by default: clocked-in PIN + reason, always alerts and flags. Void/comp under $X before send skips the gate.",
    roles: ["owner_manager"],
    surfaces: ["floor", "reports", "settings"],
    audience: "all",
    topicId: "loss-prevention",
    tags: ["approval", "shift lead", "void", "manager"],
  },
  {
    id: "upd_2026_10_20_loss_prevention",
    date: "2026-10-20",
    title: "Loss-prevention gates, audit log, exception reports",
    summary:
      "Unique PIN lockout, manager session, gated void/comp/discount, frozen paid checks, immutable audit, manager exception queue.",
    body: "Each employee has a unique PIN. Failed attempts lock the station until a manager unlocks. ODS cannot tender cash or gift. After send or bump, void/comp/discount need a manager PIN and a listed reason. Paid checks freeze; reopen or tender-swap is a manager event with before/after. Gift adjust is manager-only; load needs cash or card on the same ticket. Home shows a live feed. Reports → Loss-prevention exceptions compares employee vs house vs same weekday and queues flags for review — never an automatic accusation.",
    roles: ["owner_manager"],
    surfaces: ["floor", "reports", "settings"],
    audience: "all",
    topicId: "loss-prevention",
    tags: ["audit", "void", "comp", "PIN", "exceptions"],
  },
  {
    id: "upd_2026_10_19_guide_catchup",
    date: "2026-10-19",
    title: "Operators Guide: device roles, merchants, cash, printers",
    summary:
      "Order / ODS / host, PIN first, per-entity Quantum Payments merchants, house gift ledger, cash/tips/closeout, Ethernet printers.",
    body: "Stations are order-taking (handhelds + bar), ODS (kitchen), or host (floor + to-go). PIN first — not /login. Each entity is its own Quantum Payments merchant (Finix rail); guest sees one check; capture splits; receipts group by vendor. Gift is the Summex ledger — swipe, scan, or key — not Finix. Cash: single/shared drawer, server bank, one drawer per well, host to-go, blind count. Closeout is not clock-out. Tips: mix-based tip-out, cash-at-close vs paycheck, FOH/bar/team/dual pools. Staffing recs never auto clock-out. Printers on the AP LAN: Epson TM-T20 receipts, TM-U220 kitchen, drawer kick on the receipt printer.",
    roles: "all",
    surfaces: ["floor", "settings", "kds"],
    audience: "all",
    topicId: "device-roles",
    tags: ["guide", "devices", "payments", "cash", "printers"],
  },
  {
    id: "upd_2026_10_18_staffing_recs",
    date: "2026-10-18",
    title: "Realtime staffing cut / hold / add",
    summary:
      "Live recommendations from sales velocity, ODS, waitlist, and labor. Accept is not a clock-out — notify them to close out.",
    body: "Labor → Rules: on/off, min headcount, labor % target and high alert, sales-per-labor-hour floor, idle minutes, no-cut open/close padding and rush lock, lookahead from reservations and waitlist. Optional add-staff recs when queue/wait exceeds thresholds. Manager, host, and expo can be notified. Recommendations only — the manager decides. Never auto clock-out.",
    roles: ["owner_manager", "host_operator", "vendor_operator", "server", "kitchen_bar"],
    surfaces: ["floor", "settings"],
    audience: "all",
    topicId: "staffing-recs",
    tags: ["staffing", "labor", "cut", "add"],
  },
  {
    id: "upd_2026_10_17_tip_pooling",
    date: "2026-10-17",
    title: "Tip pooling: individual, tip-out, FOH / bar / team / dual",
    summary:
      "Location-configurable pools with mix-based tip-outs, autograt, and service charge. Closeout shows own tips, pool in/out, net due now vs paycheck.",
    body: "Settings → Cash drawers: individual, individual + tip-out, FOH pool, bar pool (all wells or per well), team pool, or dual food/drink pools from ticket line ownership. Contribution, split (hours/points/equal/sales/manual), settle at shift or pay period. Auto-grat stays, enters the pool, or splits. Service charge is house or % to staff — never labeled a tip unless you check it. Payout uses cash-at-close vs hours export. Pooling rules vary by state; Summex calculates policy only.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "reports", "settings"],
    audience: "all",
    topicId: "tip-pooling",
    tags: ["tips", "pool", "closeout", "payroll"],
  },
  {
    id: "upd_2026_10_16_server_closeout",
    date: "2026-10-16",
    title: "Server closeout, blind count, mix-based tip-out",
    summary:
      "End-of-shift closeout on order devices: open checks, sales, tenders, blind cash count, declared tips, mix-based tip-out recs. Not PIN login and not clock-out.",
    body: "Closeout is separate from PIN and from Labor clock-out. Servers enter cash on hand first when blind count is on (default for server bank and one-person drawer), then see expected and over/short. Tip-out recommendations follow food vs drink mix — two $500 servers do not owe the same kitchen and bar amounts. Accept or override; both recommended and actual store. House well/drawer close stays on Cash. Reports → Server closeouts exports a payroll-ready CSV. Summex does not process payroll.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "reports", "settings"],
    audience: "all",
    topicId: "server-closeout",
    tags: ["closeout", "tips", "cash", "blind count"],
  },
  {
    id: "upd_2026_10_14_shift_allowables",
    date: "2026-10-14",
    title: "Clock windows, shift approval, pay-period export",
    summary:
      "Published shifts, clock allowables, approval modes, and hours-file timing to ADP/Intuit or download+notify. Summex does not run payroll.",
    body: "Labor → Rules: early/late in and out (block or flag), no-shift override, rounding, break deduct. Approval: manual, auto vs shift end, or auto vs last closed ticket. Pay period weekly/biweekly/semimonthly/custom with pay date. Auto export at a time of day or N days before pay, with all-approved required. Hours export shows period status — Send or Download.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    surfaces: ["settings"],
    audience: "tenant",
    topicId: "shift-allowables",
    tags: ["clock", "schedule", "payroll", "approval"],
  },
  {
    id: "upd_2026_10_13_payroll_export",
    date: "2026-10-13",
    title: "Hours export to ADP, Intuit, or CSV",
    summary:
      "Summex does not process payroll. Reports → Payroll export sends hours, OT, and tips to ADP, QuickBooks Payroll, or a generic CSV.",
    body: "Pick a pay period. Download CSV anytime. Map staff to the provider employee id — never an SSN. If INTUIT_* or ADP_* keys are set, Send hours to provider; otherwise Connect and use CSV. Host and tenant isolation stays. No checks, no tax e-file, no net pay.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    surfaces: ["reports", "settings"],
    audience: "tenant",
    topicId: "payroll-export",
    tags: ["payroll", "adp", "intuit", "csv", "hours"],
  },
  {
    id: "upd_2026_10_12_hr_files_punches",
    date: "2026-10-12",
    title: "I-9 files, signed PDF, clock punches",
    summary:
      "Attach signed PDFs to packets. I-9 copies store by section. Clock punches save to the location for payroll CSV. Public Guide stays ops-only.",
    body: "HR packets: download to sign, then attach the completed PDF (or e-sign when a vendor key is set). I-9 is dates plus stored copies — do not skip Section 1 before 2. Clock in/out on Labor writes to this entity. Payroll summary/CSV uses those punches. Tenant list in Platform shows training | scheduled live | live.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    surfaces: ["settings"],
    audience: "tenant",
    topicId: "hr-employment",
    tags: ["hr", "i-9", "payroll", "clock"],
  },
  {
    id: "upd_2026_10_11_hr_employment",
    date: "2026-10-11",
    title: "Entity-scoped employment",
    summary:
      "Host or tenant can be the employer. Optional hiring, packets, e-sign or PDF outbox, time-off, payroll summary, write-ups. Visibility per field.",
    body: "Settings or HR → Flags. Enable HR for this entity. Employment state drives W-4 and state packets. Without DocuSign/HelloSign keys, packets still generate — attach the signed PDF. Platform support never sees SSN or full tax packets. Clock remains Labor.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    surfaces: ["settings"],
    audience: "tenant",
    topicId: "hr-employment",
    tags: ["hr", "employment", "packets", "e-sign"],
  },
  {
    id: "upd_2026_10_08_training_loop",
    date: "2026-10-08",
    title: "Training floor loop",
    summary:
      "A SaaS training host can seat, send, Start/Bump, pay cash or sandbox card, and bus. If no staff exist, location-only PINs 0000–5555 are hashed in.",
    body: "Open POS on a training location. Banner stays TRAINING. PIN 1111 as server, 2222 host, 4444 kitchen, 5555 busser. This station switches Server, Host stand, Kitchen/Bar Order Display, Kiosk, Cashier. Live card keys are ignored. Gift and settlement are practice. PIN is not the time clock.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "kds"],
    audience: "all",
    topicId: "training-floor-loop",
    tags: ["training", "pin", "ods", "sandbox"],
  },
  {
    id: "upd_2026_10_07_floor_checks_ai",
    date: "2026-10-07",
    title: "Floor views, table combine, check split/move, scheduled AI reports",
    summary:
      "Entire location or by section. Combine tables (lowest number). Split/combine/move checks with audit. AI analysis on demand or daily/weekly.",
    body: "Drag a table onto another or multi-select Combine — the group label is the lowest number and seats add. Split group restores originals. On Order, Split / move handles seat, items, even split, custom $, combine checks, and move to another table. Operator tags stay. Reports → AI analysis; Settings schedules daily/weekly into the inbox and email/outbox. No auto price change.",
    roles: ["owner_manager", "server", "host_operator"],
    surfaces: ["floor", "reports", "settings"],
    audience: "all",
    topicId: "check-split-move",
    tags: ["floor", "combine", "split", "ai"],
  },
  {
    id: "upd_2026_10_06_guide_training_week",
    date: "2026-10-06",
    title: "Operators Guide matches training week",
    summary:
      "Public guide is operations only. No demo PIN, no seeded house, no changelog on /guide. Platform Admin still has CRM, quotes, and go-live ops.",
    body: "Exit on /guide returns to marketing home (Get pricing, Guide, Sign in). Training is sandbox Quantum Payments. Live cards wait for an approved application and an enrolled reader. PIN is not the time clock and not server closeout.",
    roles: "all",
    surfaces: ["floor", "settings", "platform"],
    audience: "all",
    topicId: "intro",
    tags: ["guide", "training", "go live"],
  },
  {
    id: "upd_2026_10_05_location_catalog",
    date: "2026-10-05",
    title: "Floor, menu, and recipes save for every tablet",
    summary:
      "The floorplan, menu, and recipes save to the location. ODS Start/Bump notifies the originating server on other devices. Server closeout is not the time clock.",
    body: "Drag tables in the editor — every paired tablet gets the map. Menu edits and recipes persist for the house. When kitchen bumps on one tablet, the originating server’s device chimes and vibrates. Cash expected drawer is float + cash sales − cash tips paid out. PIN still does not punch you in or out.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "kds", "settings"],
    audience: "all",
    topicId: "floor-editor",
    tags: ["floor", "menu", "recipes", "ods", "closeout"],
  },
  {
    id: "upd_2026_10_04_training_week",
    date: "2026-10-04",
    title: "Training vs live",
    summary:
      "Training locations stay on Quantum Payments sandbox. Go live is explicit (now or schedule) with keep/erase. Floor PIN is not the time clock.",
    body: "Banner: TRAINING — practice mode. Live processor keys are ignored until the location is live. Cash, gift ledger, floor/ODS, devices, and settlement math all work in training. Marketing shows Sign in, not an unauthenticated Dashboard. Clock in / out is Labor.",
    roles: ["owner_manager", "host_operator", "platform_admin", "server"],
    surfaces: ["floor", "settings"],
    audience: "all",
    topicId: "location-training",
    tags: ["training", "go live", "sandbox", "pin", "clock"],
  },
  {
    id: "upd_2026_10_03_printing",
    date: "2026-10-03",
    title: "Kitchen and receipt printing",
    summary:
      "Hardware registry printers (Star / Epson / generic) print tickets and receipts. SYOH sites use the browser print dialog today. LAN printers use the house print agent.",
    body: "Add a printer, assign Kitchen / Bar / Receipt / Expo, tap Test print. Send fires station tickets. Bump prints expo. Pay prints the guest receipt. Browsers cannot open TCP 9100 — run node scripts/print-agent.mjs on the hub, or leave connection = This browser.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "kds", "settings"],
    audience: "all",
    topicId: "printers-kds",
    tags: ["print", "printer", "star", "epson", "hardware"],
  },
  {
    id: "upd_2026_10_02_quantum_live",
    date: "2026-10-02",
    title: "Quantum Payments live path",
    summary:
      "Sandbox remains the default. Live card-present uses a supplied Quantum reader under the host brand. Cash still works if the processor is down or the device is offline.",
    body: "No Stripe/Square POS picker. Training always sandboxes. Live needs server-only keys and an enrolled reader — otherwise the pay dialog fails closed (“Card requires connection” / take cash). PAN and CVV are never stored. $35 dispute fee still splits by merchandise %.",
    roles: ["owner_manager", "server", "host_operator", "vendor_operator"],
    surfaces: ["floor", "settings"],
    audience: "all",
    topicId: "quantum-payments",
    tags: ["payments", "quantum", "card", "sandbox", "live"],
  },
  {
    id: "upd_2026_10_01_floor_sync",
    date: "2026-10-01",
    title: "Tickets live across devices",
    summary:
      "Open checks, sends, ODS Start/Bump, table status, and cash payments persist for the location. A second tablet and kitchen display see the same floor within a few seconds when online.",
    body: "Postgres is the floor of record. Zustand is a cache — refresh still shows the check. Vendor operators only see their own lines and tickets. Offline, this station queues the change; we do not pretend two devices share a check with no internet.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator", "vendor_operator"],
    surfaces: ["floor", "kds"],
    audience: "all",
    topicId: "kds",
    tags: ["pos", "ods", "sync", "tickets"],
  },
  {
    id: "upd_2026_09_30_station_cold_start",
    date: "2026-09-30",
    title: "Cold-start POS offline",
    summary:
      "After one online install, power the tablet with no internet, tap the icon, PIN in. Cached menu, floor, and open checks. Cash OK. Card blocked.",
    body: "The home-screen icon opens the station — you do not type a URL. First install needs internet. Thereafter cold start can be offline. Outbox syncs when WAN returns.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "kds"],
    audience: "all",
    topicId: "wifi-offline",
    tags: ["offline", "pwa", "station", "pin"],
  },
  {
    id: "upd_2026_09_27_station_split",
    date: "2026-09-27",
    title: "This station + split-screen ODS",
    summary:
      "Any tablet, Android display, or desktop can switch Host stand, Server POS, ODS, Expo, Cashier, Busser, Kiosk. Split two panes (kitchen | bar). Devices are not fixed roles.",
    body: "This station is what the screen is showing; PIN is who you are. Last station is remembered on this browser. Split: independent Start/Bump per pane, optional 70/30, tap header to fullscreen. No special device SKU.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator", "vendor_operator"],
    surfaces: ["floor", "kds", "settings"],
    audience: "all",
    topicId: "station-switcher",
    tags: ["station", "split", "ods", "device"],
  },
  {
    id: "upd_2026_09_23_training",
    date: "2026-09-23",
    title: "Training phase, Change device, split screen, Go live",
    summary:
      "New locations open in Training with sandbox cards. Managers Change device or split screen. Owner goes live now or on a schedule, choosing Keep or Erase for practice data.",
    body: "Banner: TRAINING — practice mode. Inventory tracking in training is optional. A tenant operator can stay in training while the host is live. Type GO LIVE NOW. Menus and recipes always remain.",
    roles: ["owner_manager", "host_operator", "platform_admin"],
    surfaces: ["settings"],
    audience: "all",
    topicId: "location-training",
    tags: ["training", "go-live", "device", "sandbox"],
  },
  {
    id: "upd_2026_09_22_recipes",
    date: "2026-09-22",
    title: "Recipes: AI intake, floor prep, cost linkage",
    summary:
      "Describe or upload a recipe. Confirm to save. Servers see ingredients and allergens. Bar and kitchen see full prep. SKU costs feed margin and variance.",
    body: "Costs → Recipes or Menu → Recipe. Type, voice, or photo. Map SKUs when the catalog matches. Recipe / ingredients on Order and ODS. Prices still change only when you Save on Menu.",
    roles: ["owner_manager", "server", "kitchen_bar", "vendor_operator"],
    surfaces: ["floor", "kds"],
    audience: "all",
    topicId: "recipes-prep",
    tags: ["recipe", "prep", "allergen", "ai"],
  },
  {
    id: "upd_2026_09_18_host_tenant_onboard",
    date: "2026-09-18",
    title: "Host onboarding, then operator self-serve invites",
    summary:
      "SaaS finishes the host. Hosts invite bar/kitchen tenants by email or SMS. Operators complete their own details — no platform admin per stall.",
    body: "After host_ready, open Settings → Operators / Tenants. Add a slot, send the link. The POC sets a password and submits legal, stations, and a payout stub. Host still owns routing and payouts.",
    roles: ["platform_admin", "owner_manager", "host_operator"],
    surfaces: ["platform", "settings"],
    audience: "all",
    topicId: "tenant-invites",
    tags: ["onboarding", "host", "tenant", "invite"],
  },
  {
    id: "upd_2026_09_17_quote_email",
    date: "2026-09-17",
    title: "Structured quotes and quote email",
    summary:
      "Get pricing opens a request. Pipeline builds the quote from Plans (plan, locations, add-ons, setup) and emails it. No JSON pricing.",
    body: "Save draft, then Send quote. The prospect gets a link to review, print, and accept. Without an email API key, messages land in Settings → Communications outbox.",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "quote-contract",
    tags: ["quote", "email", "pipeline", "plans"],
  },
  {
    id: "upd_2026_09_16_platform_settings",
    date: "2026-09-16",
    title: "Platform Settings: sectioned forms, no JSON",
    summary:
      "Settings is a real control plane: general, security, CRM, plans, gift defaults, flags, team, and danger zone. Operators never edit pricing JSON.",
    body: "Open Platform → Settings. Save each section independently. Edit a plan’s monthly price and modules on the plan card. Set gift issuer mode and residual from dropdowns. Factory reset stays in Danger zone and follows the Security toggle.",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "platform-settings",
    tags: ["settings", "plans", "billing", "gifts", "admin"],
  },
  {
    id: "upd_2026_09_14_saas_crm",
    date: "2026-09-14",
    title: "Platform CRM: accounts, pipeline, tenants, billing, support",
    summary:
      "Control plane has CRM, deal board, tenant directory, software invoices, tickets, and SaaS reports. Locations still only come from onboarding.",
    body: "Add a lead or convert Get pricing intake. Start onboarding from the account when the contract is ready. Go live creates a real tenant under Tenants — never a demo seed. Software billing is separate from Quantum Payments.",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "platform-crm",
    tags: ["crm", "pipeline", "tenants", "billing"],
  },
  {
    id: "upd_2026_09_13_no_demo_tenants",
    date: "2026-09-13",
    title: "No demo tenants — onboard a real location to test",
    summary:
      "Fake POS venues and PIN 0000 rooms are gone. Get pricing is the sales path. Platform Admin starts with zero tenants.",
    body: "Marketing Get pricing opens intake. /demo URLs redirect there. Admin login shows an empty tenant list until SaaS onboarding creates an org and location. Floor PIN is only for staff on that location.",
    roles: "all",
    surfaces: ["platform", "settings"],
    topicId: "empty-start",
    tags: ["onboarding", "saas", "empty-start"],
  },
  {
    id: "upd_2026_09_09_floor_qr",
    date: "2026-09-09",
    title: "Drag-and-drop floor, status flash, table QR pay",
    summary:
      "Draw the room, color tables by dining status, flash SLAs, and let guests order or pay from a table QR.",
    body: "Owner/manager/host stand open Floor editor: drag, resize, booths and barstools. Settings maps the empty → sat → drinks → food → delivered → unpaid → needs-bus pipeline, colors, and flash minutes. QR mode is Full, Hybrid, or Pay only. Guest pay is Quantum Payments on the host check — operator lines stay tagged.",
    roles: ["owner_manager", "server", "host_operator"],
    entityTypes: ["restaurant", "food_hall", "bar_lounge"],
    surfaces: ["floor", "settings"],
    topicId: "floor-editor",
    tags: ["floor", "qr", "status", "flash"],
  },
  {
    id: "upd_2026_08_13_quantum_pay",
    date: "2026-08-13",
    title: "Quantum Payments is the only processor",
    summary:
      "Guest cards run only through Quantum Payments. Integrations no longer offer Stripe, Square, or other card processors.",
    roles: ["owner_manager", "host_operator", "vendor_operator", "platform_admin"],
    topicId: "quantum-payments",
    tags: ["payments"],
  },
  {
    id: "upd_2026_08_13_chargeback",
    date: "2026-08-13",
    title: "$35 dispute fee, split by merchandise",
    summary:
      "A $35 fee is charged only when a dispute is filed. Split by each operator’s share of merchandise on that check. Won/lost does not reverse it.",
    roles: ["owner_manager", "host_operator", "vendor_operator", "platform_admin"],
    entityTypes: ["food_hall", "truck_pod", "ghost_kitchen"],
    topicId: "chargebacks",
    tags: ["chargeback", "settlement"],
  },
  {
    id: "upd_2026_08_13_gift",
    date: "2026-08-13",
    title: "First-party gift cards",
    summary:
      "Issue, reload, freeze, and void on the Summex ledger. Sale-point issuer or house. Redeem settles internally. Unredeemed liability stays on the issuer; house cards keep remainder with the house.",
    roles: ["owner_manager", "server"],
    surfaces: ["floor"],
    topicId: "gift-cards",
    tags: ["gift"],
  },
];
