import type { GuideUpdate } from "@/lib/guide/types";

/**
 * Structured What’s New feed (login popup only — not listed in the public guide).
 * Newest first. Platform-audience rows never reach location staff.
 */
export const WHATS_NEW_ENTRIES: GuideUpdate[] = [
  {
    id: "upd_2026_10_06_guide_training_week",
    date: "2026-10-06",
    title: "Operators Guide matches training week",
    summary:
      "Public guide is operations only. No demo PIN, no seeded house, no changelog on /guide. Platform Admin still has CRM, quotes, and go-live ops.",
    body: "Exit on /guide returns to marketing home (Get pricing, Guide, Sign in). Training is sandbox Quantum Payments. Live cards wait for an approved application and an enrolled reader. PIN is not the time clock and not server closeout.",
    roles: "all",
    surfaces: ["floor", "settings", "platform"],
    audience: "all",
    topicId: "intro",
    tags: ["guide", "training", "go live"],
  },
  {
    id: "upd_2026_10_05_location_catalog",
    date: "2026-10-05",
    title: "Floor, menu, and recipes save for every tablet",
    summary:
      "The floorplan, menu, and recipes save to the location. ODS Start/Bump notifies the originating server on other devices. Server closeout is not the time clock.",
    body: "Drag tables in the editor — every paired tablet gets the map. Menu edits and recipes persist for the house. When kitchen bumps on one tablet, the originating server’s device chimes and vibrates. Cash expected drawer is float + cash sales − cash tips paid out. PIN still does not punch you in or out.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "kds", "settings"],
    audience: "all",
    topicId: "floor-editor",
    tags: ["floor", "menu", "recipes", "ods", "closeout"],
  },
  {
    id: "upd_2026_10_04_training_week",
    date: "2026-10-04",
    title: "Training vs live",
    summary:
      "Training locations stay on Quantum Payments sandbox. Go live is explicit (now or schedule) with keep/erase. Floor PIN is not the time clock.",
    body: "Banner: TRAINING — practice mode. Live processor keys are ignored until the location is live. Cash, gift ledger, floor/ODS, devices, and settlement math all work in training. Marketing shows Sign in, not an unauthenticated Dashboard. Clock in / out is Labor.",
    roles: ["owner_manager", "host_operator", "platform_admin", "server"],
    surfaces: ["floor", "settings"],
    audience: "all",
    topicId: "location-training",
    tags: ["training", "go live", "sandbox", "pin", "clock"],
  },
  {
    id: "upd_2026_10_03_printing",
    date: "2026-10-03",
    title: "Kitchen and receipt printing",
    summary:
      "Hardware registry printers (Star / Epson / generic) print tickets and receipts. SYOH sites use the browser print dialog today. LAN printers use the house print agent.",
    body: "Add a printer, assign Kitchen / Bar / Receipt / Expo, tap Test print. Send fires station tickets. Bump prints expo. Pay prints the guest receipt. Browsers cannot open TCP 9100 — run node scripts/print-agent.mjs on the hub, or leave connection = This browser.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "kds", "settings"],
    audience: "all",
    topicId: "printers-kds",
    tags: ["print", "printer", "star", "epson", "hardware"],
  },
  {
    id: "upd_2026_10_02_quantum_live",
    date: "2026-10-02",
    title: "Quantum Payments live path",
    summary:
      "Sandbox remains the default. Live card-present uses a supplied Quantum reader under the host brand. Cash still works if the processor is down or the device is offline.",
    body: "No Stripe/Square POS picker. Training always sandboxes. Live needs server-only keys and an enrolled reader — otherwise the pay dialog fails closed (“Card requires connection” / take cash). PAN and CVV are never stored. $35 dispute fee still splits by merchandise %.",
    roles: ["owner_manager", "server", "host_operator", "vendor_operator"],
    surfaces: ["floor", "settings"],
    audience: "all",
    topicId: "quantum-payments",
    tags: ["payments", "quantum", "card", "sandbox", "live"],
  },
  {
    id: "upd_2026_10_01_floor_sync",
    date: "2026-10-01",
    title: "Tickets live across devices",
    summary:
      "Open checks, sends, ODS Start/Bump, table status, and cash payments persist for the location. A second tablet and kitchen display see the same floor within a few seconds when online.",
    body: "Postgres is the floor of record. Zustand is a cache — refresh still shows the check. Vendor operators only see their own lines and tickets. Offline, this station queues the change; we do not pretend two devices share a check with no internet.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator", "vendor_operator"],
    surfaces: ["floor", "kds"],
    audience: "all",
    topicId: "kds",
    tags: ["pos", "ods", "sync", "tickets"],
  },
  {
    id: "upd_2026_09_30_station_cold_start",
    date: "2026-09-30",
    title: "Cold-start POS offline",
    summary:
      "After one online install, power the tablet with no internet, tap the icon, PIN in. Cached menu, floor, and open checks. Cash OK. Card blocked.",
    body: "The home-screen icon opens the station — you do not type a URL. First install needs internet. Thereafter cold start can be offline. Outbox syncs when WAN returns.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator"],
    surfaces: ["floor", "kds"],
    audience: "all",
    topicId: "wifi-offline",
    tags: ["offline", "pwa", "station", "pin"],
  },
  {
    id: "upd_2026_09_27_station_split",
    date: "2026-09-27",
    title: "This station + split-screen ODS",
    summary:
      "Any tablet, Android display, or desktop can switch Host stand, Server POS, ODS, Expo, Cashier, Busser, Kiosk. Split two panes (kitchen | bar). Devices are not fixed roles.",
    body: "This station is what the screen is showing; PIN is who you are. Last station is remembered on this browser. Split: independent Start/Bump per pane, optional 70/30, tap header to fullscreen. No special device SKU.",
    roles: ["owner_manager", "server", "kitchen_bar", "host_operator", "vendor_operator"],
    surfaces: ["floor", "kds", "settings"],
    audience: "all",
    topicId: "station-switcher",
    tags: ["station", "split", "ods", "device"],
  },
  {
    id: "upd_2026_09_23_training",
    date: "2026-09-23",
    title: "Training phase, Change device, split screen, Go live",
    summary:
      "New locations open in Training with sandbox cards. Managers Change device or split screen. Owner goes live now or on a schedule, choosing Keep or Erase for practice data.",
    body: "Banner: TRAINING — practice mode. Inventory tracking in training is optional. A tenant operator can stay in training while the host is live. Type GO LIVE NOW. Menus and recipes always remain.",
    roles: ["owner_manager", "host_operator", "platform_admin"],
    surfaces: ["settings"],
    audience: "all",
    topicId: "location-training",
    tags: ["training", "go-live", "device", "sandbox"],
  },
  {
    id: "upd_2026_09_22_recipes",
    date: "2026-09-22",
    title: "Recipes: AI intake, floor prep, cost linkage",
    summary:
      "Describe or upload a recipe. Confirm to save. Servers see ingredients and allergens. Bar and kitchen see full prep. SKU costs feed margin and variance.",
    body: "Costs → Recipes or Menu → Recipe. Type, voice, or photo. Map SKUs when the catalog matches. Recipe / ingredients on Order and ODS. Prices still change only when you Save on Menu.",
    roles: ["owner_manager", "server", "kitchen_bar", "vendor_operator"],
    surfaces: ["floor", "kds"],
    audience: "all",
    topicId: "recipes-prep",
    tags: ["recipe", "prep", "allergen", "ai"],
  },
  {
    id: "upd_2026_09_18_host_tenant_onboard",
    date: "2026-09-18",
    title: "Host onboarding, then operator self-serve invites",
    summary:
      "SaaS finishes the host. Hosts invite bar/kitchen tenants by email or SMS. Operators complete their own details — no platform admin per stall.",
    body: "After host_ready, open Settings → Operators / Tenants. Add a slot, send the link. The POC sets a password and submits legal, stations, and a payout stub. Host still owns routing and payouts.",
    roles: ["platform_admin", "owner_manager", "host_operator"],
    surfaces: ["platform", "settings"],
    audience: "all",
    topicId: "tenant-invites",
    tags: ["onboarding", "host", "tenant", "invite"],
  },
  {
    id: "upd_2026_09_17_quote_email",
    date: "2026-09-17",
    title: "Structured quotes and quote email",
    summary:
      "Get pricing opens a request. Pipeline builds the quote from Plans (plan, locations, add-ons, setup) and emails it. No JSON pricing.",
    body: "Save draft, then Send quote. The prospect gets a link to review, print, and accept. Without an email API key, messages land in Settings → Communications outbox.",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "quote-contract",
    tags: ["quote", "email", "pipeline", "plans"],
  },
  {
    id: "upd_2026_09_16_platform_settings",
    date: "2026-09-16",
    title: "Platform Settings: sectioned forms, no JSON",
    summary:
      "Settings is a real control plane: general, security, CRM, plans, gift defaults, flags, team, and danger zone. Operators never edit pricing JSON.",
    body: "Open Platform → Settings. Save each section independently. Edit a plan’s monthly price and modules on the plan card. Set gift issuer mode and residual from dropdowns. Factory reset stays in Danger zone and follows the Security toggle.",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "platform-settings",
    tags: ["settings", "plans", "billing", "gifts", "admin"],
  },
  {
    id: "upd_2026_09_14_saas_crm",
    date: "2026-09-14",
    title: "Platform CRM: accounts, pipeline, tenants, billing, support",
    summary:
      "Control plane has CRM, deal board, tenant directory, software invoices, tickets, and SaaS reports. Locations still only come from onboarding.",
    body: "Add a lead or convert Get pricing intake. Start onboarding from the account when the contract is ready. Go live creates a real tenant under Tenants — never a demo seed. Software billing is separate from Quantum Payments.",
    roles: ["platform_admin"],
    surfaces: ["platform"],
    audience: "platform",
    topicId: "platform-crm",
    tags: ["crm", "pipeline", "tenants", "billing"],
  },
  {
    id: "upd_2026_09_13_no_demo_tenants",
    date: "2026-09-13",
    title: "No demo tenants — onboard a real location to test",
    summary:
      "Fake POS venues and PIN 0000 rooms are gone. Get pricing is the sales path. Platform Admin starts with zero tenants.",
    body: "Marketing Get pricing opens intake. /demo URLs redirect there. Admin login shows an empty tenant list until SaaS onboarding creates an org and location. Floor PIN is only for staff on that location.",
    roles: "all",
    surfaces: ["platform", "settings"],
    topicId: "empty-start",
    tags: ["onboarding", "saas", "empty-start"],
  },
  {
    id: "upd_2026_09_09_floor_qr",
    date: "2026-09-09",
    title: "Drag-and-drop floor, status flash, table QR pay",
    summary:
      "Draw the room, color tables by dining status, flash SLAs, and let guests order or pay from a table QR.",
    body: "Owner/manager/host stand open Floor editor: drag, resize, booths and barstools. Settings maps the empty → sat → drinks → food → delivered → unpaid → needs-bus pipeline, colors, and flash minutes. QR mode is Full, Hybrid, or Pay only. Guest pay is Quantum Payments on the host check — operator lines stay tagged.",
    roles: ["owner_manager", "server", "host_operator"],
    entityTypes: ["restaurant", "food_hall", "bar_lounge"],
    surfaces: ["floor", "settings"],
    topicId: "floor-editor",
    tags: ["floor", "qr", "status", "flash"],
  },
  {
    id: "upd_2026_08_13_quantum_pay",
    date: "2026-08-13",
    title: "Quantum Payments is the only processor",
    summary:
      "Guest cards run only through Quantum Payments. Integrations no longer offer Stripe, Square, or other card processors.",
    roles: ["owner_manager", "host_operator", "vendor_operator", "platform_admin"],
    topicId: "quantum-payments",
    tags: ["payments"],
  },
  {
    id: "upd_2026_08_13_chargeback",
    date: "2026-08-13",
    title: "$35 dispute fee, split by merchandise",
    summary:
      "A $35 fee is charged only when a dispute is filed. Split by each operator’s share of merchandise on that check. Won/lost does not reverse it.",
    roles: ["owner_manager", "host_operator", "vendor_operator", "platform_admin"],
    entityTypes: ["food_hall", "truck_pod", "ghost_kitchen"],
    topicId: "chargebacks",
    tags: ["chargeback", "settlement"],
  },
  {
    id: "upd_2026_08_13_gift",
    date: "2026-08-13",
    title: "First-party gift cards",
    summary:
      "Issue, reload, freeze, and void on the Summex ledger. Sale-point issuer or house. Redeem settles internally. Unredeemed liability stays on the issuer; house cards keep remainder with the house.",
    roles: ["owner_manager", "server"],
    surfaces: ["floor"],
    topicId: "gift-cards",
    tags: ["gift"],
  },
];
