import { p, related, shot, steps, tip, topic, ul, warn, why } from "./helpers";
import type { GuideTopic } from "../types";

export const DEVICE_TOPICS: GuideTopic[] = [
  topic({
    id: "device-roles",
    chapterId: "devices",
    title: "Stations and PINs",
    summary:
      "Station UI is device role ∩ staff PIN. The tablet is the envelope; the PIN is which of those actions this person may use. Never the same home for every PIN.",
    roles: "all",
    keywords: [
      "device role",
      "order",
      "ods",
      "host",
      "handheld",
      "bar",
      "kitchen",
      "to-go",
      "pin",
      "change device",
      "station",
      "reassign",
      "delete",
      "deactivate",
      "unpair",
      "pair code",
      "claim code",
    ],
    openView: "settings",
    blocks: [
      why(
        "The tablet is a screen, not a person. Station UI is the intersection of device role (what the hardware may do) and employee PIN (which of those capabilities this person may see). If either side denies an action, hide it or block with a short reason. Never give every PIN the same home.",
      ),
      p(
        "Every staff station is one of four roles: order, ODS, host, or kiosk. An unpaired or unprimed tablet shows a pair-code field only — never a fake two-button POS. Type the Devices code and submit. After pair, the PIN pad. Password owner login is venue back office, never this PIN home.",
      ),
      p(
        "Staff stations are Android tablets running one Play-ready app: Summex Station (`app.summex.pos`). First open is a text field for the venue pair code from Devices (for example K7VY5R) — never /login, never the marketing site. No scan required. After pair, the PIN pad, optional lock-task. Guest QR and pay links stay on the guest’s own phone browser — not a staff station. iPad and browser POS are not a supported house setup.",
      ),
      ul(
        "Device envelope — Order: floor (full service / hybrid), queue (counter), window/lane (drive-through), to-go, bar tab if Bar tabs on order devices is on, clock, pay/close on their checks.",
        "Device envelope — Host: floor + waitlist + seat, to-go, clock. Bar tabs only if Host may open bar tabs is on. Peer venues still have a host ROLE (the stand) with no host merchant.",
        "Device envelope — ODS: Start/Bump only, lanes by entity, clock. No new order, no to-go, no pay. A manager PIN on ODS is still the rail — not order entry.",
        "Device envelope — Kiosk: guest waitlist / QR / pay. A paired kiosk skips the staff PIN pad. Staff PINs do not operate kiosk. Manager / supervisor / Devices service PIN may reload or exit.",
        "PIN on a capable device — Host: host envelope. Server: order envelope; on a host tablet, seat + to-go only if Servers may use the host stand is on, otherwise clock + use an order tablet.",
        "Bartender: drinks / bar tab on order; ODS is their bar lane only. Kitchen / cook / expo: ODS rail on ODS; on order or host, clock only — never to-go, bar tab, or a table order.",
        "Busser: floor status cleaned if the venue allows; no ordering. Supervisor / manager: union of what this DEVICE allows, plus reload / exit kiosk. They do not gain order-entry on an ODS tablet.",
        "Home after PIN — a short menu of jobs this DEVICE × this PIN allows (2–6 large named buttons). Hide what the intersection denies — never a greyed-out grid. One job per screen. Back returns to the menu (or to the floor if they came from a table). Pay / split lives on the check, not the home menu.",
        "Order tablet menu — My tables (full-service floor only; map + status, no side drawers). New table. To-go. Bar tab if the venue has a rail and the PIN allows it. Clock in/out. Closeout (server / manager, end of shift). Kitchen PIN on an order tablet: clock sheet — Clock and Done only.",
        "Host tablet menu — Floor / seat, Waitlist, To-go, Clock in/out. No ODS rail, no menu editor, no bar tab on this menu.",
        "ODS — rail only plus Clock. No hamburger of POS tasks. A manager PIN on ODS is still the rail — not order entry.",
        "Counter / drive-through: New ticket or lane/window (no dining floor). Unpaired: type the Devices code and submit.",
        "Clock in and clock out is on the short menu (or the ODS clock bar). Completing clock does not open order entry. Live venues never show Operating as on the staff menu. Isolated demos: one small control in a manager More overflow.",
        "Venue settings (back office, not a JSON file): Servers may use the host stand; Host may open bar tabs; Bar tabs on order devices.",
        "A manager Change device (training/demo) switches among Order / ODS / Host. PIN stays the person; the role is the screen.",
        "Pair once (internet required). Type the one-time Devices code — case-insensitive, spaces ignored. One-time; expiry unchanged. A bad or expired code says “Code invalid or expired. Regenerate on Devices.” QR is optional (hidden until Show QR). Claim this browser / Pair this browser stay for laptop tests. Bookmarks are app.summex.app/station. After that, power on → PIN pad for that venue and role, not the sales home. App updates keep the pairing. Store APKs do not need a baked station. Back-office username and password is for owners on a laptop, not the handheld.",
        "Broken ODS → reassign a server tablet from Devices. Same pair code; staff PIN in again. Do not reinstall.",
        "Devices: Deactivate, Unpair, Replace, or Delete revokes the pair token immediately. An online tablet is kicked to the pair-code screen within a few seconds (no APK reinstall). Local snapshot is invalid — next open is not a PIN pad. Deactivate keeps the named slot. Unpair / Replace keep the name. Delete removes the slot — confirm “Delete this device. The tablet must scan a new code.” Activate again mints a new code (same as Replace). A PIN on a deactivated tablet: “This station was deactivated — enter a new code,” not Invalid PIN. Location owner / manager / Admin only. Floor PINs cannot delete. After delete, Add device can reuse the same name and role.",
      ),
      steps(
        "Owner: Devices → Add device → Order / ODS / Host / Kiosk. The one-time code shows large on the row (QR is Show QR, collapsed by default). Codes expire; regenerate from that row.",
        "Tablet: first open of Summex Station → type the code (for example K7VY5R) and submit. Thereafter: power on → PIN keypad. That is not clock-in and not closeout.",
        "Paired row: Role dropdown (Order / Host / ODS, plus ODS kitchen or ODS bar when both exist, and Kiosk when the house has one). Confirm, then staff PIN in again. Apply now only if that tablet is on the PIN pad — never mid-check.",
        "Owner or manager: Change device to move this screen among Order / ODS / Host without a new account login.",
        "Switch user returns to the PIN pad. A Devices role change takes effect on the next PIN, same as Publish.",
        "To retire a named station: Delete (one confirm). To keep the name and swap hardware: Replace or Unpair. To leave it in the list: Deactivate — the tablet returns to the pair-code field; Activate again shows a new code.",
      ),
      warn(
        "Do not send kitchen staff to /login. A kitchen PIN on an order tablet is not the server UI. Time clock is the Clock in / Clock out control — PIN is not a punch. Server closeout is Cash.",
      ),
      related("floor-pin-login", "login", "device-assignment", "station-switcher", "android-kiosk", "station-fit", "kds", "printers-kds", "loss-prevention"),
    ],
  }),
  topic({
    id: "station-fit",
    chapterId: "devices",
    title: "Handheld vs counter screens",
    summary:
      "Order, bar, host, and pay fit an 8\" portrait handheld. Manager dashboards scroll — they do not shrink.",
    roles: "all",
    keywords: [
      "handheld",
      "tablet",
      "counter",
      "portrait",
      "landscape",
      "touch",
      "8 inch",
      "layout",
      "slide-over",
    ],
    openView: "order",
    blocks: [
      why(
        "An 8\" Android in portrait is a different station than a 15\" counter. The same PIN and the same check — the layout must not squash into three skinny columns or shrink type to fake a laptop dashboard.",
      ),
      ul(
        "Portrait handheld (typical 8\"): one column. Menu fills the screen. The check is a slide-over, not a third column. Tap targets are at least 48px.",
        "On a full-service floor, To-go and Bar tab (when the house has a rail) are named jobs on the short menu — not a dense toolbar, and not a dashboard of tiles.",
        "Pay: one tender per row (card, cash, gift, comp). PIN pad stays large.",
        "Small tablet landscape: check + menu side by side. Still usable. No skinny nav column.",
        "Counter: side menu + check + items. Manager back office on a phone scrolls. Fonts are not shrunk to fit ten columns.",
      ),
      steps(
        "Hold the order handheld in portrait. Open a check. Ring items on the full-width menu. Tap Check to review, Send, or Pay.",
        "Rotate a small tablet to landscape. Check stays beside the menu — you can still tap.",
        "On a phone-sized owner login, open Reports or Settings and scroll. Do not pinch-zoom for tiny type.",
      ),
      tip(
        "Host stand: Floor / seat, Waitlist, and To-go are large named taps on the short menu. Same on a handheld as on the counter.",
      ),
      related("device-roles", "android-kiosk", "tenders-tips", "role-server", "role-host-stand"),
    ],
  }),
  topic({
    id: "android-kiosk",
    chapterId: "devices",
    title: "Tablets run Summex only",
    summary:
      "One Play-ready APK: Summex Station. Pair, then PIN. Website deploys: manager long-press reload. APK updates: unpin and reinstall.",
    roles: ["owner_manager", "host_operator", "kitchen_bar", "platform_admin"],
    keywords: [
      "android",
      "apk",
      "kiosk",
      "tablet",
      "lock task",
      "pin windows",
      "reload",
      "exit kiosk",
      "service pin",
      "knox",
      "station",
      "launcher",
    ],
    openView: "settings",
    blocks: [
      why(
        "A floor tablet is a station, not a general-purpose phone. If someone can swipe to the launcher, they are not in service.",
      ),
      p(
        "Install Summex Station once. The store binary opens the pair screen on the console host — no venue baked in, no debug station preset, never the sales site. Owner (back office password, not staff PIN): Devices → Add device → name + role. The one-time code shows large (QR optional, collapsed). Codes expire; regenerate from the row. Tablet: type the code and submit — no scan required. After pair, the tablet stores venue and role, receives the house snapshot, and is PIN only for that house. The PIN pad does not link to /login or the marketing home. Optional lock-task / pin-windows after pair. Publish updates idle devices and the next PIN login. Staff keep the last publish until Switch user. Never mid-ticket.",
      ),
      steps(
        "Install Summex Station on every staff Android tablet (same Play-ready APK for host, order, and ODS).",
        "Owner: Devices → Add device (name + Order / Order Display / Host). Read the large one-time code. Show QR only if you want it.",
        "Tablet: type the code and submit. Snapshot is pushed. Thereafter power on → PIN. App updates do not wipe pairing. A bad or expired code: “Code invalid or expired. Regenerate on Devices.”",
        "After menu or floor layout edits: Publish changes. Logged-in staff keep running; next PIN login loads the new publish. 86 / un-86 is not a publish — every station sees it immediately.",
        "Broken ODS → reassign a server tablet from Devices (Role dropdown). No new pair code.",
        "Unpair, Replace, or Deactivate from the same Devices list revokes the pair token and kicks an online tablet to the pair-code field within a few seconds. Unpair / Replace keep the named slot. Delete removes the slot after one confirm (“Delete this device. The tablet must scan a new code.”). Activate again mints a new code. Location owner / manager / Admin only.",
        "Training: on Samsung, confirm pin-windows when Summex asks. Set Summex as Home if the tablet offers it.",
        "Website updates (new JS on app.summex.app): manager, owner, or the Devices service PIN long-presses the discreet reload control for 2 seconds. The WebView reloads. Stay on pair or PIN — never /login. No unpin.",
        "APK updates (new Summex Station binary): manager Exit kiosk (confirm) to stop lock-task and show Android home, then uninstall/reinstall or Play update. Staff PINs cannot exit kiosk.",
      ),
      ul(
        "Reload = website deploy. Pairing stays on the tablet. Next screen is pair or PIN.",
        "Exit kiosk = leave lock-task. Confirm dialog. Manager / owner / Devices service PIN only.",
        "Devices → Station service PIN: optional 4-digit PIN with the same reload/exit rights as manager.",
      ),
      warn(
        "Do not put guest QR / pay on this APK. Table tents and ticket codes open in the guest’s browser. Do not unpin for a website deploy — use reload.",
      ),
      related("device-roles", "device-assignment", "station-fit", "floor-pin-login", "table-qr", "wifi-offline", "labor-basis"),
    ],
  }),
  topic({
    id: "wifi-offline",
    chapterId: "devices",
    title: "Offline mode",
    summary: "What still runs when internet is down, what waits, and how sync works.",
    roles: "all",
    keywords: ["wifi", "offline", "outbox", "network", "ssid", "internet", "queue"],
    openView: "settings",
    blocks: [
      why(
        "A dead ISP should not kill dinner. Summex is Wi‑Fi-first: stations talk on the staff SSID. Core service stays on the device even when the uplink is gone.",
      ),
      p(
        "The header banner says Offline — changes will sync when back online, or Syncing… when the outbox is flushing. No internet is not the same as no house hub: the Wi‑Fi chip distinguishes a missed API heartbeat from a down access point.",
      ),
      ul(
        "Works offline (cached location): menu, modifiers, tables/sections, staff switcher, open checks, ODS tickets on this station.",
        "Allow: create/edit orders, send to kitchen/bar (local queue), bump tickets, seat cached tables, cash tender, waitlist add (SMS pending send).",
        "Needs internet: Quantum Payments live card-present, SMS/email send, cloud reporting AI, SaaS admin and billing.",
        "Card: blocked with “Card requires connection.” Take cash or keep the check open. Card is not queued and never fakes a live Visa.",
        "Tickets are live across devices when online: every POS and ODS at the location shares the same open checks, sends, Start/Bump, table status, and cash payments (server wins on refresh). Offline, this station still runs from its cache and queues mutations; we do not pretend two tablets share a check with no internet.",
      ),
      steps(
        "First install (internet required): on Summex Station, pair with the Devices code or QR, wait for the PIN pad. Do this on each Android tablet.",
        "Thereafter cold start can be offline: power the tablet, tap Summex Station — no typing a URL. PIN in. Banner: Offline.",
        "Seat, send a ticket, Start and Bump. Take cash. Card shows Card requires connection — not queued, never a fake Visa.",
        "When WAN returns, banner says Syncing… Outbox applies each mutation once (clientMutationId). Sync failed stays until a manager retries.",
      ),
      shot(
        "Header Wi‑Fi chip — outbox, failed sync list, Offline banner.",
        "Network sheet with house SSID, queued cash/tickets, and failed rows.",
      ),
      warn(
        "First install requires internet. A house router with no WAN is not enough for a cold unpaired tablet. Pair Summex Station once while the uplink is up, wait for the floor. After that, power on with no internet: PIN in, cached menu/floor, cash tender. Card still needs a connection. App updates do not wipe pairing.",
      ),
      tip(
        "Owner / manager: watch Failed to sync. Server / cashier: cash is the offline tender. Kitchen: bump locally. Host: waitlist SMS is pending send.",
      ),
      related("printers-kds", "quantum-payments", "troubleshooting", "kds", "cash-handling", "network-readiness"),
    ],
  }),
  topic({
    id: "printers-kds",
    chapterId: "devices",
    title: "Printers & ODS devices",
    summary:
      "Two printer types: Receipt and Order. Make/model preset sets emulation, paper, cutter, port 9100. Test print is raw bytes to the printer — never the OS dialog.",
    roles: ["owner_manager", "kitchen_bar", "platform_admin"],
    keywords: [
      "printer",
      "kds",
      "device",
      "station",
      "android",
      "tablet",
      "star",
      "epson",
      "escpos",
      "receipt",
      "t20",
      "u220",
      "sp742",
      "sp700",
      "citizen",
      "bixolon",
      "9100",
      "ethernet",
      "drawer kick",
    ],
    openView: "settings",
    blocks: [
      why(
        "Tickets and chits live on the staff network. Guest Wi‑Fi or the printer’s own Wi‑Fi hotspot will look “down” while the floor is fine. Ethernet to the house access-point LAN is the production path.",
      ),
      p(
        "Devices → Add device. Type is Receipt printer or Order printer — same list as tablets. Kitchen, bar, and label are destinations on an order printer, not extra types. Form fields, not JSON: name, make/model, Wi-Fi or Ethernet, static IP (required for live print; pending IP is allowed on a slot), port (default 9100).",
      ),
      steps(
        "Devices → Add device. Pick Receipt printer or Order printer.",
        "Name it. Connection: Ethernet (production) or Wi-Fi. Static IP + port 9100.",
        "Make/model: pick what the house bought. Star SP700 / SP742 / SP712 / SP717 is the default order (impact kitchen). Star Line Mode is the other Star generic. Epson TM-T20 / T88 / m30 thermal, TM-U220 impact. Citizen, Bixolon, SNBC/Ithaca, Seiko, POS-X/Rongta, Generic ESC/POS 80mm (always there), Generic 58mm for kiosk/narrow. The preset sets emulation, paper width, cutter, and port 9100.",
        "Receipt printer: cash drawer kick yes/no; which order/host stations use it (empty = venue default); print pay QR when the venue QR setting is on. ODS does not need a receipt printer.",
        "Order printer: destination name (Kitchen, Bar, Expo, Window, Label…); entity or all so a peer venue routes food vs drink; which stations may send to it (empty = every order/host station).",
        "Save. Test print sends raw bytes to that IP:9100 through the LAN print agent or a paired station on the staff network. Never the OS print dialog (no Brother laser popup). Status: pending (no IP), idle, last-print, or unreachable.",
      ),
      ul(
        "Production: Ethernet to the staff AP. Do not join the printer to guest Wi‑Fi or run it as its own hotspot.",
        "Star SP742 at a static IP (example 192.168.0.105): Type Order printer, make/model Star SP700 / SP742 (ESC/POS) or Star generic StarPRNT / Star Line Mode.",
        "Drawer kick: receipt printer only.",
        "Existing kitchen / bar / label rows migrate to Order printer (label → destination Label).",
        "Quote / onboarding and Summit Hall seed a receipt slot plus kitchen and bar order printers (IP can stay pending).",
        "Bring-your-own Android tablets run POS/ODS via Summex Station. Printers and drawers stay BYO.",
      ),
      warn(
        "There is no Kitchen printer, Bar printer, or Label printer type. Those are destinations on an Order printer. Test print is raw TCP 9100 — never window.print or an OS dialog. Do not put order printers on the printer’s own Wi‑Fi.",
      ),
      related("wifi-offline", "kds", "device-roles", "cash-handling", "station-switcher"),
    ],
  }),
  topic({
    id: "device-assignment",
    chapterId: "devices",
    title: "Assign devices to any entity",
    summary: "Tablets, ODS, kiosks, and printers are location assets. Suggested assignment is a default — not a locked role.",
    roles: ["owner_manager", "host_operator", "vendor_operator", "kitchen_bar"],
    keywords: ["device", "tablet", "ods", "kiosk", "assignment", "claim code", "delete", "deactivate", "unpair"],
    openView: "settings",
    blocks: [
      why(
        "Hardware is not branded to a stall. The host location owns the registry. Any Android tablet running Summex Station can run Operator A POS this week and Operator B ODS next week — This station switches the screen without a new login.",
      ),
      ul(
        "Type: tablet POS, order display, kiosk, host stand, receipt printer, or order printer.",
        "Suggested assignment: operator (host or a guest entity) + function (floor POS, bar POS, kitchen ODS, bar ODS, expo, kiosk, host stand, cashier).",
        "Paired Devices row: Role dropdown reassigns that tablet (Order / Host / ODS). Broken ODS → reassign a server tablet from Devices. Same pair; next PIN. Printers and drawer kick stay on the station type or named printer.",
        "Deactivate: the named slot stays in the list. Pair token is revoked immediately. An online tablet drops PIN and shows the pair-code field within a few seconds. PIN on that glass: “This station was deactivated — enter a new code,” not Invalid PIN. Activate again mints a new code (same as Replace). Next app open does not restore the PIN pad.",
        "Unpair / Replace: keep the named slot if you still want that station. Unpair clears the tablet binding. Replace issues a new QR or code.",
        "Delete: confirm “Delete this device. The tablet must scan a new code.” Removes the row, revokes the pair token, drops the snapshot binding, and kicks an online tablet back to the pair-code field. Pending devices with a code use that same one dialog. Location owner / manager / Admin only. Floor PINs cannot delete. After delete, Add device can reuse the same name and role.",
        "This station (header): switch Host stand, Server POS, Expo, Cashier, Busser, Kiosk, or Order Display. Multi-op houses pick Host / Operator A / Operator B.",
        "PIN still identifies the person. Station switch is what this screen is showing. Last station is remembered on this tablet.",
        "ODS only shows tickets for that station and entity unless the host grants a broader view_tickets.",
      ),
      steps(
        "Dashboard → Devices (or Settings → Devices): Add a named slot — name, type, entity, function (server, host, kitchen ODS, bar ODS, split, cashier, expo, busser, kiosk).",
        "The 6-character code shows large on that slot (QR collapsed until Show QR). On Summex Station: first run, type the code and submit. Case and spaces do not matter. Pairing stays on the tablet through app updates. Claim this browser / Pair this browser stay for laptop tests.",
        "Lost tablet you still want as that station: Replace (new QR) or Unpair. To take it off the floor without losing the name: Deactivate. To remove the slot: Delete → confirm “Delete this device. The tablet must scan a new code.”",
        "Production staff stations are Android tablets running Summex Station. A Chrome “Pair this browser” path may exist for development — it is not a supported house setup.",
        "This station (header or PIN pad) switches function and entity. Last station is remembered on this device.",
        "Large displays: Layout → Split. Each pane has its own station + entity (typical: kitchen | bar ODS). 50/50 or 70/30. Tap a pane title to fullscreen.",
      ),
      warn(
        "An Operator A ODS does not show Operator B tickets unless the host grants view_tickets. Devices are not fixed roles.",
      ),
      related("device-roles", "station-switcher", "host-operator-settings", "printers-kds", "role-vendor"),
    ],
  }),
  topic({
    id: "station-switcher",
    chapterId: "devices",
    title: "This station & split screen",
    summary:
      "Any device can switch into any allowed function. Large displays split two ODS/POS panes.",
    roles: "all",
    keywords: [
      "this station",
      "split screen",
      "ods",
      "kds",
      "android",
      "tablet",
      "wall display",
      "kitchen",
      "bar",
    ],
    openView: "kitchen",
    blocks: [
      why(
        "Samsung tablets and Android touchscreens running Summex Station are the house product. Hardware is not a locked role. This station is what the screen is showing; PIN is who is signed in.",
      ),
      ul(
        "Three device roles: Order (handhelds + bar), ODS (kitchen tickets), Host (floor map + to-go). Change device among those three.",
        "This station still names the function on that role: Host stand, Server POS, Expo, Cashier, Busser, Kiosk, Kitchen ODS, Bar ODS, Bar POS.",
        "Multi-operator: pick Host, Operator A, or Operator B. Tickets stay location-scoped and tagged to the operator.",
        "Last station is remembered on this tablet (next load).",
        "Split: two independent panes, each with its own station + entity. Typical left Kitchen ODS (Operator A), right Bar ODS (Operator B).",
        "Optional 70/30. Tap a pane header to fullscreen that pane; Back to split returns.",
        "No special device SKU — any device may enable split.",
      ),
      steps(
        "Pair the display in Devices first with Summex Station. Open POS stays on this host — not a separate app origin.",
        "Open This station in the header (or on the PIN pad).",
        "Pick the function. On a host house, pick the entity. Last choice is remembered here.",
        "On a wall display: Layout → Split. Set each pane independently. Start / Bump on each rail.",
        "Tap a pane title to focus it. Tap Back to split when both rails are needed.",
      ),
      warn(
        "Station switch does not clock you in or change the location. Time clock is a separate punch. Guest checks stay under the host brand.",
      ),
      related("device-roles", "device-assignment", "printers-kds", "kds", "floor-pin-login", "location-training"),
    ],
  }),
];
