import { related, steps, tip, topic, ul, warn, why } from "./helpers";
import type { GuideTopic } from "../types";

export const FINANCE_TOPICS: GuideTopic[] = [
  topic({
    id: "ops-finance",
    chapterId: "finance",
    title: "Operations finance",
    summary: "Ledger, AP, inventory, AvT, and a controllable P&L for each selling entity.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    keywords: ["finance", "ledger", "p&l", "prime", "entity", "books"],
    openView: "inventory",
    blocks: [
      why(
        "Summex is the POS of record. The books restaurant accountants expect — sales, inventory, payables, and labor accrual — live on the selling entity, next to the checks.",
      ),
      steps(
        "Costs → Ops finance. Pick the selling entity. Location rollup adds the entities you can see and does not edit them.",
        "Post close writes the day’s sales, tenders, tips, tax, gift liability, cash over/short, and revenue-share journals. The same post runs on daily closeout and on the nightly pack.",
        "Training journals stay in the sandbox until the location is live. Go-live journals are the ones on the official P&L.",
      ),
      ul(
        "A peer entity’s vendors, inventory, and journals stay on that entity.",
        "There is no third-party POS connect. Checks, tenders, and recipes already in Summex are the source.",
        "Summex does not process payroll, file payroll tax, or move net pay.",
      ),
      related(
        "ops-finance-ledger",
        "ops-finance-pnl",
        "ops-finance-ap",
        "ops-finance-avt",
        "ops-finance-labor",
        "ops-finance-cash",
      ),
    ],
  }),
  topic({
    id: "ops-finance-ledger",
    chapterId: "finance",
    title: "Chart of accounts and journals",
    summary: "A restaurant chart per entity, posted from the POS.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    keywords: ["chart", "journal", "sales", "tender", "tax", "tips", "gift"],
    openView: "inventory",
    blocks: [
      why("Each entity starts from the same restaurant chart: sales by food and beverage, discounts, comps, tax, tips payable, COGS, labor, and occupancy."),
      steps(
        "Ops finance → Ledger shows the chart and the latest journals.",
        "Post close is idempotent for that entity and business day. Running it twice does not double the sales.",
        "Revenue share posts on the payer as an expense and on the receiver as income. It does not rewrite the other entity’s inventory.",
      ),
      tip("Sandbox journals are labeled. They drop off the live P&L."),
      related("ops-finance", "ops-finance-pnl", "system-ledger"),
    ],
  }),
  topic({
    id: "ops-finance-pnl",
    chapterId: "finance",
    title: "Daily P&L, prime cost, break-even",
    summary: "Food COGS from recipes. Labor from approved punches. Controllable profit above occupancy.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    keywords: ["p&l", "prime", "cogs", "break-even", "controllable", "rollup"],
    openView: "reports",
    blocks: [
      why("Prime cost is food and beverage COGS plus labor. Controllable profit stops above occupancy. Break-even sales are occupancy divided by what’s left after prime."),
      steps(
        "Ops finance → Daily P&L. One row is the entity. Location rollup is the sum, still view only.",
        "Food COGS comes from recipe cost at the time of the sale. Labor comes from approved punches times the accrual rate on the Labor screen.",
        "Unapproved punches are not accrued.",
      ),
      related("ops-finance-labor", "ops-finance-ledger", "recipes-prep"),
    ],
  }),
  topic({
    id: "ops-finance-bank",
    chapterId: "finance",
    title: "Bank reconciliation",
    summary: "Import a CSV or QuickBooks-style file and match deposits to card payouts and cash drops.",
    roles: ["owner_manager", "host_operator"],
    keywords: ["bank", "csv", "qbo", "payout", "deposit", "reconcile"],
    openView: "inventory",
    blocks: [
      why("The bank file is the outside number. Summex matches it to card clearing from the close and to bank deposits you logged."),
      steps(
        "Ops finance → Bank rec. Paste a Date, Description, Amount file, or a Date, Description, Debit, Credit file.",
        "Import CSV. A line matches when the amount is the same and the date is within three days.",
        "Card payouts match card clearing. Cash drops match a bank deposit.",
      ),
      related("ops-finance-cash", "ops-finance-ledger"),
    ],
  }),
  topic({
    id: "ops-finance-ap",
    chapterId: "finance",
    title: "Vendors, invoices, and AP",
    summary: "GL code, approve, credit memo, and mark paid. Price gaps are flagged.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    keywords: ["ap", "vendor", "invoice", "credit", "approval", "price"],
    openView: "purchasing",
    blocks: [
      why("Invoice capture still reads the file. Ops finance adds the payable: who you owe, which account, and whether it was approved."),
      steps(
        "Ops finance → AP. Vendors belong to the entity.",
        "Save a draft, code each line, Submit, Approve, then Post. Post debits inventory and credits accounts payable, and the unit cost becomes the recipe cost.",
        "A credit memo reverses the quantity and the payable. Mark paid clears AP against the bank.",
        "A unit cost that moves off the last pay, or off a contract price, is called out on the invoice. It does not block the post.",
      ),
      warn("Posting an invoice on one entity does not change a peer entity’s on-hand or payable."),
      related("ops-finance-purchasing", "cost-invoices", "ops-finance-inventory"),
    ],
  }),
  topic({
    id: "ops-finance-purchasing",
    chapterId: "finance",
    title: "Purchase orders and three-way match",
    summary: "PO, receipt, and invoice have to agree before a linked bill posts.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    keywords: ["po", "receive", "three-way", "edi", "csv"],
    openView: "purchasing",
    blocks: [
      why("A linked bill should match what was ordered and what arrived."),
      steps(
        "Save a PO, then Receive. Receiving puts the quantity on hand and a received-not-invoiced balance.",
        "Enter the invoice against that PO. Post is allowed when quantity and price match. A mismatch stays open.",
        "EDI today is a CSV you paste or that arrives by email. A live connector can come later. The draft still waits for GL coding and approval.",
      ),
      related("ops-finance-ap", "cost-ordering"),
    ],
  }),
  topic({
    id: "ops-finance-inventory",
    chapterId: "finance",
    title: "Counts, transfers, waste, and prep",
    summary: "Counts post a valuation. Prep turns components into a yield.",
    roles: ["owner_manager", "kitchen_bar", "vendor_operator"],
    keywords: ["count", "barcode", "waste", "transfer", "prep", "batch"],
    openView: "inventory",
    blocks: [
      why("On-hand is the entity’s stock. A count, a waste log, a transfer, or a prep batch is how it moves when it is not a sale."),
      steps(
        "Ops finance → Inventory. Post count sets on-hand and books the difference to inventory variance.",
        "A transfer out leaves this entity only. The other entity accepts its own inbound copy. You cannot edit their book from here.",
        "Prep batch decrements the components and adds the finished yield. The finished cost is the component cost spread over that yield.",
        "Counts work from the station in hand, including a typed or scanned code in the SKU field.",
      ),
      related("ops-finance-avt", "cost-variance", "recipes-prep"),
    ],
  }),
  topic({
    id: "ops-finance-avt",
    chapterId: "finance",
    title: "Actual versus theoretical",
    summary: "Recipes times items sold, against counts, invoices, waste, and transfers.",
    roles: ["owner_manager", "kitchen_bar", "vendor_operator"],
    keywords: ["avt", "theoretical", "actual", "ounces", "variance"],
    openView: "inventory",
    blocks: [
      why("Theoretical use is the recipe. Actual use is what the counts and paperwork say left the shelf."),
      steps(
        "Sell an item that has a recipe. Theoretical ounces move for that entity only.",
        "Actual for the day is the prior count, plus invoices, minus the closing count, waste, and transfers.",
        "Refresh AvT. A gap outside the band opens the same exception queue as other cost flags. The manager still picks the response, including a theft review. The screen does not accuse anyone.",
      ),
      related("cost-variance", "ops-finance-menu", "recipes-prep"),
    ],
  }),
  topic({
    id: "ops-finance-menu",
    chapterId: "finance",
    title: "Menu engineering",
    summary: "Popularity against contribution margin, cash price and card price.",
    roles: ["owner_manager", "vendor_operator"],
    keywords: ["menu engineering", "star", "margin", "popularity"],
    openView: "inventory",
    blocks: [
      why("A popular plate with a thin margin is a different decision from a quiet plate that pays for itself."),
      steps(
        "Ops finance → Menu engineering. Each sold item is quantity over the day’s items, and price minus recipe cost.",
        "Cash margin and card margin are both shown. Card uses the venue cash-discount rule when that rule is on.",
        "The class is star, plowhorse, puzzle, or dog from the day’s median popularity and median cash margin.",
      ),
      tip("Changing a price is still Menu → Save. This screen does not rewrite the menu."),
      related("ops-finance-avt", "menu-modifiers"),
    ],
  }),
  topic({
    id: "ops-finance-labor",
    chapterId: "finance",
    title: "Forecast, draft schedule, and wage accrual",
    summary: "History suggests sales. A matrix suggests heads. Punches accrue. Payroll stays an export.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    keywords: ["forecast", "schedule", "labor", "accrual", "adp", "gusto"],
    openView: "labor",
    blocks: [
      why("The floor already has overtime windows, early and late clock rules, and cut-staff recommendations. Finance adds the sales forecast and the journal."),
      steps(
        "Ops finance → Labor. Enter the accrual dollars per hour. That rate is not a paycheck.",
        "Sales history for the same weekday becomes the forecast. The labor matrix maps a sales band to heads by role. Draft schedule writes those heads. Drafts stay off the clock until Labor publishes them.",
        "Intraday, sales versus labor percent versus the target can recommend a cut, a hold, or an add. The floor’s existing cut-staff rec is unchanged.",
        "Post close accrues approved punches: debit labor, credit wages payable. Export approved punches and tips from Labor to ADP, Intuit, or the generic CSV a Gusto file uses. A live connector stays optional.",
      ),
      warn("Summex does not calculate net pay, withhold taxes, or pay staff."),
      related("entity-schedule-payroll", "payroll-export", "ops-finance-pnl"),
    ],
  }),
  topic({
    id: "ops-finance-cash",
    chapterId: "finance",
    title: "Safe drops and bank deposits",
    summary: "A drop leaves cash on hand. A deposit is what bank rec matches.",
    roles: ["owner_manager", "host_operator"],
    keywords: ["safe", "drop", "deposit", "cash on hand", "till"],
    openView: "cash",
    blocks: [
      why("The till and the drawer close are already on Cash. The drop is the next step: money leaving the drawer and, later, the building."),
      steps(
        "Ops finance → Cash drops. Safe drop moves cash on hand to the safe.",
        "Bank deposit moves the safe amount to the bank account. That deposit is a match target on Bank rec.",
        "Cash over or short from the close stays on the sales journal.",
      ),
      related("ops-finance-bank", "cash-handling", "server-closeout"),
    ],
  }),
  topic({
    id: "ops-finance-logbook",
    chapterId: "finance",
    title: "Manager log and open or close tasks",
    summary: "A checklist for open and close, plus a note the next manager can read.",
    roles: ["owner_manager", "host_operator", "vendor_operator"],
    keywords: ["logbook", "checklist", "open", "close", "occupancy"],
    openView: "inventory",
    blocks: [
      why("The close is a list, not a memory. Tasks sit on the entity with the books."),
      steps(
        "Ops finance → Logbook. Check open tasks at the start and close tasks at the end.",
        "Add a manager note for the day.",
        "Accrue occupancy when rent or a similar fixed cost belongs on that day. It feeds break-even and stays under controllable profit.",
      ),
      related("ops-finance-pnl", "ops-finance"),
    ],
  }),
];
