import { callout, ol, p, related, shot, steps, tip, topic, ul, warn, why } from "./helpers";
import type { GuideTopic } from "../types";

export const FLOOR_TOPICS: GuideTopic[] = [
  topic({
    id: "floor-tables",
    chapterId: "floor",
    title: "Tables & the floor map",
    summary: "Entire location or by section. Seat, combine tables, transfer, turn.",
    roles: ["owner_manager", "server", "host_operator"],
    keywords: ["floor", "tables", "seat", "map", "turn"],
    openView: "floor",
    blocks: [
      why(
        "The floor map is the live picture of the room. If table state is wrong, kitchen, payment, and turns all drift.",
      ),
      p(
        "On an order or host tablet the floor is status-colored blocks with the table number only — large, medium weight, on the fill. An empty table is a hairline ring with a clear center. Round and square tables show a few seat nubs and the number. The bar is a hollow black outline, with BAR on the longest leg and the well empty. Stools are B tiles on the guest edge and use that same thin ring. Booths stay booth-shaped (2-bench, U, L) and use the same status fill. Walls, doors, and windows are a hairline. Color is the status. If a status sits past its flash minutes, the block gets a thin flash. There is no SLA text on the map. Open checks still win over a stale Empty paint. CHECK OPEN is on the table sheet, not painted on the block. A full-service house publishes dining tables 1–N, bar seats B1–Bn with one BAR slab, and sections Dining and Bar. The live floor draws that published snapshot. When the snapshot is missing, the seeded floor shows and is published once. On a demo, Operating as changes menus and reports. The floor stays the house map. The editor and the live map show the same tables after Publish.",
      ),
      shot(
        "Floor map of solid status-colored tables and booths, each with a large table number and no chairs.",
        "Busy-night floor: colored blocks, numbers only.",
      ),
      steps(
        "PIN on a full-service order or host tablet. The bottom bar is Floor, Checks, Menu, Pay. Floor is the map. Tables size to the screen. Pinch to zoom, drag to pan. A table is at least a large tap.",
        "Tap a table. One tap reopens a sat table: the sheet lists that table’s open checks (CHECK OPEN). The big actions are Add, Send, Print check, and Pay. Set status, New check on this table, Transfer / hold, Table QR, and Mark delivered are under More — not on the first sheet. Print check for a Dining table goes to receipt printers assigned to Dining — this station sends 9100 to that Epson immediately. Job is a guest check / receipt, never kitchen / Star. The Epson slip includes a pay QR for that check when venue QR pay-or-reorder is on and Print pay QR is checked, named tax lines, and the venue timezone. Toast: “Sending to Dining receipt printer” or “No receipt printer for this section — add one in Devices.” Never silent.",
        "If there are no open checks but the table is sat, fired, unpaid, or needs bus: that status, plus Resume. Seat only when the table is truly vacant.",
        "Empty table: Seat is one tap (party of 2, or the table’s seats if fewer). That opens Menu with categories first and the current check’s lines, cash, and card always on screen. Tap an item, then Send. Seat, first item, and Send are three taps after the sheet is open. Send returns to Floor. Party size is under More.",
        "Empty + Seat only when there are zero open checks AND status is empty.",
        "Combine: drag table A onto table B. A joins B’s party. The map shows one cluster: B’s number largest, joined numbers smaller, same fill, still no chairs. Open checks stay on the table they were opened on. The sheet offers Move checks to primary, off unless you tap it. Guest QR and the guest check say T1 + T3 + T5. Tap the cluster, More, Separate: Remove one table or Separate all. A joined table with an open check stays until that check moves to another table in the party or is closed. Separating does not delete items. Each table’s color follows its own checks afterward. Host, server, bartender, and manager can do this while clocked in. Manager PIN only when Settings says Combine requires manager (off by default).",
        "Add opens Menu on that check. Send fires and returns to Floor. Map color follows the open checks. A table with a check is never painted Empty.",
        "Bar tab: the map shows that PIN’s assigned section stools (manager / supervisor see all). Tap a stool to open or attach the check. To-go never uses the floor.",
        "Transfer / hold: offer the check to a named server (they must accept) or park it in a named hold — manager hold, walkout, bar tab, or left to close — with a reason. The check stays owned by that person or the house. There is no nameless unassigned pool.",
        "After pay, the table goes closed · needs bus. Busser or server marks it cleaned and it returns to empty. Set status → Empty is blocked while open checks exist — void or close them first.",
      ),
      warn(
        "Do not Set Status → Empty while checks are open. Void or close them first. Set status is under More. Tap the table to get back to those checks.",
      ),
      related("floor-status", "floor-editor", "table-qr", "sections", "checks-comps", "check-split-move", "counter-vs-table", "kds", "loss-prevention"),
    ],
  }),
  topic({
    id: "sections",
    chapterId: "floor",
    title: "Sections, assignments, limits",
    summary: "Color-coded sections, printer assignment, extra-table grants, and order limits.",
    roles: ["owner_manager", "server"],
    keywords: ["section", "assignment", "grant", "dining", "booth", "limits"],
    openView: "employees",
    blocks: [
      why(
        "Section control stops a server from seating or ordering a table that is not theirs — unless a manager grants it.",
      ),
      ul(
        "Tables belong to sections. Receipt printers and bar printers are assigned to those sections. Print check for a table uses that section’s Epson; drinks fire to that section’s bar printer.",
        "Staff are assigned to section(s) for the shift.",
        "Server view prioritizes tables in assigned sections (Mine).",
        "Servers cannot enter orders on another section’s table.",
        "Servers cannot seat a table in another section.",
        "Transfer to staff: the named server must accept; the check stays owned until they do. Named holds (manager hold, walkout, bar tab, left to close) require a reason and stay owned by a user or the house.",
        "A manager can force reassign. Host stand can seat into a section and assign a server.",
        "A manager can grant one extra table for this shift, or just that seating.",
        "Shift grants drop at clock-out. Seating grants drop when the table is cleared.",
      ),
      steps(
        "Open Floor editor. Each room / section can name a receipt printer and a bar printer. Devices can assign the same printers to several sections.",
        "Open Staff. Tap section chips on a person (Dining / Booth / Bar).",
        "Host stand: seat a table, pick the server for that section.",
        "Server A: Floor → table → Transfer / hold → pick a server. Server B: accept from Pending accept.",
        "Use Grant to give one overflow table (shift or seating).",
        "Open Settings → Section control for lock rules.",
      ),
      tip(
        "On the order and host map, status is the fill color. A server can read a ten-table room from a few feet away: big number, no chairs.",
      ),
      related("floor-tables", "checks-comps", "invites-roles", "printers-kds", "kitchen-bar-routing"),
    ],
  }),
  topic({
    id: "checks-comps",
    chapterId: "floor",
    title: "Opening checks, transfers, comps & voids",
    summary: "Start a check, move it, and apply manager-gated comps/voids.",
    roles: ["owner_manager", "server"],
    keywords: ["check", "transfer", "comp", "void", "manager pin"],
    openView: "order",
    blocks: [
      why(
        "Every guest bill is a check. Transfers keep ownership honest. Comps and voids are the two ways money leaves a check without a tender — they need a manager when policy says so.",
      ),
      steps(
        "Open a table or start Takeout / a bar tab. That creates the check.",
        "Send items to fire them. Unsent lines can still be edited freely.",
        "To move a party to another table: Floor → Transfer, or Order → Split / move → destination table.",
        "To split or combine checks: Order → Split / move. By seat, selected items, even split, or custom $ shares. Combine two open checks (same or different tables). Move items keep operator tags. Audit log records the action.",
        "To hand a check to another server: Transfer / hold → that person, then they Accept (or a manager force-reassigns). Or park in a named hold with a reason.",
        "To void or comp a line, choose Void/Comp. If Settings require it, enter a manager PIN.",
        "Never void a closed check to “fix” a card — use the correct tender or a manager adjustment.",
      ),
      warn(
        "Manager PIN is a station override, not Platform Admin. Owners set whether comps/voids require it in Settings.",
      ),
      related("floor-tables", "tenders-tips", "audit", "counter-vs-table", "check-split-move"),
    ],
  }),
  topic({
    id: "check-split-move",
    chapterId: "floor",
    title: "Split, combine, and move checks",
    summary:
      "By seat, items, even split, or custom $. Combine checks. Move items or the whole check. Operator tags stay.",
    roles: ["owner_manager", "server"],
    keywords: ["split check", "combine check", "move items", "seat split", "even split"],
    openView: "order",
    blocks: [
      why(
        "A four-top that wants two bills should not wait on a spreadsheet. Split and move stay on the same floor; the audit log shows who did it.",
      ),
      steps(
        "Open the check. Tap Split / move.",
        "Split: selected items to a new check; by seat; even split of items into 2–8 checks; or custom dollar shares of the remaining balance.",
        "Combine: pick another open check (same table or another). Lines merge. Operator / vendor tags stay on each line.",
        "Move items onto another check, or move the entire check to another table (combines if that table already has a check).",
        "Assigned servers can mutate their own checks. Managers can mutate any. Actions write the audit log.",
      ),
      warn(
        "Custom $ shares set each check’s remaining due. Food lines stay on the original unless you also move items. Do not invent a second card processor for a split.",
      ),
      related("checks-comps", "floor-tables", "host-capture", "audit"),
    ],
  }),
  topic({
    id: "counter-vs-table",
    chapterId: "floor",
    title: "Counter vs table service",
    summary: "QSR/café flow versus seated dining.",
    roles: ["owner_manager", "server"],
    keywords: ["counter", "qsr", "cafe", "table service", "takeout"],
    openView: "takeout",
    blocks: [
      why(
        "The same POS covers a seated dining room and a counter. The difference is whether a table holds the check.",
      ),
      ul(
        "Table service — PIN on an order station opens Floor, Checks, Menu, Pay. The map is status color and the table number. Seat, add an item, Send. Print check follows the table’s section receipt printer. Handhelds ring and fire. Cash and drawer kick stay on a Terminal; that kick hits the Epson that printed the check. To-go, Bar tab, clock, and closeout are under Checks → Other jobs.",
        "Counter / QSR — ticket/queue and to-go. No dining floor on the order glass.",
        "Drive-through — lane on the order tablet, window on the host tablet. No dining room map.",
        "Bar tab — from the floor, tap Bar tab, then pick a stool on your section rail. Empty stool opens a tab; occupied attaches the check. To-go stays off a stool. Still Quantum Payments for cards.",
      ),
      steps(
        "For counter / to-go: open To-go, name the guest, build the check, take payment, send. To-go never sits on a stool.",
        "For a bar tab: tap Bar tab. The floor shows that PIN’s assigned section(s) only (manager / supervisor see all). Tap a stool — do not skip seating.",
        "For table: never take a card on an unnamed counter ticket if the guest is seated — attach the table so ODS and the floor stay in sync.",
        "Hall / pod guests can still pay once at a host stand even if they ordered at several stalls.",
      ),
      related("floor-tables", "multi-operator-orders", "tenders-tips"),
    ],
  }),
  topic({
    id: "host-stand",
    chapterId: "floor",
    title: "Host stand (waitlist & seating)",
    summary: "Host bar: Floor, Checks, Menu, Pay. Map is status color and the table number.",
    roles: ["owner_manager", "server"],
    keywords: ["host stand", "waitlist", "reservation", "seat", "quoted wait", "to-go", "bar tab"],
    openView: "waitlist",
    blocks: [
      why(
        "The FOH host keeps the door honest so servers are not seating over each other. This is not the hall Host Venue role. After PIN you pick one job.",
      ),
      ul(
        "After a host / supervisor / manager PIN, the bar is Floor, Checks, Menu, Pay. The short menu under Checks → Other jobs is Waitlist, To-go, and Close out. The floor shows clocked in HH:MM.",
        "To-go starts a takeout check with the same pay and print path as the order station.",
        "Floor is a white workspace, full bleed. An empty table is a hairline ring with a clear center and a medium-weight number inside. Any other status fills that shape with the status color and a high-contrast number. Round tables are circles. Other tables are rounded squares. A few seat nubs sit on round and square tables. The bar is a hollow black outline. BAR sits on the longest leg, and the well stays empty. Stools are B1…Bn tiles on the guest edge, with the same thin ring as an empty table. Walls, doors, and windows are a hairline on the white. Top shows the staff name and local time, plus a tight icon row for messages, print, and switch user. Bottom left is Dine in | To go. The other corner is Tickets search. Tap a table with open checks — one tap — for Add, Send, Print check, Pay. Empty + Seat only when vacant. If the published floor has tables, they are drawn. If that snapshot is empty, the last saved draft is drawn and the banner says Publish floor to lock layout. A failed picture or a demo seed does not hide the tables.",
        "Kitchen / cook PIN: Close out (End shift) and Done only. No to-go from this tablet.",
        "Server PIN: Floor and To-go only when Servers may use the host stand is on; otherwise clock and use an order tablet.",
      ),
      steps(
        "PIN in on the host tablet. You land on Floor. Add a walk-in from Checks → Waitlist with party size and quoted wait.",
        "When a table in the right section is empty, seat onto that table. Optionally assign the server for that section.",
        "Tap To-go for pickup. Pay and print as usual.",
        "The assigned server owns a seated check. They may Release it to the offer pool; another server Accepts.",
        "Respect section locks — a manager grant is required to seat across sections.",
      ),
      related("floor-tables", "floor-status", "table-qr", "sections", "invites-roles", "role-host-stand", "device-roles"),
    ],
  }),
  topic({
    id: "floor-editor",
    chapterId: "floor",
    title: "Floorplan editor",
    summary: "Drag-and-drop rooms, tables, 4-top / U / L booths, and barstools. The live floor uses the same layout.",
    roles: ["owner_manager", "host_operator"],
    keywords: ["floor editor", "copy", "drag", "resize", "booth", "booth 4-top", "U booth", "L booth", "barstool", "layout", "room", "chair", "seating", "how many", "reset table numbers", "grid", "ruler", "snap", "align", "zoom", "fit room"],
    openView: "floor_editor",
    blocks: [
      why(
        "The runtime floor is the saved layout — not a list. If the map is wrong, hosts seat the wrong room and QR tokens sit on the wrong sticker.",
      ),
      ul(
        "Owner, manager, and host stand draw the room. Entire location vs By section matches the runtime floor.",
        "Place table, Booth 4-top, Booth U, Booth L, barstool, wall, door, window, host stand, bar top, or other. Icons match the plan shape. Drag to move. Corner handle resizes. Walls stretch from the end handles. An end snaps to a nearby wall end or to a point along another wall, about a hand’s width on the plan, and the two walls share that point. A shared corner draws closed. Pull past the snap and the walls separate. Publish shows the same corner on the live floor. The room is width × depth in feet and inches, for example 42 ft 6 in by 28 ft. A selected table, booth, bar, wall, or host stand edits length × width, or a diameter, in feet and inches, and the drawing updates immediately. A 4-top starts at about 3' × 3'. Walls take a length, and thickness when you set it. Changing the room keeps each object’s real size. The editor shows a small dimension on the selected piece. Fit room fills the workspace with the room rectangle and a small margin. Zoom changes from the scroll wheel, a pinch, the zoom buttons, or Fit room. Changing the room fits it again. Clicking a piece, dragging it, or pulling a handle keeps that zoom and that pan. Space or the middle button pans. Fit room returns to the fitted view. The live floor on a tablet opens fitted the same way. It uses that scale and does not print the measurements. The bar top is a hollow slab, straight, L, U, island, or a polyline. Each leg is a length in feet and inches, and the legs of an L share a corner. Counter depth defaults to 24 in and is the rail width, not the bounding box. Both the inside and outside edges are a black outline, and the band between them is clear. BAR, or the bar’s own name, is centered on the longest leg and clipped to that band. Rotating the bar or changing a leg keeps the name on that leg, upright. The well of an L or U stays empty. A 22 ft bar occupies 22 ft on the same scale as the tables. The live floor draws that same slab. While a piece is selected or dragged, the editor shows the distance in feet and inches to the nearest room edge and to the nearest wall, table, bar, or door. Those guides hide when nothing is selected. The live floor does not print them. Copy asks how many copies, a whole number of at least 1. Each copy is a new piece with the same kind, size, rotation, and section, placed about 1 ft right and 1 ft farther down than the one before so they do not stack. Table numbers take the next free number, such as 18 then 19, or B10 then B11. Cancel leaves the original alone. Zero sizes are refused. Bar top shape is Straight, L, U, island, or a custom polyline. The bar selects on the dark slab. A click on open floor beside an L or U leaves the bar unselected. Each leg has an end handle: drag it to lengthen or shorten that leg, and the corner stays put. A straight bar has a handle at each end of the long axis. Stools sit on the guest side of the rail, flush to the outside stroke, and stay with a leg as it changes. Publish stores each leg’s length. Rotate 90° turns the selected piece and its handles together, 0→90→180→270→0, around its center and saves that angle. A wall, door, or window keeps a black end handle on each new end. Drag that handle and the piece lengthens along that direction. The selection outline follows the rotated piece. Tables, booths, and bar-leg handles use the same spin. Booth L/U and bar L/U use that angle on the live map.",
        "Booth 4-top: two parallel benches + table (capacity 4). Booth U: three-sided banquette (default 6, 4–8). Booth L: two benches at 90° (default 5, 4–6). Seats stay attached — no orphan chairs. Chair, stool, and booth-bench marks scale with the fixture and the seat count (a 2-top is tighter than an 8-top). They stay proportional when you zoom. They do not cover the table number or eat the next table.",
        "Table, Booth 4-top, Booth U, Booth L, and Barstool ask How many? The count starts at 1. The first piece sits where you last clicked the room, or in the center. Each further piece sits about 1 ft over so they do not stack. New tables and booths take the next free number, including a gap such as 3 when 1, 2, and 4 are already used. New stools take the next free B number.",
        "Reset table numbers asks, then numbers dining tables and booths from 1, from the top of the room and left to right. A booth that already uses a B number stays out of that sequence. Stools on each bar become B1, B2, and so on along the rail. A second bar continues the B numbers so two rails do not both start at B1.",
        "Grid draws the size you pick: 6 in, 1 ft, or 2 ft. Ruler prints feet and inches along the room edges. Snap is Off, Grid, or Objects. With two or more pieces selected, align Left, Right, Top, or Bottom to the outer edge of the set, so two tables can meet a wall that is in the set. Distribute horizontal and Distribute vertical even out three or more. The live floor stays as published until you Publish.",
        "Table icons are a light fill or a hollow top with a dark number and a few seat nubs (four on a square, six on a round). Square no seats is a compact square with no nubs, for a tight 2-top. The bar is a hollow black outline. BAR, or a custom name, sits on the longest leg inside that outline. A vertical leg stacks the letters so they stay upright. Stools are small rounded squares labeled B1, B2, and so on.",
        "Select a bar and pick the side before Generate. Straight: Guest side A or Guest side B. L and U: Outside (around the bar) or Inside (the well). An island is around the perimeter only. Then set the count: one number for a straight bar or island, leg A and leg B for an L (corner seat stays off), left / rear / right for a U. Generate puts the B tiles flush on that edge, not on the slab. Changing the side asks before it moves stools that are already there. Drag still snaps a stool against that edge.",
        "Properties: label (table number), seats, room/section color, kind, rotation. Each fixture gets a stable table QR token.",
        "Rooms are sections. Multi-room houses switch rooms in the editor and on the live floor.",
        "Layout saves to the location (all paired tablets pick it up). Rotate a token if a sticker is compromised.",
      ),
      steps(
        "Open Floor → Floor editor (or Floor editor in nav).",
        "Add a table, Booth 4-top, Booth U, Booth L, or barstool. How many? starts at 1. The first sits on your last click, or in the center, and the rest step about 1 ft so they do not stack. Numbers are the next free integer, or the next B number for a stool. Drag onto the canvas. Resize from the corner. Shift-click or drag a box to select several. Delete or Backspace removes them, and asks once when more than one is selected. Copy asks how many, then places that many of each selected piece a foot right and down with the next number. Reset table numbers orders dining tables and booths from the top, left to right, and stools along each bar. A booth that already uses a B number stays out of the dining sequence. Grid, ruler, and snap (Off, Grid, or Objects) are on the editor. Align Left, Right, Top, Bottom, or distribute the selection. Clear slate removes every object in the room after you confirm. The room width, depth, and section list stay. The live floor stays as published until you Publish. Clicking a piece keeps the current zoom. Rotate 90°.",
        "Set label, seats, and room. Show QR and copy the guest link.",
        "Return to Floor on an order or host tablet. The editor and the live floor are a white workspace. Walls, doors, and windows sit where you drew them; on the live floor they are a hairline, and the host stand stays a block. The bar is a hollow outline with the name on the longest leg. A house name can sit small on the line. Empty dining tables are hairline rings with a medium-weight number inside and a few seat nubs. Any other status fills the circle or rounded square and keeps those nubs. Square no seats has none. Stool tiles use that same thin ring. Publish writes the full layout, so the editor and the live map show the same pieces.",
      ),
      tip(
        "Go live always keeps the floorplan. Practice checks can be erased; tables stay where you drew them.",
      ),
      related("floor-tables", "floor-status", "table-qr", "sections"),
    ],
  }),
  topic({
    id: "floor-status",
    chapterId: "floor",
    title: "Table statuses, colors & flash",
    summary: "Pipeline from empty to cleaned, host-mapped colors, SLA flash.",
    roles: ["owner_manager", "server", "host_operator"],
    keywords: ["status", "flash", "SLA", "color", "sat", "bus", "cleaned"],
    openView: "settings",
    blocks: [
      why(
        "Color is how a host reads the room from the stand. Flash is how a table that sat too long gets attention without a radio call.",
      ),
      ol(
        "Empty",
        "Sat · no order",
        "Drinks fired",
        "Food fired",
        "Food delivered",
        "Dining · unpaid",
        "Closed · needs bus — cleaned returns to empty",
      ),
      p(
        "Host settings choose which steps are on, the color per status, flash minutes (0/blank = off), who may tap a status (server, host, manager), and who may seat (host stand, manager, or both). Host stand also has Servers may use the host stand and Host may open bar tabs.",
      ),
      ul(
        "Automatic table status is on by default. Venue can turn the whole auto off, or turn individual steps off in Settings → Floor statuses.",
        "Host seats / table assigned → Sat · no order. First drink fire (no food yet) → Drinks fired. Food fire → Food fired (keeps drinks if both). All fired food marked delivered (server/expo) → Food delivered. All items delivered and the check still open → Dining · unpaid. Check paid in full (staff or QR) → Closed · needs bus (or Empty if that step is off). Busser / staff table cleaned → Empty.",
        "Do not tap Set status when the event already happened. Manual Set status still overrides until a later event.",
        "Open checks paint the table from the check, not stored Empty. CHECK OPEN is the sheet heading — the map does not print it on the block.",
        "When minutes are exceeded the block flashes a thin outline. No SLA label on the map. A staff notice still fires. A status change clears the flash.",
      ),
      steps(
        "Settings → Floor statuses, flash & QR.",
        "Turn steps on or off. Map colors. Set flash minutes (0/blank = off).",
        "Seat a table and wait past the sat · no order threshold to see the pulse.",
      ),
      related("floor-tables", "floor-editor", "table-qr", "host-stand"),
    ],
  }),
  topic({
    id: "table-qr",
    chapterId: "floor",
    title: "QR order & pay",
    summary: "Combinable modes: self-serve, reorder after staff open, pay/split, ticket QR, table tents.",
    roles: ["owner_manager", "server", "host_operator"],
    keywords: ["QR", "table QR", "pay QR", "hybrid", "full QR", "token", "table tent", "ticket QR"],
    openView: "settings",
    blocks: [
      why(
        "The sticker on the table is a deep link to that seat at this location. The guest is at the location — table tent / check QR only. No e-commerce cart, no alcohol delivery SKU, no shipping a bottle. Guests add to the open check. Capture is always Quantum Payments — one guest tender, split to each brand’s merchant when operators share the check.",
      ),
      ul(
        "Full self-serve — scan table QR, open a check, order, pay. Opening a check notifies host/server.",
        "Reorder after open — QR adds items only if a staff-opened check already exists. Empty table: “see your server.” Never silently start a ticket.",
        "Pay / split — QR pays the open check (card, gift, or both). Optional even / by-item / by-seat split and tip. Staff split, void, send, print check, and pay stay on the selected check from Floor table view — Table QR is the guest tent, not the staff split path.",
        "Print pay QR — Epson guest check (Print check / Print all open) includes a native thermal QR when the receipt printer has Print pay QR checked (default on for TM-T20). The QR is the public guest URL for THIS open check: the table’s public token plus the check number (reorder + pay, no staff PIN). If the table has no token, Print check mints one and saves it on the table — never a random or demo token. Scan opens that table’s open check (e.g. T1-03), not “Unknown table.” Star kitchen tickets never get a pay QR. Not a raster dumped as kitchen text.",
        "QR pay in full: the check closes on the same ledger as staff Cash/Card. The assigned server’s station notifies — sound, vibrate, and banner “Table N paid — QR.” Expo is included only if Notify expo on QR pay is on. Floor goes Closed · needs bus (or Empty if that step is off). Partial QR pay: check stays open, Dining · unpaid, banner “Table N partial QR pay $X.”",
        "Table tents — printable QR per table (and seat). Print the sheet from Floor.",
        "Order allow: none / drinks / food / food and drinks. Age affirm when drinks are on.",
        "QR pay in full always closes the check and flags Closed · needs bus. Partial QR pay leaves the check open.",
      ),
      steps(
        "Settings → Floor statuses, flash & QR. Turn on the flags that match the house.",
        "Print table tents from Floor, or copy a table QR from the table card / Floor editor.",
        "On Order, Print check encodes the table’s public guest URL for that check number. Scan it on the guest phone — sites.summex.app or the app guest route — to open that table’s open check (reorder + pay).",
        "Guest UI is public — no PIN, no CRM. After pay they stay on thank-you, not Sign in.",
        "Lines keep their operator. One tender. Receipt grouped by vendor. Finix splits by owner.",
        "When the guest sends from QR, kitchen print is a venue job — a docked host, ODS, or print agent writes 9100. The guest phone never prints.",
      ),
      warn(
        "On-premise only. The guest is at the location. Table tokens are location-scoped. Rotate if a sticker walks. Ticket QR expires; reprint for a fresh code. Live cards on QR still need an approved Quantum application — training uses sandbox. No delivery and no shipped alcohol.",
      ),
      related("floor-tables", "floor-status", "quantum-payments", "host-capture", "type-food-hall", "printers-kds"),
    ],
  }),
];
