import { callout, p, related, steps, topic, ul, warn, why } from "./helpers";
import type { GuideTopic } from "../types";

export const PLATFORM_CRM_TOPICS: GuideTopic[] = [
  topic({
    id: "platform-crm",
    chapterId: "platform",
    title: "CRM (accounts, contacts, deals)",
    summary: "Leads, accounts, opportunities, and a timeline — not POS guest CRM.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["crm", "lead", "account", "contact", "deal", "opportunity", "activity"],
    blocks: [
      why(
        "Sales and success need a house record before there is a tenant. CRM lives on the control plane. Guest loyalty is a different product.",
      ),
      ul(
        "Accounts are companies. Stage follows Lead → Qualified → Proposal → Contract → Onboarding → Live → Churned.",
        "Contacts are people on an account (email, phone, role).",
        "Opportunities carry monthly amount, plan, probability, and close date.",
        "Activities are notes, calls, emails, tasks, and stage changes. Tasks have due dates.",
        "Get pricing / intake creates a prospect that syncs into CRM automatically.",
      ),
      steps(
        "Platform → CRM. Add lead, or wait for intake to appear.",
        "Log a follow-up with a due date. Open the account timeline.",
        "Start onboarding when the deal is ready — that writes a real onboarding run, not a demo seed.",
        "Go live only after org, location, and owner invite exist. The org then shows under Tenants.",
      ),
      warn("CRM never seeds public demo tenants or PIN 0000 rooms."),
      related("saas-lifecycle", "platform-tenants", "prospect-intake"),
    ],
  }),
  topic({
    id: "saas-lifecycle",
    chapterId: "platform",
    title: "Pipeline & lifecycle",
    summary: "Lead through live, wired to quotes, contract, and onboarding.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["pipeline", "kanban", "quote", "contract", "go live", "churn"],
    blocks: [
      why(
        "The subscriber lifecycle is one path. A quoted house is not a tenant until onboarding creates an org.",
      ),
      p(
        "Board columns are Request → Sent → Accepted → Contracted → Onboarding → Live. Rejected and Churned are exits only. Cards show name, amount, stage, one-line meta, Open, and the next allowed action. Details live on Open.",
      ),
      steps(
        "Get pricing creates a Request. Open the account. Rebuild from intake so the quote has a monthly software package (not setup-only). Scroll the account pane to modules, monthly total, and Send (Save/Send stay pinned). Send → Sent.",
        "Prospect accepts or requests changes, or Admin records accept → Accepted.",
        "Record contract (checkbox + date) → Contracted. Start onboarding needs that accepted monthly package. OVERRIDE + reason to skip.",
        "CRM Start onboarding uses the same gate.",
        "Finish host onboarding, then Go live. Training is a location substatus — not a skip of the quote.",
      ),
      callout("Go live", "Requires a real org and location. Never a demo seed."),
      related("platform-crm", "onboarding-wizard", "quote-contract"),
    ],
  }),
  topic({
    id: "platform-tenants",
    chapterId: "platform",
    title: "Tenant directory",
    summary: "Live orgs, locations, operators, plan, health. Suspend with confirm.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["tenant", "org", "suspend", "mrr", "directory"],
    blocks: [
      why("Once a house is live it is a tenant — billed software, not a prospect card."),
      ul(
        "Directory shows plan, location count, operators, MRR proxy from the deal, past-due, open tickets.",
        "Each location shows training | scheduled_live | live. Training is sandbox cards; live cards wait for processor approval.",
        "Drill-in lists locations, operators, and users.",
        "Suspend requires confirm. Reactivate restores access. Nothing is silently deleted.",
      ),
      related("saas-billing", "saas-support", "empty-start"),
    ],
  }),
  topic({
    id: "saas-billing",
    chapterId: "platform",
    title: "Software billing",
    summary: "Plans, invoices, Stripe or sandbox — not Quantum Payments.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["stripe", "invoice", "mrr", "subscription", "saas fee"],
    blocks: [
      why(
        "Software subscription is a different rail from guest cards. Mixing them is how houses get confused at close.",
      ),
      ul(
        "Plans and entitlements (locations, seats) live on org_subscriptions.",
        "Without STRIPE_SECRET_KEY the console is sandbox: assign a plan and issue invoices by hand.",
        "Failed invoices surface on Billing and Reports. They do not stop cash on the floor.",
      ),
      related("platform-tenants", "quote-contract"),
    ],
  }),
  topic({
    id: "saas-support",
    chapterId: "platform",
    title: "Support & success",
    summary: "Tickets linked to accounts, macros, health signals.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["ticket", "support", "macro", "csm", "health"],
    blocks: [
      why("Success needs a thread on the account, not a private inbox."),
      steps(
        "Open Support. New ticket, optional account link, first comment.",
        "Use macros for go-live, network, billing vs cards, PIN vs password.",
        "Health on Tenants and Reports: open tickets, past due, failed invoices.",
      ),
      related("platform-crm", "saas-billing", "network-readiness"),
    ],
  }),
  topic({
    id: "saas-reporting",
    chapterId: "platform",
    title: "SaaS reporting",
    summary: "Funnel, pipeline value, live locations, churn — real rows only.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["funnel", "pipeline value", "churn", "reports"],
    blocks: [
      why("Admin metrics are for the book of business, not a POS daypart."),
      ul(
        "Funnel counts CRM accounts by stage.",
        "Pipeline value sums opportunity monthly amounts.",
        "Live orgs and locations are real onboarded tenants (there are no demo leftovers).",
      ),
      related("platform-crm", "saas-lifecycle", "platform-tenants"),
    ],
  }),
  topic({
    id: "factory-reset",
    chapterId: "platform",
    title: "Factory reset",
    summary: "Wipe all business data. Keep Admin bootstrap with forced password change.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["factory reset", "wipe", "danger zone", "bootstrap", "testing"],
    blocks: [
      why(
        "Build and test cycles accumulate junk orgs. Factory reset returns the store to first-run: only the platform Admin login.",
      ),
      steps(
        "Platform → Settings → Danger zone.",
        "Read the warning. Check the box. Type RESET. Re-enter the Admin password.",
        "On success you are signed out. Sign in as Admin with the initial password.",
        "You must set a new password (8+ characters; not the bootstrap password).",
      ),
      ul(
        "Deletes orgs, locations, operators, CRM, prospects, tickets, invoices, ledger, devices, and non-admin users.",
        "Does not seed demo venues.",
        "Plans and software pricing catalog stay.",
        "Server-only. Floor PIN and location owners cannot run it.",
      ),
      warn(
        "Irreversible. Testing-only. Turn off Factory reset in Settings → Security, or set FACTORY_RESET_ENABLED=false. Production is off unless that env is true.",
      ),
      related("platform-settings", "admin-bootstrap", "empty-start", "platform-tenants"),
    ],
  }),
  topic({
    id: "platform-settings",
    chapterId: "platform",
    title: "Platform settings",
    summary: "Typed sections for name, security, CRM, plans, gifts, flags, team — never raw JSON.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: [
      "settings",
      "plans",
      "billing",
      "gift defaults",
      "feature flags",
      "team",
      "security",
      "json",
    ],
    blocks: [
      why(
        "Operators configure Summex through labeled forms. Pricing is a plan editor, not a JSON blob. Values live in the database.",
      ),
      ul(
        "General — display name, support contacts, timezone, currency, public URLs.",
        "Security & auth — password length, session idle, PIN length/lockout, first-login change, factory-reset toggle.",
        "CRM & pipeline — lead source chips, ordered stages, default owner, Qualified follow-up rule.",
        "Onboarding — checklist template, network warn-only, default plan, auto-invite.",
        "Plans & billing — name, code, active, monthly per location, setup (waive / flat / by package), quote expiry, optional terminal lines, module checkboxes. Intake maps to paid packages. Stripe is Connected or Not configured. No JSON editor.",
        "Payments & gift defaults — Quantum Payments sandbox/live, chargeback fee, issuer mode, term, residual, house retains, legal disclaimer.",
        "Communications — SMS/email status, SMS included per location (default 500), overage mode (bill at cost / block / warn) and pass-through rate, AI daily cap (default 200) and included-with (Ops pack by default), waitlist and invite templates with {{tokens}}. Email is never surcharged.",
        "Feature flags — global defaults for new orgs. Per-plan overrides stay under Plans. HR modules are per employer entity, not a platform JSON blob.",
        "Data & compliance — waitlist phone and audit retention, privacy notes.",
        "Team — invite platform users (admin / sales / success / read only). Deactivate anyone except the last admin.",
        "Danger zone — factory reset only if Security allows it. Type RESET.",
      ),
      steps(
        "Platform → Settings. Pick a section.",
        "Edit the controls. Save that section. A toast confirms success or the validation error.",
        "Plans: open a plan card, change monthly price and module checkboxes, Save.",
        "Gifts: set issuer mode and residual from dropdowns — there is no JSON textarea.",
      ),
      warn("Access is platform_admin only. Floor PIN never opens this control plane."),
      related("factory-reset", "saas-billing", "platform-crm", "platform-admin", "go-live-ops"),
    ],
  }),
  topic({
    id: "go-live-ops",
    chapterId: "platform",
    title: "Go-live ops checklist",
    summary:
      "Neon, auth URLs, processor approval, reader — software go-live is not a live Visa.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: [
      "go live",
      "neon",
      "auth",
      "processor",
      "reader",
      "checklist",
      "production",
    ],
    blocks: [
      why(
        "Training week is a software go-live. The first live card is a processor + hardware go-live. Do not treat them as the same day.",
      ),
      ul(
        "Database — production Postgres (Neon or equivalent) with migrations applied. No demo seed.",
        "Auth URLs — Sign in and invite links on the public www host. POS/ODS/kiosk on the app host when that host is live; otherwise stay on this origin.",
        "Processor — host Quantum Payments application approved. Training always sandboxes even if someone stored a live-mode preference.",
        "Reader — enrolled Finix/Quantum reader supplied through Summex for live card-present. Tablets, printers, and drawers stay BYO. Customer-owned Square/Stripe/bank terminals are not supported. Live cards fail closed without an enrolled reader.",
        "Tenant status — Tenants list shows training | scheduled_live | live. Owner chooses keep/erase; menus, recipes, staff, settings always stay.",
      ),
      steps(
        "Confirm the location is still Training until the owner types GO LIVE NOW or the schedule fires.",
        "Confirm the host (and any operator) Quantum application is approved before expecting a live Visa.",
        "Pair the reader. Take a sandbox card in training first.",
        "Owner goes live. Cash still works if the processor is down.",
      ),
      warn(
        "Available in training; live cards require an approved Quantum application and an enrolled reader. Factory reset is a danger-zone test tool — not a go-live step.",
      ),
      related(
        "location-training",
        "platform-tenants",
        "quantum-payments",
        "factory-reset",
        "access-urls",
      ),
    ],
  }),
];
