import { callout, p, related, shot, steps, tip, topic, ul, warn, why } from "./helpers";
import type { GuideTopic } from "../types";

export const SAAS_TOPICS: GuideTopic[] = [
  topic({
    id: "prospect-intake",
    chapterId: "saas",
    title: "Prospect intake",
    summary: "Branching selector wizard and a snapshot quote.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["intake", "prospect", "get pricing", "interview", "quote", "saas"],
    blocks: [
      why(
        "Pricing should start from how the house actually runs — single brand vs host + operators — not from a generic SKU list.",
      ),
      steps(
        "Open Get a price. Pick house shape: single operator, host + tenants, or shared venue (peers). The shape stays selected until you pick a different one.",
        "Service style is filtered by shape (counter, full service, bar-only, mixed, hall/stalls). Shared venue asks for entity count on the next step (default 2). Modules are checkboxes; options the shape cannot use stay hidden.",
        "Enter counts (locations, entities if not single, seats, stations, kiosks, Quantum readers). The live catalog recalculates monthly software. Optional: paste a description to pre-check boxes, then confirm in the wizard.",
        "Review: monthly software + optional setup + reader line. Processing is a note, not the software total. Email last — that creates a CRM lead.",
        "The stored quote is the wizard answers, not a stale food-hall default. Two operators in one building is shared venue with entity count ≥ 2.",
      ),
      callout(
        "Status machine",
        "Request → Sent → Accepted → Contracted → Onboarding → Live. Rejected / Churned are exits only. You cannot skip a stage without OVERRIDE.",
      ),
      shot(
        "Get a price — shape, service style, modules, counts, live quote.",
        "Selector wizard with a live monthly software total.",
      ),
      related("quote-contract", "onboarding-wizard", "single-vs-multi"),
    ],
  }),
  topic({
    id: "quote-contract",
    chapterId: "saas",
    title: "Quote, accept, contract signed",
    summary: "Monthly software package from intake, then accept and contract. Setup is never the only line.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["quote", "contract", "accept", "signed", "pipeline"],
    blocks: [
      why(
        "Commercial agreement is a human step. The product records it; it does not e-sign the paper for you.",
      ),
      steps(
        "Get pricing shows a live quote: Counter $0, Full service $149/loc, Multi-operator $299/loc + $49/tenant. Prospect toggles modules (ops pack $99, extra stations $19, kiosk $29, terminal lease $15). Request this quote snapshots those lines.",
        "Dollar amounts live in Settings → Plans & billing (Get a price catalog forms). Setup defaults to $0. Processing is a note, not software $. Quotes also show: Email included. SMS: 500/mo included, extra at cost. AI reports in Ops pack. PDF, email, and CRM use the same lines. Staff stations are Android tablets running Summex Station (sideload now; Play later). Printers, drawers, and gift MSR are BYO. Live cards require Finix/Quantum readers supplied through Summex (drop-ship to the site). Customer-owned Square/Stripe/bank terminals are not supported. iPad and browser POS are not a supported house setup.",
        "Save draft, then Send quote. The account quote form scrolls — modules, monthly total, setup, and Send sit in that pane (Save/Send stay pinned at the bottom). Email and Print/PDF show monthly software, processing as a separate note (guest card rate from platform default, Quantum Payments, not mixed into software $), expires-on, Accept and Request changes.",
        "Merchant taps Accept, or Request changes, or Admin marks accepted. Status becomes accepted. Not a live tenant yet.",
        "Platform Admin records the contract (checkbox + date) → Signed. That creates the venue-owner login and emails app.summex.app/login, username, and a one-time password. They must change it on first login. OVERRIDE + reason for an admin skip of the path.",
        "Do not create the org by hand unless you are skipping the commercial path for an internal site. Do not fill the subscriber’s menus or staff.",
      ),
      warn(
        "Accepting a quote does not charge cards and does not create POS data. Onboarding is the provisioner.",
      ),
      related("prospect-intake", "onboarding-wizard", "platform-admin"),
    ],
  }),
  topic({
    id: "onboarding-wizard",
    chapterId: "saas",
    title: "Onboarding wizard",
    summary: "The venue owner completes setup after contract signed. Platform only records the contract and can resend the invite.",
    visibility: "platform",
    roles: ["platform_admin", "owner_manager", "host_operator"],
    keywords: ["onboarding", "setup", "wizard", "go-live", "contracted"],
    openView: "settings",
    blocks: [
      why(
        "Onboarding is the subscriber’s job. Platform records the signed contract; the owner builds the house.",
      ),
      steps(
        "After quote accepted, Platform records contract signed. That emails the venue owner — not a control-plane login.",
        "Owner logs in at app.summex.app/login, changes the one-time password, lands on the venue onboarding wizard — never the PIN pad, never platform CRM.",
        "Nine gated steps, save-and-resume: building name/address/timezone; peer vs single-operator; entity count (peer ≥ 2); service style; cash-discount rounding; QR mode; tax venue-shared vs per-entity; name each operator and invite their POC; shared device counts.",
        "No Finix form on the venue. No menu on the venue. Finish → onboarding / awaiting entities.",
        "Each operator completes their own legal packet, Finix application, menu, staff PINs, and tip/closeout. Training sandbox until the owner schedules go-live.",
        "Platform does not open or fill the subscriber wizard. Pipeline Resend invite is not impersonation.",
      ),
      tip(
        "You can save and return. Each step writes real rows (org, location, members) — not a mock. Network readiness is advisory.",
      ),
      related("create-org", "single-vs-multi", "peer-venue-setup", "tenant-invites", "settlement", "network-readiness", "access-urls", "empty-start"),
    ],
  }),
  topic({
    id: "peer-venue-setup",
    chapterId: "saas",
    title: "Peer venue setup (shared building)",
    summary:
      "A named building with independent selling entities and no host merchant. One guest check. Splits by line owner.",
    roles: ["platform_admin", "owner_manager", "host_operator", "vendor_operator"],
    keywords: [
      "peer venue",
      "shared building",
      "no host merchant",
      "entity onboarding",
      "billing contact",
      "android",
    ],
    blocks: [
      why(
        "Two operators in one building do not need a landlord brand. The venue owns the floor, devices, QR, cash rounding, and the SaaS bill. Each entity is its own merchant.",
      ),
      ul(
        "Venue (building wrapper): name, address, timezone, floorplan, sections, devices, printers, QR policy, cash-discount rounding, waitlist/kiosk, shared check, billing contact, subscription. hostEntityId is null. No Finix identity. No menu. No house sales.",
        "Entity (selling operator): legal/KYC, Finix merchant, payout, menu, recipes, modifiers, inventory, staff, schedule, tip/closeout, owned-lines P&L.",
        "Device belongs to the venue. Role: order, ODS, host, or kiosk. Pair from Devices by QR or short code. Role can change after activate.",
        "Line on a check requires an entity. Settlement, labor, gift redeem, and chargebacks use owned lines only.",
        "Single-operator shop uses the same screens with entity count = 1.",
        "Billing contact is not a merchant. Password login never hits the staff PIN pad.",
      ),
      steps(
        "Get a price: Shared building — no host merchant. Entity count ≥ 2. Quote itemizes Finix/Quantum readers (qty × unit), setup, monthly modules. Android tablets only.",
        "Quote accepted + contract signed. Email to the billing contact: app.summex.app/login, username, temp password, must-change-on-first-login. Lands on the venue wizard.",
        "Venue owner finishes the nine steps and invites each operator POC.",
        "Each operator: legal name, DBA, EIN, owners, bank, MCC (5812 / 5813 / other), required Finix application, menu, staff PINs, tip/closeout/till, optional invoices.",
        "Status per entity: invited → in progress → payments pending → ready. Venue cannot mark training-ready until every entity is at least in progress. Card-live waits until every entity Finix is approved and at least one reader is enrolled.",
        "Training = real org, sandbox cards, practice tickets. Go live now (type GO LIVE NOW) or schedule a datetime. Keep or erase practice tickets; menus and inventory stay.",
      ),
      warn(
        "Do not invent a host merchant so two peers can share a floor. Do not send password sessions to the PIN pad. Staff stations are Android tablets — not iPad or browser POS.",
      ),
      related("onboarding-wizard", "single-vs-multi", "tenant-invites", "device-roles", "location-training", "login"),
    ],
  }),
  topic({
    id: "tenant-invites",
    chapterId: "saas",
    title: "Host invites operators (tenants)",
    summary: "After the host is ready, the host sends email/SMS links. Operators complete their own onboarding.",
    visibility: "platform",
    roles: ["platform_admin", "owner_manager", "host_operator"],
    keywords: ["tenant", "operator invite", "self-serve", "host_ready", "SMS", "email"],
    blocks: [
      why(
        "SaaS onboards the host completely. Operators under a host are the host's job. Each tenant POC gets a link and fills their own legal, stations, and payout stub.",
      ),
      steps(
        "Finish host onboarding (org, location, owner, plan, go-live). Status is host_ready / live.",
        "Host owner opens POS → Settings → Operators / Tenants.",
        "Add a tenant slot: display name, type (bar / kitchen / retail / other), POC email and phone.",
        "Send invite (email and/or SMS). Copy the link if mail is logged-only.",
        "POC opens /tenant/…, sets a password, completes the wizard including the payout account (Quantum Payments application). Guests never see the processor name.",
        "Host sees onboard status and Quantum Payments status (pending / approved). Tenant cannot change host billing or other tenants. Live split payouts wait until the operator application is approved; they can still be ticketed on sandbox and cash.",
      ),
      tip("Invite links expire in 14 days (Settings → Onboarding). Resend issues a new token. Revoke kills the current one."),
      warn("No demo tenants. A stall that has not completed onboarding is invited, not a fake POS house."),
      related("onboarding-wizard", "single-vs-multi", "invites-roles", "platform-tenants"),
    ],
  }),
  topic({
    id: "create-org",
    chapterId: "saas",
    title: "Create org, location, packages",
    summary: "Manual provision from the control plane when you are not on a prospect path.",
    visibility: "platform",
    roles: ["platform_admin", "owner_manager"],
    keywords: ["organization", "location", "packages", "licensing", "console"],
    blocks: [
      why(
        "Internal sites and already-signed paper deals still need an org, a location, and a package set before POS has anything to open.",
      ),
      steps(
        "Sign in and open the platform console.",
        "Create organization (display name + venue type).",
        "Create a location under that org. Pick restaurant, food hall, truck pod, etc.",
        "Enable packages per location: POS core, ODS, online, labor, settlement, marketing, and so on.",
        "Invite owners/managers. They complete their own passwords.",
        "Open POS for that location. Header package preview can simulate a smaller license for training.",
      ),
      p(
        "Packages are the commercial lens. Role (PIN) is the access lens. Both must allow a tool for it to show in the menu.",
      ),
      related("onboarding-wizard", "invites-roles", "empty-start", "platform-admin"),
    ],
  }),
  topic({
    id: "single-vs-multi",
    chapterId: "saas",
    title: "Single operator, host + tenants, shared venue",
    summary: "One brand, a host with tenants, or peers sharing a building with no landlord-brand POS.",
    roles: ["platform_admin", "owner_manager", "host_operator", "vendor_operator"],
    keywords: [
      "multi-operator",
      "host",
      "vendor",
      "food hall",
      "single operator",
      "peer venue",
      "shared venue",
      "shared building",
    ],
    blocks: [
      why(
        "This choice drives who is a merchant, who owns the menu, and how the guest pays. Getting it wrong means operators cannot be paid correctly — or invents a host company that does not exist.",
      ),
      ul(
        "Single operator — one entity, one merchant, one menu.",
        "Host + tenants — a host subscriber plus guest operators. The host may sell, issue gift, and take a cut. Host owner/manager password login has full access to every tenant’s ops. Each entity is its own Quantum Payments merchant.",
        "Shared venue (peers) — a named building only. Two or more independent operators (bar operator, food operator). No host merchant, no host menu, no host gift product, no host role. Venue admin is not a landlord brand. Venue admin holds floor, devices, guest branding, and who may see whom.",
      ),
      steps(
        "In Get-a-price or onboarding, pick the model that matches the building.",
        "Shared venue: name the building (guest-facing). Invite each operator POC. They complete their own Quantum Payments application and menu.",
        "Tag every sellable line to an operator. On a shared venue, untagged lines fail closed — the building is not a merchant.",
        "Guest pays once. Receipt groups by vendor. Finix splits by line owner. Live cards wait until each selling entity is approved (sandbox in training).",
      ),
      warn(
        "Do not create a third “landlord POS” so two peers can share a floor. Shared venue is the partnership model. Quotes are Shared venue $299 + $49 per entity — not a host operator line.",
      ),
      related("host-capture", "multi-operator-orders", "settlement", "chargebacks", "type-food-hall"),
    ],
  }),
  topic({
    id: "invites-roles",
    chapterId: "saas",
    title: "Invites, roles, permissions",
    summary: "Account roles on the org, PIN roles on the floor.",
    roles: ["platform_admin", "owner_manager"],
    keywords: ["invite", "roles", "permissions", "rbac", "pin", "staff"],
    openView: "employees",
    blocks: [
      why(
        "Account membership controls who can open the platform. PIN access level controls which POS tools appear after a station login.",
      ),
      ul(
        "Platform Admin — tenants, pipeline, support. Not a restaurant owner. There is only one platform Admin; tenant Users cannot mint another.",
        "Location admin / host owner — email and password at app.summex.app/login. Dashboard tiles for that role. Host + tenants: venue health, all entities, Devices, Publish, combined and per-entity reports. Shared venue: the same minus host-merchant chrome.",
        "Entity owner vs entity manager — both password logins for one selling entity. Owner: sales, labor %, 86, menu, invoices, schedule, payout, and that brand’s payments. Manager: the same ops plus floor from back office; no billing.",
        "Accountant — reports, hours export, gift liability. No Devices. No 86.",
        "Manager — users, devices, day-to-day; not SaaS billing.",
        "Staff / vendor PIN — limited location or stall tools on a station.",
        "PIN roles: Server, Bartender, Host (stand), Kitchen, Busser, Cashier. Floor staff can be added from Tenants → Users with name, PIN, role, and home entity. Password users never use a PIN to open the dashboard.",
      ),
      steps(
        "Tenants → open the venue → Users. Add Location admin (whole venue) or Entity admin (one selling entity): name, email, temporary password, force change on first login.",
        "They sign in at app.summex.app/login and land on that dashboard — never a PIN pad, never platform CRM. Isolated demo houses work the same.",
        "Optional: add floor staff who only have a PIN. Edit role, reset password or PIN, disable from the same list.",
        "Menus hide tools the PIN cannot use. A blocked deep link returns that person to their home screen.",
      ),
      tip(
        "FOH “Host” on the waitlist is not the same as Host Venue (multi-operator). The guide tab Host (multi-operator) is the hall/pod operator.",
      ),
      related("login", "sections", "platform-admin", "create-org", "platform-tenants"),
    ],
  }),
  topic({
    id: "network-readiness",
    chapterId: "saas",
    title: "Network readiness (warn only)",
    summary: "Onboarding probes health and a Wi‑Fi checklist. Fail or skip never blocks go-live.",
    visibility: "platform",
    roles: ["platform_admin", "owner_manager", "host_operator"],
    keywords: ["network", "wifi", "readiness", "health", "warn only", "skip", "onboarding"],
    openView: "settings",
    blocks: [
      why(
        "A house that opens on guest Wi‑Fi will look “down” on POS while phones browse fine. The check is a warning, not a gate.",
      ),
      ul(
        "Probe hits Summex health. Pass, warn (slow or partial), or fail (unreachable).",
        "Checklist: staff Wi‑Fi, no guest-only isolation for POS, tablet count, printer on the same LAN, cash vs card when the internet is down.",
        "Warn or fail shows recommendations. Continue anyway is always allowed. Skip for now records skipped.",
        "Saved on the location: status, checked-at, notes. Re-run from Location settings anytime.",
        "POS and login are never disabled by this result.",
      ),
      steps(
        "In onboarding, open Network readiness after Settlement.",
        "Run network check on a staff tablet. Tick the house checklist.",
        "If it fails, join staff SSID and retry — or Continue anyway / Skip for now.",
        "Go-live still completes. Re-run from Settings → House network before first service.",
      ),
      warn(
        "This is advisory. A red fail does not stop Complete setup. Cards still need an uplink; cash and ODS do not.",
      ),
      related("onboarding-wizard", "wifi-offline", "access-urls", "printers-kds"),
    ],
  }),
  topic({
    id: "access-urls",
    chapterId: "saas",
    title: "www, venue hosts, and QR URLs",
    summary: "{slug}.summex.app is the house. Wildcard DNS once. Path /v/{slug} in preview.",
    roles: "all",
    keywords: [
      "url",
      "host",
      "www",
      "app.summex",
      "sites",
      "qr",
      "bookmark",
      "kiosk",
      "subdomain",
      "slug",
      "wildcard",
    ],
    blocks: [
      why(
        "Each house gets a stable URL from its venue name. Staff pair tablets and guests scan QR on that host — not a new DNS record per tenant.",
      ),
      ul(
        "www / marketing (summex.app) — Get a price, Guide, Demo, Contact. No login link. The `/` path is the sales landing only — never POS or the control plane.",
        "Venue host — https://{slug}.summex.app. Assigned at onboard from the venue name (editable before publish). Reserved labels (www, app, login, …) are blocked.",
        "Path fallback — /v/{slug} on preview and localhost. Same app; no wildcard DNS required there.",
        "Staff pair QR and station bookmarks use https://app.summex.app/station (and /station/order). Table QR for guests can stay on the venue host.",
        "One operator job: add *.summex.app in Namecheap (CNAME to Vercel) and on the Vercel project. No per-tenant DNS.",
      ),
      steps(
        "Onboard the house (shared venue or host + tenants). Confirm the venue URL before publish.",
        "Owner Settings lists POS, ODS, kiosk, and table QR on that host.",
        "Print table QR from Floor. Pair a station with the code/QR from Devices.",
        "Platform Tenants → click the house opens the venue URL.",
      ),
      tip(
        "Do not create a DNS record per tenant. Wildcard once. Bookmark stations on app.summex.app. Set APP_URL=https://app.summex.app so console cookies land on that host.",
      ),
      related("network-readiness", "table-qr", "feature-kiosk", "onboarding-wizard", "wifi-offline"),
    ],
  }),
  topic({
    id: "platform-admin",
    chapterId: "platform",
    title: "Platform admin: tenants & support",
    summary: "Pipeline, tenant status, and support actions on an empty or live fleet.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["admin", "tenants", "pipeline", "support", "status", "saas"],
    blocks: [
      why(
        "Platform Admin is the only identity that can see every tenant. Treat it as production access, not a demo login.",
      ),
      steps(
        "Sign in as Admin (after the forced password change).",
        "Pipeline lists prospects by status (Quote → Signed → Onboarding → Training → Live). Open one to quote, mark contract signed, or resend the owner invite.",
        "Tenants lists organizations. Click a tenant to open venue settings (location, devices, menus per entity, payments, QR, cash, labor, users). Shared venue works with no host merchant. Back returns to Tenants.",
        "Settings is sectioned: General, Security, CRM, Onboarding, Plans, Payments & gifts, Communications (SMS allotment, overage, AI cap), Flags, Compliance, Team, Danger zone. Save per section. No JSON editors.",
        "Support actions: resend an invite, open POS as that location context, review audit-style prospect events.",
        "Never seed a named customer. Isolated Summit Hall is the generic Demo row for tablet priming.",
      ),
      callout(
        "Who to contact",
        "Merchants contact their owner/manager first, then platform support@summex.app. Card disputes go through Quantum Payments (see Chargebacks) — not a second processor.",
      ),
      related("login", "quote-contract", "troubleshooting", "audit", "platform-settings"),
    ],
  }),
  topic({
    id: "prospect-demos",
    chapterId: "saas",
    title: "Get pricing — no demo tenants",
    summary: "Sales CTA is Get pricing. Testing a house means SaaS onboarding — no fake POS tenants.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: [
      "demo",
      "tour",
      "share",
      "prospect",
      "summit hall",
      "guided",
      "auto-play",
      "voiceover",
      "narration",
      "spotlight",
    ],
    blocks: [
      why(
        "A live Summex has no fake customer restaurants. Prospects request a demo through intake. Platform Admin may use isolated Summit Hall to prime tablets — it is not a subscriber.",
      ),
      p(
        "Marketing home → Get a price opens intake — not a PIN pad and not a seeded venue. Demo explains the product; it is not a seeded house.",
      ),
      ul(
        "No PIN 0000 tenant. Isolated Summit Hall has named floor PINs; customer houses get PINs when you add staff.",
        "Platform Admin signs in with username/email and password. Summit Hall may already be listed as Demo / pairable (not a subscriber). Other customer orgs appear after onboarding.",
        "Test path: open Summit Hall, or intake → quote → contract if required → wizard → org + location → owner invite → Open POS.",
      ),
      steps(
        "From the public site, Get pricing.",
        "Complete intake. Accept the quote.",
        "Finish host onboarding so the first location is a real tenant in Training.",
        "Sign in. Open POS. Staff use unique floor PINs — never a universal code.",
      ),
      callout(
        "Role walkthroughs",
        "After a real location exists, optional in-product walkthroughs spotlight the live UI. They never seed a demo org.",
      ),
      warn("Never send Admin credentials as a prospect walkthrough. Customer tenants are created through intake."),
      related("partner-demo", "prospect-intake", "onboarding-wizard", "empty-start"),
    ],
  }),
  topic({
    id: "platform-demos-admin",
    chapterId: "platform",
    title: "Isolated demo venue (platform)",
    summary: "One is_demo peer venue (Summit Hall) for tablet priming. Excluded from CRM stats.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["demo", "reset", "pipeline", "tenants", "share", "summit hall"],
    blocks: [
      why(
        "Platform Admin manages live tenants and the prospect pipeline. Summit Hall is tagged Demo so tablets can pair without counting as a subscriber.",
      ),
      steps(
        "Sign in as Admin (password). Tenants shows Summit Hall as Demo / pairable.",
        "Open the demo → Users to add a location admin, entity admin, or PIN floor staff. They sign in at app.summex.app/login and only see that demo house. Other tenants cannot.",
        "Devices: add host, order, ODS kitchen, ODS bar. Pair Android stations. Publish when ready.",
        "Pipeline is for real intake → quote → contract → setup. Demo rows stay out of CRM stats, pipeline revenue, and subscriber counts.",
      ),
      warn(
        "Never send Admin login as a prospect walkthrough. Public skip-password demo tenants stay off. Factory reset keeps Platform Admin and reseeds Summit Hall.",
      ),
      related("platform-admin", "prospect-demos", "empty-start", "partner-demo", "go-live-ops"),
    ],
  }),
  topic({
    id: "admin-bootstrap",
    chapterId: "platform",
    title: "Admin bootstrap & forced password",
    summary: "The only seeded identity. Change the password before anything else.",
    visibility: "platform",
    roles: ["platform_admin"],
    keywords: ["bootstrap", "admin", "password", "forced"],
    blocks: [
      why(
        "A fresh Summex has no tenants. Platform Admin is the bootstrap identity — not a restaurant PIN and not a demo login.",
      ),
      steps(
        "Sign in with username Admin (or admin@summex.local) and the initial password.",
        "On first success you must set a new password (8+ characters). The initial password cannot be reused.",
        "You land on the control plane. Pipeline and Console are signed-in surfaces only.",
      ),
      warn(
        "The initial Admin password exists only for bootstrap. Change it immediately. Do not publish it on the marketing site.",
      ),
      related("platform-admin", "empty-start", "login"),
    ],
  }),
];
