import type { PosView, VenueEntityId } from "@/lib/pos/types";

export type DemoStepKind = "narrative" | "pos";

export type DemoStep = {
  id: string;
  title: string;
  body: string;
  kind: DemoStepKind;
  view?: PosView;
  target?: string;
  autoMs?: number;
  /** Store action after the step is shown. */
  action?:
    | "seat"
    | "add_food"
    | "add_drink"
    | "send"
    | "pay"
    | "bump_kitchen"
    | "bump_bar"
    | "open_tab"
    | "counter_open"
    | "settle_preview"
    | "waitlist_join"
    | "waitlist_ready"
    | "reservation_seed"
    | "offline_cash"
    | "none";
};

export type DemoScript = {
  id: string;
  title: string;
  subtitle: string;
  type: VenueEntityId | "full";
  steps: DemoStep[];
};

const AUTO = 5200;

export const TYPE_SCRIPTS: Record<VenueEntityId, DemoScript> = {
  restaurant: {
    id: "restaurant",
    title: "Full-service dining",
    subtitle: "Seat, course, pay once.",
    type: "restaurant",
    steps: [
      {
        id: "r1",
        title: "The floor",
        body: "Tables live in sections. The host stand seats; the server owns the check.",
        kind: "pos",
        view: "floor",
        target: "floor",
        autoMs: AUTO,
        action: "none",
      },
      {
        id: "r2",
        title: "Seat a table",
        body: "A four-top sits. The check is open — nothing has left the kitchen yet.",
        kind: "pos",
        view: "floor",
        target: "floor",
        autoMs: AUTO,
        action: "seat",
      },
      {
        id: "r3",
        title: "Build the order",
        body: "Food and a drink on one ticket. Kitchen and bar will still see only their lines.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "add_food",
      },
      {
        id: "r4",
        title: "Send",
        body: "Fire the line. Tickets route. The guest never sees two systems.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "r5",
        title: "Kitchen rail",
        body: "The make line sees plates, not the bar.",
        kind: "pos",
        view: "kitchen",
        target: "kitchen",
        autoMs: AUTO,
        action: "bump_kitchen",
      },
      {
        id: "r6",
        title: "Pay once",
        body: "Quantum Payments is the only guest card. One capture, one receipt.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
      {
        id: "r7",
        title: "Waitlist",
        body: "When the room is full, the kiosk shows a range — not a fake exact minute. Guests add themselves and get a sandbox text.",
        kind: "pos",
        view: "waitlist",
        target: "waitlist",
        autoMs: AUTO,
        action: "waitlist_join",
      },
      {
        id: "r8",
        title: "Table ready",
        body: "Host marks ready. The guest is texted. They can remove themselves from the same thread.",
        kind: "pos",
        view: "waitlist",
        target: "waitlist",
        autoMs: AUTO,
        action: "waitlist_ready",
      },
      {
        id: "r9",
        title: "Reservation check-in",
        body: "A booked party uses last name + code at the kiosk. Staff see Guest checked in.",
        kind: "pos",
        view: "waitlist",
        target: "waitlist",
        autoMs: AUTO,
        action: "reservation_seed",
      },
    ],
  },
  food_hall: {
    id: "food_hall",
    title: "The Laundry · host check",
    subtitle: "Steam Distillery + Diamond House BBQ, one guest.",
    type: "food_hall",
    steps: [
      {
        id: "l1",
        title: "The host brand",
        body: "The guest sits at The Laundry. They do not pay Steam or Diamond House directly.",
        kind: "pos",
        view: "floor",
        target: "floor",
        autoMs: AUTO,
        action: "none",
      },
      {
        id: "l2",
        title: "Seat under the host",
        body: "One table, one check. Operators stay tagged on the line.",
        kind: "pos",
        view: "floor",
        target: "floor",
        autoMs: AUTO,
        action: "seat",
      },
      {
        id: "l3",
        title: "Drinks from Steam",
        body: "A highball from Steam Distillery — bar station, Steam’s ledger.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "add_drink",
      },
      {
        id: "l4",
        title: "Food from Diamond House",
        body: "Brisket from Diamond House BBQ on the same check. Kitchen, not bar.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "add_food",
      },
      {
        id: "l5",
        title: "Route apart",
        body: "Send once. Bar sees Steam. Pit sees Diamond House. The guest still has one bill.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "l6",
        title: "Bar tickets",
        body: "Steam’s rail only. Bump when the glass is up.",
        kind: "pos",
        view: "bar",
        target: "bar",
        autoMs: AUTO,
        action: "bump_bar",
      },
      {
        id: "l7",
        title: "Kitchen tickets",
        body: "Diamond House only. The floor is notified on bump.",
        kind: "pos",
        view: "kitchen",
        target: "kitchen",
        autoMs: AUTO,
        action: "bump_kitchen",
      },
      {
        id: "l8",
        title: "One guest card",
        body: "Quantum Payments captures once, under The Laundry. No second terminal at the table.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
      {
        id: "l9",
        title: "Settlement split",
        body: "Close the period. Merchandise, fees, and a 5% host cut allocate Steam vs Diamond House.",
        kind: "pos",
        view: "settlement",
        target: "settlement",
        autoMs: AUTO,
        action: "settle_preview",
      },
    ],
  },
  bar_lounge: {
    id: "bar_lounge",
    title: "Bar & lounge",
    subtitle: "Tabs, bump, pay.",
    type: "bar_lounge",
    steps: [
      {
        id: "b1",
        title: "The well",
        body: "Service starts at the bar. Tables in the lounge are optional.",
        kind: "pos",
        view: "bar",
        target: "bar",
        autoMs: AUTO,
        action: "none",
      },
      {
        id: "b2",
        title: "Open a tab",
        body: "A named tab, not a dining-room four-top.",
        kind: "pos",
        view: "bar",
        target: "bar",
        autoMs: AUTO,
        action: "open_tab",
      },
      {
        id: "b3",
        title: "Build the round",
        body: "Cocktails on the tab. Small plates still route to the kitchen.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "add_drink",
      },
      {
        id: "b4",
        title: "Send & bump",
        body: "The cocktail KDS is the source of truth for the well.",
        kind: "pos",
        view: "bar",
        target: "bar",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "b5",
        title: "Close on Quantum Payments",
        body: "One card. The house brand is on the receipt.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
    ],
  },
  qsr: {
    id: "qsr",
    title: "Quick service",
    subtitle: "Counter, send, pay, done.",
    type: "qsr",
    steps: [
      {
        id: "q1",
        title: "The window",
        body: "No table map. The check is the queue.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "none",
      },
      {
        id: "q2",
        title: "Open a check",
        body: "Counter service. Name optional; speed is the product.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "counter_open",
      },
      {
        id: "q3",
        title: "Add the meal",
        body: "Mains and a drink. Make line vs fountain still split.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "add_food",
      },
      {
        id: "q4",
        title: "Send the line",
        body: "Kitchen sees the plate. The guest stays at the counter.",
        kind: "pos",
        view: "kitchen",
        target: "kitchen",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "q5",
        title: "Pay and complete",
        body: "Quantum Payments at the register. Check closed.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
    ],
  },
  cafe: {
    id: "cafe",
    title: "Café",
    subtitle: "Espresso and pastry, one check.",
    type: "cafe",
    steps: [
      {
        id: "c1",
        title: "The counter",
        body: "Barista and baker share a guest. They do not share a station.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "counter_open",
      },
      {
        id: "c2",
        title: "Drink + pastry",
        body: "A latte and a croissant. Bar vs pastry still route apart.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "add_drink",
      },
      {
        id: "c3",
        title: "Send",
        body: "Espresso bar and pastry kitchen each get their ticket.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "c4",
        title: "Pay once",
        body: "One Quantum Payments capture. The guest is not asked twice.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
    ],
  },
  truck_pod: {
    id: "truck_pod",
    title: "Truck pod",
    subtitle: "Lot host, window orders.",
    type: "truck_pod",
    steps: [
      {
        id: "t1",
        title: "The lot",
        body: "Pads and power belong to the host. Each truck still runs a window.",
        kind: "pos",
        view: "truck_pod",
        target: "truck_pod",
        autoMs: AUTO,
        action: "none",
      },
      {
        id: "t2",
        title: "A window check",
        body: "The guest orders at the truck — not from a dining-room map.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "counter_open",
      },
      {
        id: "t3",
        title: "Kitchen in the truck",
        body: "Tickets stay on the truck KDS. The lot host is not the cook.",
        kind: "pos",
        view: "kitchen",
        target: "kitchen",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "t4",
        title: "Pay the house brand",
        body: "When the host captures, Quantum Payments is still the only card.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
    ],
  },
  ghost_kitchen: {
    id: "ghost_kitchen",
    title: "Ghost kitchen",
    subtitle: "No dining room. Dispatch is the floor.",
    type: "ghost_kitchen",
    steps: [
      {
        id: "g1",
        title: "No host stand",
        body: "This house has no tables. Expo and courier handoff replace the dining room.",
        kind: "pos",
        view: "kitchen",
        target: "kitchen",
        autoMs: AUTO,
        action: "none",
      },
      {
        id: "g2",
        title: "A dispatch check",
        body: "Takeout is the default order type.",
        kind: "pos",
        view: "takeout",
        target: "takeout",
        autoMs: AUTO,
        action: "counter_open",
      },
      {
        id: "g3",
        title: "Make line",
        body: "Send. The rail is the only floor the cook needs.",
        kind: "pos",
        view: "kitchen",
        target: "kitchen",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "g4",
        title: "Close the ticket",
        body: "Quantum Payments on the brand. No second processor for delivery.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
    ],
  },
  catering: {
    id: "catering",
    title: "Catering",
    subtitle: "Event check, pack, close.",
    type: "catering",
    steps: [
      {
        id: "k1",
        title: "The job",
        body: "Catering is not a dining room. The check is the event.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "counter_open",
      },
      {
        id: "k2",
        title: "Build the menu",
        body: "Plates and sides for the drop. Kitchen sees the pack list.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "add_food",
      },
      {
        id: "k3",
        title: "Send the pack",
        body: "Tickets to the commissary line.",
        kind: "pos",
        view: "kitchen",
        target: "kitchen",
        autoMs: AUTO,
        action: "send",
      },
      {
        id: "k4",
        title: "Close the event",
        body: "One Quantum Payments capture for the job.",
        kind: "pos",
        view: "order",
        target: "order",
        autoMs: AUTO,
        action: "pay",
      },
    ],
  },
};

export const FULL_TOUR_SCRIPT: DemoScript = {
  id: "full",
  title: "Full product tour",
  subtitle: "Major surfaces, in order, without mixing live tenants.",
  type: "full",
  steps: [
    {
      id: "f1",
      title: "Tenants vs demos",
      body: "Live houses live under Tenants. These rooms are tagged demo — excluded from billing, statistics, and empty-start. A prospect never sees your real operators.",
      kind: "narrative",
      autoMs: 7000,
      action: "none",
    },
    {
      id: "f2",
      title: "Location types & packages",
      body: "Restaurant, hall, bar, café, QSR, pod, ghost, catering. POS core and KDS ship on the starter path; host settlement and labor are packages you turn on per site.",
      kind: "narrative",
      autoMs: 7000,
      action: "none",
    },
    {
      id: "f3",
      title: "Floor, sections, tables",
      body: "Color-coded sections. The host seats; servers keep the check. This is The Laundry dining room — a host floor, not a single-brand café.",
      kind: "pos",
      view: "floor",
      target: "floor",
      autoMs: AUTO,
      action: "seat",
    },
    {
      id: "f4",
      title: "Menu & modifiers",
      body: "Steam Distillery and Diamond House BBQ as categories. Lines keep their operator when they hit the check.",
      kind: "pos",
      view: "menu",
      target: "menu",
      autoMs: AUTO,
      action: "none",
    },
    {
      id: "f5",
      title: "Ordering & routing",
      body: "Drinks to the bar, plates to the pit. One send. Two rails.",
      kind: "pos",
      view: "order",
      target: "order",
      autoMs: AUTO,
      action: "add_drink",
    },
    {
      id: "f6",
      title: "Host check + Quantum Payments",
      body: "Food and drink on one guest bill. Capture once under The Laundry. There is no Stripe or Square picker on this floor.",
      kind: "pos",
      view: "order",
      target: "order",
      autoMs: AUTO,
      action: "add_food",
    },
    {
      id: "f7",
      title: "Settlement & ledger",
      body: "Period close allocates merchandise, card fees, and the host cut. The ledger is the product you can run today — live ACH is not claimed here.",
      kind: "pos",
      view: "settlement",
      target: "settlement",
      autoMs: 7000,
      action: "send",
    },
    {
      id: "f8",
      title: "Cash discount & round-up",
      body: "Keep a round menu price. A 5% cash discount with $0.25 round-up is a house setting — not a second processor.",
      kind: "pos",
      view: "cash",
      target: "cash",
      autoMs: AUTO,
      action: "none",
    },
    {
      id: "f9",
      title: "Chargeback fee",
      body: "When a dispute is filed — only then — a $35 fee splits by merchandise share on that check. Sandbox only on this tour.",
      kind: "pos",
      view: "ledger",
      target: "ledger",
      autoMs: AUTO,
      action: "pay",
    },
    {
      id: "f10",
      title: "Operators Guide",
      body: "Searchable, role-aware, in the product. Send a prospect the Guide for the floor; send them a demo link for the tour.",
      kind: "narrative",
      autoMs: 6000,
      action: "none",
    },
    {
      id: "f11",
      title: "Intake & onboarding",
      body: "Get pricing → snapshot quote → accept → contract marked signed → guided onboarding. Demos never become live tenants.",
      kind: "narrative",
      autoMs: 7000,
      action: "none",
    },
    {
      id: "f12",
      title: "Kiosk, waitlist, check-in",
      body: "The guest kiosk can take an order, join a waitlist, or check in a reservation with a code. Wait times are ranges. Texts are sandbox unless Twilio is set.",
      kind: "pos",
      view: "waitlist",
      target: "waitlist",
      autoMs: 7000,
      action: "waitlist_join",
    },
  ],
};

export function scriptFor(type: VenueEntityId | "full"): DemoScript {
  if (type === "full") return FULL_TOUR_SCRIPT;
  return TYPE_SCRIPTS[type];
}
