/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as TableLabelRouteImport } from './routes/table.$label'
import { Route as VenueTypeRouteImport } from './routes/venue.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TableLabelRoute = TableLabelRouteImport.update({
  id: '/table/$label',
  path: '/table/$label',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueTypeRoute = VenueTypeRouteImport.update({
  id: '/venue/$type',
  path: '/venue/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/kiosk': typeof KioskRoute
  '/online': typeof OnlineRoute
  '/platform': typeof PlatformRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/site/$slug': typeof SiteSlugRoute
  '/table/$label': typeof TableLabelRoute
  '/venue/$type': typeof VenueTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/kiosk': typeof KioskRoute
  '/online': typeof OnlineRoute
  '/platform': typeof PlatformRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/site/$slug': typeof SiteSlugRoute
  '/table/$label': typeof TableLabelRoute
  '/venue/$type': typeof VenueTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/kiosk': typeof KioskRoute
  '/online': typeof OnlineRoute
  '/platform': typeof PlatformRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/site/$slug': typeof SiteSlugRoute
  '/table/$label': typeof TableLabelRoute
  '/venue/$type': typeof VenueTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/kiosk'
    | '/online'
    | '/platform'
    | '/order/$orderId'
    | '/site/$slug'
    | '/table/$label'
    | '/venue/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/kiosk'
    | '/online'
    | '/platform'
    | '/order/$orderId'
    | '/site/$slug'
    | '/table/$label'
    | '/venue/$type'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/kiosk'
    | '/online'
    | '/platform'
    | '/order/$orderId'
    | '/site/$slug'
    | '/table/$label'
    | '/venue/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  KioskRoute: typeof KioskRoute
  OnlineRoute: typeof OnlineRoute
  PlatformRoute: typeof PlatformRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  SiteSlugRoute: typeof SiteSlugRoute
  TableLabelRoute: typeof TableLabelRoute
  VenueTypeRoute: typeof VenueTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$label': {
      id: '/table/$label'
      path: '/table/$label'
      fullPath: '/table/$label'
      preLoaderRoute: typeof TableLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$type': {
      id: '/venue/$type'
      path: '/venue/$type'
      fullPath: '/venue/$type'
      preLoaderRoute: typeof VenueTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  KioskRoute: KioskRoute,
  OnlineRoute: OnlineRoute,
  PlatformRoute: PlatformRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  SiteSlugRoute: SiteSlugRoute,
  TableLabelRoute: TableLabelRoute,
  VenueTypeRoute: VenueTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
