/**
 * DEV_DEMO / Admin “Load test venue” only.
 * Production (DEV_DEMO=0) never loads this dataset.
 */
import type {
  Employee,
  FloorSection,
  MenuCategory,
  MenuItem,
  RestaurantSettings,
  SettlementConfig,
  Table,
  Vendor,
} from "./types";
import { DEFAULT_SECTION_POLICY } from "./section-control";

export const LAUNDRY_ORG_NAME = "The Laundry Group";
/** Matches demo SaaS location id (`loc_hall`) so POS + control plane stay aligned. */
export const LAUNDRY_LOCATION_ID = "loc_hall";
export const LAUNDRY_LOCATION_NAME = "The Laundry";
export const LAUNDRY_STEAM_ID = "vnd_steam";
export const LAUNDRY_DIAMOND_ID = "vnd_diamond";
export const LAUNDRY_TEST_LABEL = "TEST venue";

export const LAUNDRY_SETTINGS: RestaurantSettings = {
  name: LAUNDRY_LOCATION_NAME,
  address: "TEST · The Laundry Group",
  phone: "(555) 010-0000",
  taxRate: 0.0875,
  autoGratPercent: 0.2,
  autoGratPartySize: 6,
  happyHourEnabled: false,
  happyHourStart: 15,
  happyHourEnd: 18,
  happyHourDays: [1, 2, 3, 4, 5],
  currency: "USD",
  receiptFooter: "The Laundry · TEST venue · Guest cards via Quantum Payments",
  managerPin: "0000",
  serviceChargeLabel: "Auto-gratuity",
  multiTenantHallMode: true,
  hostMultiOperator: true,
  onlineOrderingEnabled: true,
  qrOrderingEnabled: true,
  sectionPolicy: { ...DEFAULT_SECTION_POLICY },
  cashDiscountEnabled: true,
  cashDiscountPercent: 5,
  cashRoundIncrement: 0.25,
  cashRoundMode: "up",
  waitlistEnabled: true,
  kioskMode: "combined",
};

export const LAUNDRY_VENDORS: Vendor[] = [
  {
    id: LAUNDRY_STEAM_ID,
    name: "Steam Distillery",
    shortName: "Steam",
    locationId: LAUNDRY_LOCATION_ID,
    color: "#2C4A6E",
    cuisine: "Cocktails & beer",
    active: true,
    bankLast4: "0000",
    bankLabel: "TEST · Steam Distillery payout stub",
    stationLabel: "Bar",
    stationType: "bar",
  },
  {
    id: LAUNDRY_DIAMOND_ID,
    name: "Diamond House BBQ",
    shortName: "Diamond",
    locationId: LAUNDRY_LOCATION_ID,
    color: "#9A6700",
    cuisine: "Barbecue",
    active: true,
    bankLast4: "0000",
    bankLabel: "TEST · Diamond House BBQ payout stub",
    stationLabel: "Pit",
    stationType: "kitchen",
  },
];

export const LAUNDRY_SECTIONS: FloorSection[] = [
  { id: "sec_laundry_dining", name: "Dining", color: "sec-1", sort: 0 },
  { id: "sec_laundry_bar", name: "Bar", color: "sec-3", sort: 1 },
];

export const LAUNDRY_TABLES: Table[] = [
  ...[1, 2, 3, 4, 5, 6].map((n, i) => ({
    id: `t_laundry_${n}`,
    label: String(n),
    section: "Dining",
    seats: 4,
    x: 12 + (i % 3) * 22,
    y: 14 + Math.floor(i / 3) * 28,
    w: 14,
    h: 14,
    shape: "round" as const,
    status: "available" as const,
    locationId: LAUNDRY_LOCATION_ID,
  })),
  ...[1, 2, 3, 4].map((n, i) => ({
    id: `t_laundry_b${n}`,
    label: `B${n}`,
    section: "Bar",
    seats: 1,
    x: 10 + i * 18,
    y: 78,
    w: 10,
    h: 10,
    shape: "bar" as const,
    status: "available" as const,
    locationId: LAUNDRY_LOCATION_ID,
  })),
];

export const LAUNDRY_CATEGORIES: MenuCategory[] = [
  { id: "cat_laundry_drinks", name: "Steam Distillery", sort: 0, color: "#2C4A6E", station: "bar" },
  { id: "cat_laundry_mains", name: "Diamond House BBQ", sort: 1, color: "#9A6700", station: "kitchen" },
  { id: "cat_laundry_sides", name: "Sides", sort: 2, color: "#5C5C5C", station: "kitchen" },
];

export const LAUNDRY_MENU: MenuItem[] = [
  {
    id: "itm_steam_highball",
    name: "House Highball",
    categoryId: "cat_laundry_drinks",
    priceCents: 1200,
    course: "drink",
    station: "bar",
    description: "House spirit, soda, citrus. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_steam_of",
    name: "Steam Old Fashioned",
    categoryId: "cat_laundry_drinks",
    priceCents: 1500,
    course: "drink",
    station: "bar",
    description: "Whiskey, bitters, orange. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_steam_lager",
    name: "Draft lager",
    categoryId: "cat_laundry_drinks",
    priceCents: 700,
    course: "drink",
    station: "bar",
    description: "Pint. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_steam_soda",
    name: "Soda",
    categoryId: "cat_laundry_drinks",
    priceCents: 400,
    course: "drink",
    station: "bar",
    description: "Fountain. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_diamond_brisket",
    name: "Brisket plate",
    categoryId: "cat_laundry_mains",
    priceCents: 1800,
    course: "entree",
    station: "kitchen",
    description: "Sliced brisket, pickles. Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_ribs",
    name: "Ribs, half rack",
    categoryId: "cat_laundry_mains",
    priceCents: 2200,
    course: "entree",
    station: "kitchen",
    description: "Dry-rubbed. Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_sandwich",
    name: "BBQ sandwich",
    categoryId: "cat_laundry_mains",
    priceCents: 1400,
    course: "entree",
    station: "kitchen",
    description: "Chopped pit meat on bun. Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_beans",
    name: "Pit beans",
    categoryId: "cat_laundry_sides",
    priceCents: 600,
    course: "side",
    station: "kitchen",
    description: "Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_corn",
    name: "Cornbread",
    categoryId: "cat_laundry_sides",
    priceCents: 500,
    course: "side",
    station: "kitchen",
    description: "Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
];

export const LAUNDRY_EMPLOYEES: Employee[] = [
  {
    id: "emp_laundry_owner",
    name: "Laundry Host",
    pin: "9999",
    role: "owner",
    color: "#2C4A6E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Host owner",
  },
  {
    id: "emp_laundry_mgr",
    name: "Floor Manager",
    pin: "0000",
    role: "manager",
    color: "#5C5C5C",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining", "sec_laundry_bar"],
    title: "Manager",
  },
  {
    id: "emp_laundry_srv",
    name: "Server",
    pin: "1111",
    role: "server",
    color: "#1F7A4C",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining"],
    title: "Server",
  },
  {
    id: "emp_laundry_bar",
    name: "Steam bartender",
    pin: "3333",
    role: "bartender",
    color: "#2C4A6E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_bar"],
    title: "Bar · Steam Distillery",
    operatorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "emp_laundry_kit",
    name: "Diamond pit",
    pin: "5555",
    role: "kitchen",
    color: "#9A6700",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Kitchen · Diamond House BBQ",
    homeView: "kitchen",
    operatorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "emp_laundry_host",
    name: "Host stand",
    pin: "2222",
    role: "host",
    color: "#5B8DEF",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining"],
    title: "Host stand",
  },
  {
    id: "emp_laundry_cash",
    name: "Counter",
    pin: "4444",
    role: "cashier",
    color: "#0F766E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Cashier",
  },
  {
    id: "emp_laundry_steam_op",
    name: "Steam operator",
    pin: "6666",
    role: "vendor_operator",
    color: "#2C4A6E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_bar"],
    title: "Steam Distillery",
    operatorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "emp_laundry_diamond_op",
    name: "Diamond operator",
    pin: "7777",
    role: "vendor_operator",
    color: "#9A6700",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Diamond House BBQ",
    operatorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "emp_laundry_acct",
    name: "Back office",
    pin: "8888",
    role: "accountant",
    color: "#57534E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Accountant",
  },
];

export function laundrySettlement(): SettlementConfig {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  const day = d.getDay();
  d.setDate(d.getDate() - day);
  return {
    locationId: LAUNDRY_LOCATION_ID,
    locationName: LAUNDRY_LOCATION_NAME,
    periodType: "weekly",
    customPeriodDays: 7,
    cardFeePercent: 2.9,
    hostCutEnabled: true,
    hostCutType: "percent_of_gross",
    hostCutPercent: 5,
    hostCutFixedCents: 0,
    hostName: LAUNDRY_LOCATION_NAME,
    taxRemittedBy: "host",
    tipPoolWithVendors: false,
    currentPeriodStart: d.getTime(),
  };
}

export function laundryPosSlice() {
  return {
    tenantLocationId: LAUNDRY_LOCATION_ID,
    settings: { ...LAUNDRY_SETTINGS },
    employees: LAUNDRY_EMPLOYEES.map((e) => ({ ...e })),
    currentEmployeeId: null as string | null,
    categories: LAUNDRY_CATEGORIES.map((c) => ({ ...c })),
    menuItems: LAUNDRY_MENU.map((m) => ({ ...m })),
    modifierGroups: [],
    tables: LAUNDRY_TABLES.map((t) => ({ ...t })),
    orders: [],
    tickets: [],
    waitlist: [],
    reservations: [],
    vendors: LAUNDRY_VENDORS.map((v) => ({ ...v })),
    settlementConfig: laundrySettlement(),
    settlementPeriods: [],
    chargebacks: [],
    ledgerEntries: [],
    extraTableGrants: [],
    sectionOverrides: {} as Record<string, string[]>,
    floorSections: LAUNDRY_SECTIONS.map((s) => ({ ...s })),
    activeEntityId: "food_hall" as const,
    view: "floor" as const,
    activeOrderId: null as string | null,
    activeTableId: null as string | null,
    selectedCategoryId: LAUNDRY_CATEGORIES[0]!.id,
    selectedLineId: null as string | null,
  };
}
