/**
 * DEV_DEMO / Admin “Load test venue” only.
 * Production (DEV_DEMO=0) never loads this dataset.
 */
import type {
  Employee,
  FloorSection,
  MenuCategory,
  MenuItem,
  RestaurantSettings,
  SettlementConfig,
  Table,
  Vendor,
} from "./types";
import { DEFAULT_SECTION_POLICY } from "./section-control";
import { HOST_SCOPE } from "@/lib/access/entity-grants";
import type { LocationDevice } from "./location-devices";
import { withHashedPin } from "./pin";
import {
  PARTNER_DEMO_LOCATION_ID,
  PARTNER_DEMO_LOCATION_NAME,
} from "@/lib/demo/partner-demo";

export const LAUNDRY_ORG_NAME = "The Laundry Group";
/** Matches demo SaaS location id (`loc_hall`) so POS + control plane stay aligned. */
export const LAUNDRY_LOCATION_ID = "loc_hall";
export const LAUNDRY_LOCATION_NAME = "The Laundry";
export const LAUNDRY_STEAM_ID = "vnd_steam";
export const LAUNDRY_DIAMOND_ID = "vnd_diamond";
export const LAUNDRY_TEST_LABEL = "TEST venue";

export const LAUNDRY_SETTINGS: RestaurantSettings = {
  name: LAUNDRY_LOCATION_NAME,
  address: "TEST · The Laundry Group",
  phone: "(555) 010-0000",
  taxRate: 0.0875,
  autoGratPercent: 0.2,
  autoGratPartySize: 6,
  happyHourEnabled: false,
  happyHourStart: 15,
  happyHourEnd: 18,
  happyHourDays: [1, 2, 3, 4, 5],
  currency: "USD",
  receiptFooter: "The Laundry · TEST venue · Guest cards via Quantum Payments",
  managerPin: "1001",
  serviceChargeLabel: "Auto-gratuity",
  multiTenantHallMode: true,
  hostMultiOperator: true,
  peerVenue: true,
  operatingModel: "peer_venue",
  onlineOrderingEnabled: true,
  qrOrderingEnabled: true,
  sectionPolicy: { ...DEFAULT_SECTION_POLICY },
  cashDiscountEnabled: true,
  cashDiscountPercent: 5,
  cashRoundIncrement: 0.25,
  cashRoundMode: "up",
  waitlistEnabled: true,
  kioskMode: "combined",
  qrMode: "hybrid",
  expoEnabled: true,
  giftTermAllowed: false,
  giftTermDays: 730,
  giftOperatorBreakageSplitBps: 5000,
  giftHouseIssuerEnabled: false,
  giftHostessDefaultIssuerId: LAUNDRY_DIAMOND_ID,
  floorStatusConfig: {
    enabled: {
      empty: true,
      sat_no_order: true,
      ordered_drinks: true,
      ordered_food: true,
      food_delivered: true,
      food_completed: true,
      closed_not_cleaned: true,
    },
    colors: {
      empty: "#ffffff",
      sat_no_order: "#dbeafe",
      ordered_drinks: "#fef3c7",
      ordered_food: "#d1fae5",
      food_delivered: "#ccfbf1",
      food_completed: "#ede9fe",
      closed_not_cleaned: "#fee2e2",
    },
    flashMinutes: {
      empty: null,
      sat_no_order: 0.15,
      ordered_drinks: 0.4,
      ordered_food: 0.5,
      food_delivered: 0.5,
      food_completed: 0.4,
      closed_not_cleaned: 0.12,
    },
    changeRoles: ["owner", "manager", "host", "server", "busser"],
    seatingRole: "host_or_manager",
  },
};

export const LAUNDRY_VENDORS: Vendor[] = [
  {
    id: LAUNDRY_STEAM_ID,
    name: "Steam Distillery",
    shortName: "Steam",
    locationId: LAUNDRY_LOCATION_ID,
    color: "#2C4A6E",
    cuisine: "Cocktails & beer",
    active: true,
    bankLast4: "0000",
    bankLabel: "TEST · Steam Distillery payout stub",
    stationLabel: "Bar",
    stationType: "bar",
  },
  {
    id: LAUNDRY_DIAMOND_ID,
    name: "Diamond House BBQ",
    shortName: "Diamond",
    locationId: LAUNDRY_LOCATION_ID,
    color: "#9A6700",
    cuisine: "Barbecue",
    active: true,
    bankLast4: "0000",
    bankLabel: "TEST · Diamond House BBQ payout stub",
    stationLabel: "Pit",
    stationType: "kitchen",
  },
];

export const LAUNDRY_SECTIONS: FloorSection[] = [
  { id: "sec_laundry_dining", name: "Dining", color: "sec-1", sort: 0 },
  { id: "sec_laundry_bar", name: "Bar", color: "sec-3", sort: 1 },
];

export const LAUNDRY_TABLES: Table[] = [
  ...[1, 2, 3, 4, 5, 6].map((n, i) => ({
    id: `t_laundry_${n}`,
    label: String(n),
    section: "Dining",
    seats: 4,
    x: 12 + (i % 3) * 22,
    y: 14 + Math.floor(i / 3) * 28,
    w: 14,
    h: 14,
    shape: "round" as const,
    kind: "table" as const,
    status: "empty" as const,
    qrToken: `tlaundry${n}`,
    locationId: LAUNDRY_LOCATION_ID,
  })),
  ...[1, 2, 3, 4].map((n, i) => ({
    id: `t_laundry_b${n}`,
    label: `B${n}`,
    section: "Bar",
    seats: 1,
    x: 10 + i * 18,
    y: 78,
    w: 10,
    h: 10,
    shape: "bar" as const,
    kind: "barstool" as const,
    status: "empty" as const,
    qrToken: `tlaundryb${n}`,
    locationId: LAUNDRY_LOCATION_ID,
  })),
];

export const LAUNDRY_CATEGORIES: MenuCategory[] = [
  { id: "cat_laundry_drinks", name: "Steam Distillery", sort: 0, color: "#2C4A6E", station: "bar" },
  { id: "cat_laundry_mains", name: "Diamond House BBQ", sort: 1, color: "#9A6700", station: "kitchen" },
  { id: "cat_laundry_sides", name: "Sides", sort: 2, color: "#5C5C5C", station: "kitchen" },
];

export const LAUNDRY_MENU: MenuItem[] = [
  {
    id: "itm_steam_highball",
    name: "House Highball",
    categoryId: "cat_laundry_drinks",
    priceCents: 1200,
    course: "drink",
    station: "bar",
    description: "House spirit, soda, citrus. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_steam_of",
    name: "Steam Old Fashioned",
    categoryId: "cat_laundry_drinks",
    priceCents: 1500,
    course: "drink",
    station: "bar",
    description: "Whiskey, bitters, orange. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_steam_lager",
    name: "Draft lager",
    categoryId: "cat_laundry_drinks",
    priceCents: 700,
    course: "drink",
    station: "bar",
    description: "Pint. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_steam_soda",
    name: "Soda",
    categoryId: "cat_laundry_drinks",
    priceCents: 400,
    course: "drink",
    station: "bar",
    description: "Fountain. Steam Distillery.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "itm_diamond_brisket",
    name: "Brisket plate",
    categoryId: "cat_laundry_mains",
    priceCents: 1800,
    course: "entree",
    station: "kitchen",
    description: "Sliced brisket, pickles. Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_ribs",
    name: "Ribs, half rack",
    categoryId: "cat_laundry_mains",
    priceCents: 2200,
    course: "entree",
    station: "kitchen",
    description: "Dry-rubbed. Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_sandwich",
    name: "BBQ sandwich",
    categoryId: "cat_laundry_mains",
    priceCents: 1400,
    course: "entree",
    station: "kitchen",
    description: "Chopped pit meat on bun. Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_beans",
    name: "Pit beans",
    categoryId: "cat_laundry_sides",
    priceCents: 600,
    course: "side",
    station: "kitchen",
    description: "Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "itm_diamond_corn",
    name: "Cornbread",
    categoryId: "cat_laundry_sides",
    priceCents: 500,
    course: "side",
    station: "kitchen",
    description: "Diamond House BBQ.",
    modifierGroupIds: [],
    available: true,
    vendorId: LAUNDRY_DIAMOND_ID,
  },
];

/** Floor PIN roster. Hashed at slice time with the location id. Time clock is separate. */
export const LAUNDRY_EMPLOYEES: Employee[] = [
  {
    id: "emp_laundry_owner",
    name: "Owner",
    pin: "1000",
    role: "owner",
    color: "#2C4A6E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Owner",
  },
  {
    id: "emp_laundry_mgr",
    name: "Manager",
    pin: "1001",
    role: "manager",
    color: "#5C5C5C",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining", "sec_laundry_bar"],
    title: "Manager",
  },
  {
    id: "emp_laundry_host",
    name: "Host stand",
    pin: "1100",
    role: "host",
    color: "#5B8DEF",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining"],
    title: "Host stand",
  },
  {
    id: "emp_laundry_srv",
    name: "Server 1",
    pin: "2001",
    role: "server",
    color: "#1F7A4C",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining"],
    title: "Server",
  },
  {
    id: "emp_laundry_srv2",
    name: "Server 2",
    pin: "2002",
    role: "server",
    color: "#0F766E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining"],
    title: "Server · dining",
  },
  {
    id: "emp_laundry_expo",
    name: "Expo",
    pin: "2100",
    role: "kitchen",
    color: "#7C3AED",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Expo",
    homeView: "kitchen",
  },
  {
    id: "emp_laundry_bus",
    name: "Busser",
    pin: "2200",
    role: "busser",
    color: "#57534E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_dining"],
    title: "Busser",
  },
  {
    id: "emp_laundry_cash",
    name: "Cashier",
    pin: "2300",
    role: "cashier",
    color: "#0F766E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Cashier",
  },
  {
    id: "emp_laundry_steam_mgr",
    name: "Bar manager",
    pin: "3000",
    role: "vendor_operator",
    color: "#2C4A6E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_bar"],
    title: "Bar manager · Steam Distillery",
    homeView: "bar",
    operatorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "emp_laundry_bar",
    name: "Bartender",
    pin: "3001",
    role: "bartender",
    color: "#2C4A6E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_laundry_bar"],
    title: "Bartender · Steam Distillery",
    operatorId: LAUNDRY_STEAM_ID,
  },
  {
    id: "emp_laundry_diamond_mgr",
    name: "Kitchen manager",
    pin: "4000",
    role: "vendor_operator",
    color: "#9A6700",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Kitchen manager · Diamond House BBQ",
    homeView: "kitchen",
    operatorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "emp_laundry_kit",
    name: "Cook",
    pin: "4001",
    role: "kitchen",
    color: "#9A6700",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Cook · Diamond House BBQ",
    homeView: "kitchen",
    operatorId: LAUNDRY_DIAMOND_ID,
  },
  {
    id: "emp_laundry_acct",
    name: "Accountant",
    pin: "",
    role: "accountant",
    color: "#57534E",
    clockedIn: true,
    clockInAt: Date.now(),
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
    title: "Accountant",
  },
];

export function laundrySettlement(locationId = LAUNDRY_LOCATION_ID): SettlementConfig {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  const day = d.getDay();
  d.setDate(d.getDate() - day);
  return {
    locationId,
    locationName: LAUNDRY_LOCATION_NAME,
    periodType: "weekly",
    customPeriodDays: 7,
    cardFeePercent: 2.9,
    hostCutEnabled: true,
    hostCutType: "percent_of_gross",
    hostCutPercent: 5,
    hostCutFixedCents: 0,
    hostName: LAUNDRY_LOCATION_NAME,
    taxRemittedBy: "host",
    tipPoolWithVendors: false,
    currentPeriodStart: d.getTime(),
  };
}

export function laundryLocationDevices(locationId = LAUNDRY_LOCATION_ID): LocationDevice[] {
  const now = Date.now();
  return [
    {
      id: "dev_tab_a",
      locationId,
      label: "Tablet A",
      type: "kds",
      status: "online",
      lastSeenAt: now - 12_000,
      serial: "TAB-A-STEAM",
      claimCode: "STMKDS",
      assignment: { operatorId: LAUNDRY_STEAM_ID, function: "bar_kds" },
    },
    {
      id: "dev_tab_b",
      locationId,
      label: "Tablet B",
      type: "tablet_pos",
      status: "online",
      lastSeenAt: now - 8_000,
      serial: "TAB-B-DIA",
      claimCode: "DIAPOS",
      assignment: { operatorId: LAUNDRY_DIAMOND_ID, function: "floor_pos" },
    },
    {
      id: "dev_tab_c",
      locationId,
      label: "Tablet C",
      type: "kiosk",
      status: "online",
      lastSeenAt: now - 20_000,
      serial: "TAB-C-HOST",
      claimCode: "HOSTKO",
      assignment: { operatorId: HOST_SCOPE, function: "kiosk" },
    },
    {
      id: "dev_kds_27",
      locationId,
      label: '27" kitchen display',
      type: "kds",
      status: "online",
      lastSeenAt: now - 5_000,
      serial: "AND-KDS-27",
      claimCode: "DIAKDS",
      assignment: { operatorId: LAUNDRY_DIAMOND_ID, function: "kitchen_kds" },
    },
    {
      id: "dev_host_stand",
      locationId,
      label: "Host stand",
      type: "host_stand",
      status: "online",
      lastSeenAt: now - 30_000,
      serial: "HOST-01",
      claimCode: "HOSTST",
      assignment: { operatorId: HOST_SCOPE, function: "host_stand" },
    },
    {
      id: "dev_printer_bar",
      locationId,
      label: "Bar chit printer",
      type: "printer",
      status: "offline",
      lastSeenAt: now - 86_400_000,
      serial: "PR-BAR-01",
      claimCode: "BARPRT",
      assignment: { operatorId: LAUNDRY_STEAM_ID, function: "bar_pos" },
    },
  ];
}

export function laundryPosSliceFor(locationId: string, opts?: { partner?: boolean }) {
  const partner = Boolean(opts?.partner);
  const settings: RestaurantSettings = {
    ...LAUNDRY_SETTINGS,
    name: partner ? PARTNER_DEMO_LOCATION_NAME : LAUNDRY_SETTINGS.name,
    address: partner ? "The Laundry · partner demo" : LAUNDRY_SETTINGS.address,
    receiptFooter: partner
      ? "The Laundry · Guest cards via Quantum Payments"
      : LAUNDRY_SETTINGS.receiptFooter,
    managerPin: "1001",
  };
  return {
    tenantLocationId: locationId,
    settings,
    employees: LAUNDRY_EMPLOYEES.map((e) => {
      const copy = {
        ...e,
        entityId: "food_hall" as const,
        clockedIn: true,
        clockInAt: Date.now(),
      };
      if (!copy.pin || !/^\d{4}$/.test(copy.pin)) return copy;
      return withHashedPin(copy, copy.pin, locationId);
    }),
    currentEmployeeId: null as string | null,
    categories: LAUNDRY_CATEGORIES.map((c) => ({ ...c })),
    menuItems: LAUNDRY_MENU.map((m) => ({ ...m })),
    modifierGroups: [],
    tables: LAUNDRY_TABLES.map((t) => ({ ...t, locationId })),
    orders: [],
    tickets: [],
    waitlist: [],
    reservations: [],
    vendors: LAUNDRY_VENDORS.map((v) => ({
      ...v,
      locationId,
      bankLabel: partner ? `${v.name} payout` : v.bankLabel,
    })),
    inventory: [
      {
        id: "inv_laundry_bourbon",
        name: "Well bourbon",
        unit: "btl",
        onHand: 6,
        par: 10,
        costCents: 2800,
        linkedMenuItemIds: ["itm_steam_highball", "itm_steam_of"],
        lowStock: true,
      },
      {
        id: "inv_laundry_brisket",
        name: "Brisket (lb)",
        unit: "lb",
        onHand: 18,
        par: 24,
        costCents: 900,
        linkedMenuItemIds: ["itm_diamond_brisket", "itm_diamond_sandwich"],
        lowStock: true,
      },
    ],
    settlementConfig: laundrySettlement(locationId),
    settlementPeriods: [],
    chargebacks: [],
    ledgerEntries: [],
    extraTableGrants: [],
    sectionOverrides: {} as Record<string, string[]>,
    floorSections: LAUNDRY_SECTIONS.map((s) => ({ ...s })),
    activeEntityId: "food_hall" as const,
    view: "floor" as const,
    activeOrderId: null as string | null,
    activeTableId: null as string | null,
    selectedCategoryId: LAUNDRY_CATEGORIES[0]!.id,
    entityPermissions: [],
    locationDevices: laundryLocationDevices(locationId),
    activeDeviceId: null as string | null,
    selectedLineId: null as string | null,
  };
}

export function laundryPosSlice() {
  return laundryPosSliceFor(LAUNDRY_LOCATION_ID);
}

/** Partner-demo POS payload — menus routed bar vs kitchen, hashed floor PINs. */
export function partnerLaundryPosSlice(locationId = PARTNER_DEMO_LOCATION_ID) {
  return laundryPosSliceFor(locationId, { partner: true });
}
