import type {
  Building,
  Campaign,
  CateringEvent,
  DeliveryDriver,
  HouseAccount,
  Integration,
  Location,
  OnlineOrder,
  Promotion,
  PurchaseOrder,
  Recipe,
  ScheduleShift,
  ShiftChecklist,
  Tenant,
  TenantPayout,
} from "./platform-types";

export const BUILDINGS: Building[] = [
  {
    id: "bld_harbor",
    name: "Summex Market Hall",
    address: "40–48 Pier Avenue, Seaport District",
    locationIds: ["loc_hh", "loc_noodle", "loc_taco", "loc_gelato"],
    commonsFeeCentsDaily: 12000,
  },
];

export const TENANTS: Tenant[] = [
  {
    id: "ten_hh",
    name: "Summex",
    slug: "summex",
    legalName: "Summex LLC",
    taxIdMasked: "**-***4821",
    color: "#94a3b8",
    bankAccount: {
      id: "ba1",
      label: "Operating",
      last4: "4821",
      routingLast4: "0210",
    },
    locationIds: ["loc_hh", "loc_hh_uptown", "loc_commissary"],
    commonsFeeShare: 0.45,
    active: true,
    cuisine: "New American / Bar",
  },
  {
    id: "ten_noodle",
    name: "Pier Noodle Co",
    slug: "pier-noodle",
    legalName: "Pier Noodle Co Inc",
    taxIdMasked: "**-***9912",
    color: "#f87171",
    bankAccount: {
      id: "ba2",
      label: "Checking",
      last4: "9912",
      routingLast4: "0210",
    },
    locationIds: ["loc_noodle"],
    commonsFeeShare: 0.25,
    active: true,
    cuisine: "Ramen / Asian",
  },
  {
    id: "ten_taco",
    name: "Salty Taco",
    slug: "salty-taco",
    legalName: "Salty Taco LLC",
    taxIdMasked: "**-***3340",
    color: "#fbbf24",
    bankAccount: {
      id: "ba3",
      label: "Ops",
      last4: "3340",
      routingLast4: "0260",
    },
    locationIds: ["loc_taco"],
    commonsFeeShare: 0.2,
    active: true,
    cuisine: "Mexican",
  },
  {
    id: "ten_gelato",
    name: "Dockside Gelato",
    slug: "dockside-gelato",
    legalName: "Dockside Sweets LLC",
    taxIdMasked: "**-***7788",
    color: "#67e8f9",
    bankAccount: {
      id: "ba4",
      label: "Main",
      last4: "7788",
      routingLast4: "0210",
    },
    locationIds: ["loc_gelato"],
    commonsFeeShare: 0.1,
    active: true,
    cuisine: "Dessert",
  },
];

export const LOCATIONS: Location[] = [
  {
    id: "loc_hh",
    name: "Summex — Pier",
    code: "ZS-PIER",
    address: "42 Pier Avenue",
    timezone: "America/Los_Angeles",
    tenantId: "ten_hh",
    buildingId: "bld_harbor",
    phone: "(555) 014-2200",
    open: true,
    coversCapacity: 120,
  },
  {
    id: "loc_hh_uptown",
    name: "Summex — Uptown",
    code: "ZS-UP",
    address: "900 Market Street",
    timezone: "America/Los_Angeles",
    tenantId: "ten_hh",
    phone: "(555) 014-8800",
    open: true,
    coversCapacity: 80,
  },
  {
    id: "loc_commissary",
    name: "H&H Commissary",
    code: "ZS-COM",
    address: "12 Industrial Way",
    timezone: "America/Los_Angeles",
    tenantId: "ten_hh",
    phone: "(555) 014-1000",
    isCommissary: true,
    open: true,
    coversCapacity: 0,
  },
  {
    id: "loc_noodle",
    name: "Pier Noodle Co",
    code: "NOODLE",
    address: "44 Pier Avenue (Hall Stall B)",
    timezone: "America/Los_Angeles",
    tenantId: "ten_noodle",
    buildingId: "bld_harbor",
    phone: "(555) 014-3300",
    open: true,
    coversCapacity: 28,
  },
  {
    id: "loc_taco",
    name: "Salty Taco",
    code: "TACO",
    address: "46 Pier Avenue (Hall Stall C)",
    timezone: "America/Los_Angeles",
    tenantId: "ten_taco",
    buildingId: "bld_harbor",
    phone: "(555) 014-4400",
    open: true,
    coversCapacity: 20,
  },
  {
    id: "loc_gelato",
    name: "Dockside Gelato",
    code: "GELATO",
    address: "48 Pier Avenue (Hall Stall D)",
    timezone: "America/Los_Angeles",
    tenantId: "ten_gelato",
    buildingId: "bld_harbor",
    phone: "(555) 014-5500",
    open: true,
    coversCapacity: 12,
  },
];

export const RECIPES: Recipe[] = [
  {
    id: "rcp_burger",
    menuItemId: "mi_burger",
    name: "Forge Burger",
    yieldPortions: 1,
    plateCostCents: 420,
    lines: [
      { inventoryId: "inv6", qty: 0.08, unit: "dz" },
      { inventoryId: "inv8", qty: 0.25, unit: "lb" },
    ],
  },
  {
    id: "rcp_steak",
    menuItemId: "mi_steak",
    name: "Ribeye 12oz",
    yieldPortions: 1,
    plateCostCents: 1450,
    lines: [{ inventoryId: "inv3", qty: 0.75, unit: "lb" }],
  },
  {
    id: "rcp_of",
    menuItemId: "mi_old_fashioned",
    name: "Summex Old Fashioned",
    yieldPortions: 1,
    plateCostCents: 180,
    lines: [{ inventoryId: "inv1", qty: 0.04, unit: "btl" }],
  },
  {
    id: "rcp_oysters",
    menuItemId: "mi_oysters",
    name: "Oysters (6)",
    yieldPortions: 1,
    plateCostCents: 900,
    lines: [{ inventoryId: "inv5", qty: 0.5, unit: "dz" }],
  },
];

export const PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po1",
    vendor: "Seaport Seafood Co",
    locationId: "loc_hh",
    status: "sent",
    createdAt: Date.now() - 1000 * 60 * 60 * 20,
    expectedAt: Date.now() + 1000 * 60 * 60 * 8,
    lines: [
      { inventoryId: "inv5", name: "Oysters", qty: 8, unitCostCents: 2400 },
      { inventoryId: "inv4", name: "Salmon fillet", qty: 24, unitCostCents: 900 },
    ],
  },
  {
    id: "po2",
    vendor: "Valley Produce",
    locationId: "loc_hh",
    status: "draft",
    createdAt: Date.now() - 1000 * 60 * 30,
    lines: [
      { inventoryId: "inv8", name: "Fries (lb)", qty: 50, unitCostCents: 200 },
    ],
  },
];

function dayAt(hour: number, dayOffset = 0): number {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, 0, 0, 0);
  return d.getTime();
}

export const SCHEDULE: ScheduleShift[] = [
  {
    id: "sh1",
    employeeId: "emp_srv1",
    locationId: "loc_hh",
    role: "server",
    start: dayAt(16),
    end: dayAt(23),
    published: true,
  },
  {
    id: "sh2",
    employeeId: "emp_srv2",
    locationId: "loc_hh",
    role: "server",
    start: dayAt(11),
    end: dayAt(19),
    published: true,
  },
  {
    id: "sh3",
    employeeId: "emp_bar1",
    locationId: "loc_hh",
    role: "bartender",
    start: dayAt(15),
    end: dayAt(24),
    published: true,
  },
  {
    id: "sh4",
    employeeId: "emp_kit",
    locationId: "loc_hh",
    role: "kitchen",
    start: dayAt(10),
    end: dayAt(22),
    published: true,
  },
  {
    id: "sh5",
    employeeId: "emp_host",
    locationId: "loc_hh",
    role: "host",
    start: dayAt(16),
    end: dayAt(22),
    published: true,
  },
  {
    id: "sh6",
    employeeId: "emp_srv3",
    locationId: "loc_hh_uptown",
    role: "server",
    start: dayAt(17),
    end: dayAt(23),
    published: false,
    notes: "Uptown float",
  },
];

export const PROMOTIONS: Promotion[] = [
  {
    id: "promo_hh",
    name: "Weekday Happy Hour",
    type: "percent",
    value: 0,
    active: true,
    channels: ["dine_in", "bar" as "dine_in"],
    locationIds: "all",
    stackable: false,
  },
  {
    id: "promo_online10",
    name: "Online 10% first order",
    code: "WELCOME10",
    type: "percent",
    value: 10,
    active: true,
    channels: ["online", "takeout", "delivery"],
    locationIds: "all",
    minSubtotalCents: 2500,
    stackable: false,
  },
  {
    id: "promo_lunch",
    name: "Lunch combo $2 off",
    code: "LUNCH2",
    type: "fixed",
    value: 200,
    active: true,
    channels: ["dine_in", "takeout"],
    locationIds: ["loc_hh", "loc_hh_uptown"],
    stackable: true,
  },
  {
    id: "promo_hall",
    name: "Hall free gelato scoop w/ entrée",
    type: "free_item",
    value: 0,
    active: true,
    channels: ["dine_in"],
    locationIds: ["loc_hh", "loc_noodle", "loc_taco"],
    stackable: false,
  },
];

export const ONLINE_ORDERS: OnlineOrder[] = [
  {
    id: "oo1",
    number: 5001,
    channel: "web",
    type: "takeout",
    status: "preparing",
    guestName: "Chris Alvarez",
    guestPhone: "555-0199",
    locationId: "loc_hh",
    tenantId: "ten_hh",
    items: [
      {
        menuItemId: "mi_burger",
        name: "Forge Burger",
        qty: 2,
        unitPriceCents: 1900,
      },
      {
        menuItemId: "mi_ipa",
        name: "Local IPA Draft",
        qty: 2,
        unitPriceCents: 800,
      },
    ],
    subtotalCents: 5400,
    taxCents: 473,
    tipCents: 800,
    deliveryFeeCents: 0,
    totalCents: 6673,
    discountCents: 0,
    paymentStatus: "paid",
    createdAt: Date.now() - 1000 * 60 * 18,
    promisedAt: Date.now() + 1000 * 60 * 12,
  },
  {
    id: "oo2",
    number: 5002,
    channel: "marketplace",
    type: "delivery",
    status: "placed",
    guestName: "Jamie Fox",
    locationId: "loc_hh",
    tenantId: "ten_hh",
    marketplace: "DoorDash",
    address: "120 Market Blvd #4",
    items: [
      {
        menuItemId: "mi_salmon",
        name: "Cedar Salmon",
        qty: 1,
        unitPriceCents: 2800,
      },
    ],
    subtotalCents: 2800,
    taxCents: 245,
    tipCents: 500,
    deliveryFeeCents: 399,
    totalCents: 3944,
    discountCents: 0,
    paymentStatus: "paid",
    createdAt: Date.now() - 1000 * 60 * 4,
  },
  {
    id: "oo3",
    number: 5003,
    channel: "qr",
    type: "dine_in_qr",
    status: "ready",
    guestName: "Table 8 QR",
    tableLabel: "8",
    locationId: "loc_hh",
    tenantId: "ten_hh",
    items: [
      {
        menuItemId: "mi_negroni",
        name: "Pier Negroni",
        qty: 2,
        unitPriceCents: 1300,
      },
    ],
    subtotalCents: 2600,
    taxCents: 228,
    tipCents: 0,
    deliveryFeeCents: 0,
    totalCents: 2828,
    discountCents: 0,
    paymentStatus: "paid",
    createdAt: Date.now() - 1000 * 60 * 25,
  },
  {
    id: "oo_ahead1",
    number: 5004,
    channel: "web",
    type: "order_ahead",
    status: "accepted",
    guestName: "Sam Rivera",
    guestPhone: "555-0142",
    locationId: "loc_hh",
    tenantId: "ten_hh",
    items: [
      {
        menuItemId: "mi_burger",
        name: "Forge Burger",
        qty: 1,
        unitPriceCents: 1900,
      },
      {
        menuItemId: "mi_fries",
        name: "Truffle Fries",
        qty: 1,
        unitPriceCents: 900,
      },
    ],
    subtotalCents: 2800,
    taxCents: 245,
    tipCents: 400,
    deliveryFeeCents: 0,
    totalCents: 3445,
    discountCents: 0,
    paymentStatus: "paid",
    createdAt: Date.now() - 1000 * 60 * 35,
    promisedAt: Date.now() + 1000 * 60 * 20,
    claimCode: "A7K2",
    kitchenFireMode: "on_arrival",
    kitchenStatus: "pending_fire",
    arrivalStatus: "awaiting",
    notes: "Order ahead — fire when seated",
  },
  {
    id: "oo_curb1",
    number: 5005,
    channel: "app",
    type: "curbside",
    status: "ready",
    guestName: "Taylor Kim",
    guestPhone: "555-0188",
    locationId: "loc_hh",
    tenantId: "ten_hh",
    items: [
      {
        menuItemId: "mi_salmon",
        name: "Cedar Salmon",
        qty: 2,
        unitPriceCents: 2800,
      },
    ],
    subtotalCents: 5600,
    taxCents: 490,
    tipCents: 800,
    deliveryFeeCents: 0,
    totalCents: 6890,
    discountCents: 0,
    paymentStatus: "paid",
    createdAt: Date.now() - 1000 * 60 * 22,
    claimCode: "C9P1",
    kitchenFireMode: "on_arrival",
    kitchenStatus: "fired",
    firedToKitchenAt: Date.now() - 1000 * 60 * 12,
    arrivalStatus: "arrived",
    arrivedAt: Date.now() - 1000 * 60 * 8,
    vehicleDescription: "Honda CR-V",
    vehicleColor: "Blue",
  }
];

export const CATERING: CateringEvent[] = [
  {
    id: "cat1",
    name: "Thompson Rehearsal Dinner",
    clientName: "Thompson Family",
    clientPhone: "555-0201",
    locationId: "loc_hh",
    startsAt: dayAt(18, 3),
    endsAt: dayAt(22, 3),
    guestCount: 42,
    status: "deposit_paid",
    packageName: "Coastal feast",
    quoteCents: 680000,
    depositCents: 200000,
    depositPaid: true,
    room: "Private dining",
    notes: "Shellfish allergy — 2 guests",
  },
  {
    id: "cat2",
    name: "Acme Corp Lunch",
    clientName: "Acme Corp",
    locationId: "loc_hh_uptown",
    startsAt: dayAt(12, 1),
    endsAt: dayAt(14, 1),
    guestCount: 18,
    status: "quoted",
    packageName: "Executive buffet",
    quoteCents: 144000,
    depositCents: 0,
    depositPaid: false,
  },
];

export const PAYOUTS: TenantPayout[] = [
  {
    id: "payo1",
    tenantId: "ten_hh",
    periodStart: Date.now() - 1000 * 60 * 60 * 24 * 7,
    periodEnd: Date.now(),
    grossSalesCents: 4825000,
    feesCents: 144750,
    commonsCents: 84000,
    refundsCents: 12500,
    netPayoutCents: 4583750,
    status: "processing",
  },
  {
    id: "payo2",
    tenantId: "ten_noodle",
    periodStart: Date.now() - 1000 * 60 * 60 * 24 * 7,
    periodEnd: Date.now(),
    grossSalesCents: 1682000,
    feesCents: 50460,
    commonsCents: 21000,
    refundsCents: 0,
    netPayoutCents: 1610540,
    status: "pending",
  },
  {
    id: "payo3",
    tenantId: "ten_taco",
    periodStart: Date.now() - 1000 * 60 * 60 * 24 * 7,
    periodEnd: Date.now(),
    grossSalesCents: 990000,
    feesCents: 29700,
    commonsCents: 16800,
    refundsCents: 4500,
    netPayoutCents: 939000,
    status: "paid",
    paidAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: "payo4",
    tenantId: "ten_gelato",
    periodStart: Date.now() - 1000 * 60 * 60 * 24 * 7,
    periodEnd: Date.now(),
    grossSalesCents: 412000,
    feesCents: 12360,
    commonsCents: 8400,
    refundsCents: 0,
    netPayoutCents: 391240,
    status: "pending",
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: "camp1",
    name: "Win-back 30-day lapsed",
    channel: "email",
    segment: "Lapsed 30d",
    status: "scheduled",
    scheduledAt: Date.now() + 1000 * 60 * 60 * 24,
    audienceSize: 842,
  },
  {
    id: "camp2",
    name: "Happy hour SMS blast",
    channel: "sms",
    segment: "Local SMS opt-in",
    status: "sent",
    sentAt: Date.now() - 1000 * 60 * 60 * 48,
    audienceSize: 1204,
  },
];

export const DRIVERS: DeliveryDriver[] = [
  {
    id: "drv1",
    name: "Leo Park",
    phone: "555-0301",
    status: "available",
    locationId: "loc_hh",
  },
  {
    id: "drv2",
    name: "Ava Mensah",
    phone: "555-0302",
    status: "en_route",
    activeOrderId: "oo2",
    locationId: "loc_hh",
  },
];

export const HOUSE_ACCOUNTS: HouseAccount[] = [
  {
    id: "ha1",
    name: "Seaport Hotel",
    balanceCents: 128400,
    creditLimitCents: 500000,
    active: true,
  },
  {
    id: "ha2",
    name: "Acme Corp",
    balanceCents: 42000,
    creditLimitCents: 200000,
    active: true,
  },
];

export const INTEGRATIONS: Integration[] = [
  {
    id: "int_dd",
    name: "DoorDash Marketplace",
    category: "delivery",
    connected: true,
    lastSyncAt: Date.now() - 1000 * 60 * 5,
  },
  {
    id: "int_ue",
    name: "Uber Eats",
    category: "delivery",
    connected: true,
    lastSyncAt: Date.now() - 1000 * 60 * 12,
  },
  {
    id: "int_qb",
    name: "QuickBooks Online",
    category: "accounting",
    connected: true,
    lastSyncAt: Date.now() - 1000 * 60 * 60,
  },
  {
    id: "int_gusto",
    name: "Gusto Payroll",
    category: "payroll",
    connected: false,
  },
  {
    id: "int_summex",
    name: "Summex Payments",
    category: "payments",
    connected: true,
    lastSyncAt: Date.now() - 1000 * 60 * 2,
  },
  {
    id: "int_resy",
    name: "Resy / Reservations sync",
    category: "reservations",
    connected: false,
  },
  {
    id: "int_klaviyo",
    name: "Klaviyo CRM",
    category: "marketing",
    connected: true,
    lastSyncAt: Date.now() - 1000 * 60 * 90,
  },
];

export const CHECKLISTS: ShiftChecklist[] = [
  {
    id: "cl_open",
    type: "open",
    locationId: "loc_hh",
    items: [
      { id: "c1", text: "Count opening float $200", done: true, required: true },
      { id: "c2", text: "Check walk-in temps", done: true, required: true },
      { id: "c3", text: "Power on ODS / printers", done: true, required: true },
      { id: "c4", text: "Review 86 board", done: false, required: true },
      { id: "c5", text: "Brief staff on specials", done: false, required: false },
    ],
  },
  {
    id: "cl_close",
    type: "close",
    locationId: "loc_hh",
    items: [
      { id: "c6", text: "Close all open tabs", done: false, required: true },
      { id: "c7", text: "Run Z report / cash count", done: false, required: true },
      { id: "c8", text: "Sanitize bar & stations", done: false, required: true },
      { id: "c9", text: "Set alarm / lock doors", done: false, required: true },
    ],
  },
];
