import type {
  Customer,
  Employee,
  GiftCard,
  InventoryItem,
  MenuCategory,
  MenuItem,
  ModifierGroup,
  Reservation,
  RestaurantSettings,
  Table,
  WaitlistEntry,
  Vendor,
  SettlementConfig,
} from "./types";
import { DEFAULT_SECTION_POLICY } from "./section-control";
import { DEFAULT_CASH_DISCOUNT } from "./cash-discount";

export const SETTINGS: RestaurantSettings = {
  name: "Summex",
  // proprietors Michael Blair & Andy Baida
  address: "42 Pier Avenue, Seaport District",
  phone: "(555) 014-2200",
  taxRate: 0.0875,
  autoGratPercent: 0.2,
  autoGratPartySize: 6,
  happyHourEnabled: true,
  happyHourStart: 15,
  happyHourEnd: 18,
  happyHourDays: [1, 2, 3, 4, 5],
  currency: "USD",
  receiptFooter: "Thanks for choosing Summex. Tip is never expected, always appreciated.",
  managerPin: "0000",
  serviceChargeLabel: "Auto-gratuity",
  multiTenantHallMode: false,
  onlineOrderingEnabled: true,
  qrOrderingEnabled: true,
  qrMode: "hybrid",
  qrPolicy: {
    flags: ["reorder_after_open", "pay_only", "print_qr_on_ticket", "table_tents"],
    orderAllow: "food_and_drinks",
    payAllow: "both",
    split: "off",
    tip: true,
    alcoholAgeAffirm: true,
    afterPay: "close_table",
    ticketQrTtlSec: 15 * 60,
  },
  sectionPolicy: { ...DEFAULT_SECTION_POLICY },
  ...DEFAULT_CASH_DISCOUNT,
  giftTermAllowed: false,
  giftTermDays: 730,
  giftOperatorBreakageSplitBps: 5000,
  giftHouseIssuerEnabled: true,
};

export const EMPLOYEES: Employee[] = [
  {
    id: "emp_owner",
    name: "Morgan Blair",
    pin: "9999",
    role: "owner",
    color: "#2C4A6E",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 240,
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
  },
  {
    id: "emp_mgr",
    name: "Alex Rivera",
    pin: "0000",
    role: "manager",
    color: "#94a3b8",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 180,
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
  },
  {
    id: "emp_srv1",
    name: "Jordan Lee",
    pin: "1111",
    role: "server",
    color: "#7dd3fc",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 90,
    tipsEarned: 42_50,
    salesTotal: 680_00,
    active: true,
    homeSectionIds: ["sec_dining"],
  },
  {
    id: "emp_srv2",
    name: "Sam Okonkwo",
    pin: "2222",
    role: "server",
    color: "#86efac",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 120,
    tipsEarned: 61_00,
    salesTotal: 920_00,
    active: true,
    homeSectionIds: ["sec_booth"],
  },
  {
    id: "emp_bar1",
    name: "Casey Brooks",
    pin: "3333",
    role: "bartender",
    color: "#fca5a5",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 200,
    tipsEarned: 88_00,
    salesTotal: 1140_00,
    active: true,
    homeSectionIds: ["sec_bar"],
  },
  {
    id: "emp_host",
    name: "Riley Chen",
    pin: "4444",
    role: "host",
    color: "#c4b5fd",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 60,
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
  },
  {
    id: "emp_kit",
    name: "Morgan Diaz",
    pin: "5555",
    role: "kitchen",
    color: "#fcd34d",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 240,
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
  },
  {
    id: "emp_srv3",
    name: "Taylor Kim",
    pin: "6666",
    role: "server",
    color: "#fdba74",
    clockedIn: false,
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: ["sec_dining"],
  },
  {
    id: "emp_bus",
    name: "Jamie Cruz",
    pin: "7777",
    role: "busser",
    color: "#a5b4fc",
    clockedIn: true,
    clockInAt: Date.now() - 1000 * 60 * 45,
    tipsEarned: 0,
    salesTotal: 0,
    active: true,
    homeSectionIds: [],
  },
];


export const VENDORS: Vendor[] = [
  {
    id: "vnd_hearth",
    name: "Summex Kitchen",
    shortName: "Forge",
    locationId: "loc_building",
    color: "#94a3b8",
    cuisine: "New American",
    active: true,
    bankLast4: "4821",
    bankLabel: "Forge Operating",
    stationLabel: "Forge line",
  },
  {
    id: "vnd_bar",
    name: "Barline Co",
    shortName: "Bar",
    locationId: "loc_building",
    color: "#f87171",
    cuisine: "Cocktails & beer",
    active: true,
    bankLast4: "1102",
    bankLabel: "Bar Co checking",
    stationLabel: "Bar",
  },
  {
    id: "vnd_noodle",
    name: "Pier Noodle Co",
    shortName: "Noodle",
    locationId: "loc_building",
    color: "#fb923c",
    cuisine: "Ramen / Asian",
    active: true,
    bankLast4: "9912",
    bankLabel: "Noodle ops",
    stationLabel: "Noodle wok",
  },
  {
    id: "vnd_taco",
    name: "Salty Taco",
    shortName: "Taco",
    locationId: "loc_building",
    color: "#fbbf24",
    cuisine: "Mexican",
    active: true,
    bankLast4: "3340",
    bankLabel: "Salty Taco",
    stationLabel: "Taco plancha",
  },
  {
    id: "vnd_gelato",
    name: "Dockside Gelato",
    shortName: "Gelato",
    locationId: "loc_building",
    color: "#67e8f9",
    cuisine: "Dessert",
    active: true,
    bankLast4: "7788",
    bankLabel: "Dockside sweets",
    stationLabel: "Gelato",
  },
];

export const SETTLEMENT_CONFIG: SettlementConfig = {
  locationId: "loc_building",
  locationName: "Summex Market Hall",
  periodType: "weekly",
  customPeriodDays: 7,
  cardFeePercent: 2.9,
  hostCutEnabled: true,
  hostCutType: "percent_of_gross",
  hostCutPercent: 5,
  hostCutFixedCents: 0,
  hostName: "Summex Host LLC",
  taxRemittedBy: "host",
  tipPoolWithVendors: false,
  currentPeriodStart: (() => {
    const d = new Date();
    d.setHours(0, 0, 0, 0);
    // start of week Sunday
    d.setDate(d.getDate() - d.getDay());
    return d.getTime();
  })(),
};

export const CATEGORIES: MenuCategory[] = [
  { id: "cat_cocktails", name: "Cocktails", sort: 1, color: "#f87171", station: "bar" },
  { id: "cat_beer", name: "Beer & Wine", sort: 2, color: "#fbbf24", station: "bar" },
  { id: "cat_n/a", name: "Non-Alcoholic", sort: 3, color: "#34d399", station: "bar" },
  { id: "cat_apps", name: "Starters", sort: 4, color: "#60a5fa", station: "kitchen" },
  { id: "cat_salads", name: "Salads", sort: 5, color: "#4ade80", station: "kitchen" },
  { id: "cat_mains", name: "Mains", sort: 6, color: "#a78bfa", station: "kitchen" },
  { id: "cat_sides", name: "Sides", sort: 7, color: "#94a3b8", station: "kitchen" },
  { id: "cat_dessert", name: "Dessert", sort: 8, color: "#f472b6", station: "kitchen" },
];

export const MODIFIER_GROUPS: ModifierGroup[] = [
  {
    id: "mod_temp",
    name: "Temperature",
    required: true,
    min: 1,
    max: 1,
    options: [
      { id: "temp_rare", name: "Rare", priceCents: 0 },
      { id: "temp_mr", name: "Medium Rare", priceCents: 0, default: true },
      { id: "temp_med", name: "Medium", priceCents: 0 },
      { id: "temp_mw", name: "Medium Well", priceCents: 0 },
      { id: "temp_well", name: "Well Done", priceCents: 0 },
    ],
  },
  {
    id: "mod_side",
    name: "Side Choice",
    required: true,
    min: 1,
    max: 1,
    options: [
      { id: "side_fries", name: "Fries", priceCents: 0, default: true },
      { id: "side_salad", name: "Side Salad", priceCents: 0 },
      { id: "side_veg", name: "Seasonal Veg", priceCents: 0 },
      { id: "side_mash", name: "Mashed Potato", priceCents: 200 },
    ],
  },
  {
    id: "mod_dressing",
    name: "Dressing",
    required: true,
    min: 1,
    max: 1,
    options: [
      { id: "dr_vinaigrette", name: "House Vinaigrette", priceCents: 0, default: true },
      { id: "dr_ranch", name: "Ranch", priceCents: 0 },
      { id: "dr_caesar", name: "Caesar", priceCents: 0 },
      { id: "dr_none", name: "No Dressing", priceCents: 0 },
    ],
  },
  {
    id: "mod_protein",
    name: "Add Protein",
    required: false,
    min: 0,
    max: 2,
    options: [
      { id: "pr_chicken", name: "Grilled Chicken", priceCents: 600 },
      { id: "pr_salmon", name: "Salmon", priceCents: 900 },
      { id: "pr_shrimp", name: "Shrimp", priceCents: 800 },
      { id: "pr_steak", name: "Steak Tips", priceCents: 1000 },
    ],
  },
  {
    id: "mod_cook_style",
    name: "Preparation",
    required: false,
    min: 0,
    max: 3,
    options: [
      { id: "ck_no_onion", name: "No Onion", priceCents: 0 },
      { id: "ck_no_garlic", name: "No Garlic", priceCents: 0 },
      { id: "ck_extra_sauce", name: "Extra Sauce", priceCents: 100 },
      { id: "ck_gluten_free", name: "Gluten Free", priceCents: 200 },
      { id: "ck_spicy", name: "Make Spicy", priceCents: 0 },
      { id: "ck_allergy", name: "Allergy Alert", priceCents: 0 },
    ],
  },
  {
    id: "mod_spirit",
    name: "Spirit Preference",
    required: false,
    min: 0,
    max: 1,
    options: [
      { id: "sp_well", name: "Well", priceCents: 0, default: true },
      { id: "sp_call", name: "Call", priceCents: 200 },
      { id: "sp_premium", name: "Premium", priceCents: 400 },
      { id: "sp_top", name: "Top Shelf", priceCents: 700 },
    ],
  },
  {
    id: "mod_ice",
    name: "Ice",
    required: false,
    min: 0,
    max: 1,
    options: [
      { id: "ice_reg", name: "Regular Ice", priceCents: 0, default: true },
      { id: "ice_light", name: "Light Ice", priceCents: 0 },
      { id: "ice_none", name: "No Ice", priceCents: 0 },
      { id: "ice_extra", name: "Extra Ice", priceCents: 0 },
    ],
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // Cocktails
  {
    id: "mi_old_fashioned",
    name: "Summex Old Fashioned",
    categoryId: "cat_cocktails",
    priceCents: 1400,
    happyHourPriceCents: 1000,
    course: "drink",
    station: "bar",
    description: "Bourbon, demerara, bitters, orange oil",
    modifierGroupIds: ["mod_spirit", "mod_ice"],
    vendorId: "vnd_bar",
    available: true,
    prepMinutes: 3,
  },
  {
    id: "mi_negroni",
    name: "Pier Negroni",
    categoryId: "cat_cocktails",
    priceCents: 1300,
    happyHourPriceCents: 900,
    course: "drink",
    station: "bar",
    modifierGroupIds: ["mod_spirit", "mod_ice"],
    vendorId: "vnd_bar",
    available: true,
    prepMinutes: 2,
  },
  {
    id: "mi_margarita",
    name: "Smoked Margarita",
    categoryId: "cat_cocktails",
    priceCents: 1300,
    happyHourPriceCents: 900,
    course: "drink",
    station: "bar",
    modifierGroupIds: ["mod_spirit", "mod_ice", "mod_cook_style"],
    vendorId: "vnd_bar",
    available: true,
    prepMinutes: 3,
  },
  {
    id: "mi_martini",
    name: "Classic Martini",
    categoryId: "cat_cocktails",
    priceCents: 1500,
    course: "drink",
    station: "bar",
    modifierGroupIds: ["mod_spirit", "mod_ice"],
    vendorId: "vnd_bar",
    available: true,
    prepMinutes: 2,
  },
  {
    id: "mi_espresso_martini",
    name: "Espresso Martini",
    categoryId: "cat_cocktails",
    priceCents: 1400,
    course: "drink",
    station: "bar",
    modifierGroupIds: ["mod_spirit"],
    vendorId: "vnd_bar",
    available: true,
    prepMinutes: 3,
  },
  // Beer & Wine
  {
    id: "mi_ipa",
    name: "Local IPA Draft",
    categoryId: "cat_beer",
    priceCents: 800,
    happyHourPriceCents: 600,
    course: "drink",
    station: "bar",
    modifierGroupIds: [],
    vendorId: "vnd_bar",
    available: true,
    trackStock: true,
    stock: 48,
  },
  {
    id: "mi_lager",
    name: "Pier Lager",
    categoryId: "cat_beer",
    priceCents: 700,
    happyHourPriceCents: 500,
    course: "drink",
    station: "bar",
    modifierGroupIds: [],
    vendorId: "vnd_bar",
    available: true,
    trackStock: true,
    stock: 60,
  },
  {
    id: "mi_cab",
    name: "Cabernet Glass",
    categoryId: "cat_beer",
    priceCents: 1200,
    course: "drink",
    station: "bar",
    modifierGroupIds: [],
    vendorId: "vnd_bar",
    available: true,
  },
  {
    id: "mi_sauv",
    name: "Sauvignon Blanc",
    categoryId: "cat_beer",
    priceCents: 1100,
    course: "drink",
    station: "bar",
    modifierGroupIds: [],
    vendorId: "vnd_bar",
    available: true,
  },
  {
    id: "mi_bubbles",
    name: "Prosecco Glass",
    categoryId: "cat_beer",
    priceCents: 1000,
    course: "drink",
    station: "bar",
    modifierGroupIds: [],
    vendorId: "vnd_bar",
    available: true,
  },
  // Non-alc
  {
    id: "mi_soda",
    name: "House Soda",
    categoryId: "cat_n/a",
    priceCents: 350,
    course: "drink",
    station: "bar",
    modifierGroupIds: ["mod_ice"],
    vendorId: "vnd_bar",
    available: true,
  },
  {
    id: "mi_sparkling",
    name: "Sparkling Water",
    categoryId: "cat_n/a",
    priceCents: 400,
    course: "drink",
    station: "bar",
    modifierGroupIds: [],
    vendorId: "vnd_bar",
    available: true,
  },
  {
    id: "mi_mocktail",
    name: "Zero-Proof Spritz",
    categoryId: "cat_n/a",
    priceCents: 800,
    course: "drink",
    station: "bar",
    modifierGroupIds: ["mod_ice"],
    vendorId: "vnd_bar",
    available: true,
  },
  {
    id: "mi_coffee",
    name: "Drip Coffee",
    categoryId: "cat_n/a",
    priceCents: 400,
    course: "drink",
    station: "bar",
    modifierGroupIds: [],
    vendorId: "vnd_bar",
    available: true,
  },
  // Starters
  {
    id: "mi_calamari",
    name: "Crispy Calamari",
    categoryId: "cat_apps",
    priceCents: 1600,
    course: "appetizer",
    station: "kitchen",
    allergens: ["shellfish", "gluten"],
    modifierGroupIds: ["mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 12,
  },
  {
    id: "mi_wings",
    name: "Market Wings",
    categoryId: "cat_apps",
    priceCents: 1500,
    course: "appetizer",
    station: "kitchen",
    modifierGroupIds: ["mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 14,
  },
  {
    id: "mi_oysters",
    name: "Oysters (6)",
    categoryId: "cat_apps",
    priceCents: 2200,
    course: "appetizer",
    station: "kitchen",
    allergens: ["shellfish"],
    modifierGroupIds: [],
    vendorId: "vnd_hearth",
    available: true,
    trackStock: true,
    stock: 24,
    prepMinutes: 5,
  },
  {
    id: "mi_bruschetta",
    name: "Tomato Bruschetta",
    categoryId: "cat_apps",
    priceCents: 1200,
    course: "appetizer",
    station: "kitchen",
    allergens: ["gluten"],
    modifierGroupIds: ["mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 8,
  },
  {
    id: "mi_soup",
    name: "Soup of the Day",
    categoryId: "cat_apps",
    priceCents: 900,
    course: "appetizer",
    station: "kitchen",
    modifierGroupIds: [],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 4,
  },
  // Salads
  {
    id: "mi_caesar",
    name: "Classic Caesar",
    categoryId: "cat_salads",
    priceCents: 1400,
    course: "appetizer",
    station: "kitchen",
    allergens: ["dairy", "gluten", "eggs"],
    modifierGroupIds: ["mod_protein", "mod_dressing", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 7,
  },
  {
    id: "mi_garden",
    name: "Market Garden",
    categoryId: "cat_salads",
    priceCents: 1300,
    course: "appetizer",
    station: "kitchen",
    modifierGroupIds: ["mod_protein", "mod_dressing", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 7,
  },
  {
    id: "mi_beet",
    name: "Roasted Beet Salad",
    categoryId: "cat_salads",
    priceCents: 1500,
    course: "appetizer",
    station: "kitchen",
    allergens: ["nuts", "dairy"],
    modifierGroupIds: ["mod_protein", "mod_dressing"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 6,
  },
  // Mains
  {
    id: "mi_burger",
    name: "Forge Burger",
    categoryId: "cat_mains",
    priceCents: 1900,
    course: "entree",
    station: "kitchen",
    allergens: ["gluten", "dairy"],
    modifierGroupIds: ["mod_temp", "mod_side", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 16,
  },
  {
    id: "mi_steak",
    name: "Ribeye 12oz",
    categoryId: "cat_mains",
    priceCents: 4200,
    course: "entree",
    station: "kitchen",
    modifierGroupIds: ["mod_temp", "mod_side", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 22,
  },
  {
    id: "mi_salmon",
    name: "Cedar Salmon",
    categoryId: "cat_mains",
    priceCents: 2800,
    course: "entree",
    station: "kitchen",
    allergens: ["fish"],
    modifierGroupIds: ["mod_side", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 18,
  },
  {
    id: "mi_pasta",
    name: "Cacio e Pepe",
    categoryId: "cat_mains",
    priceCents: 2100,
    course: "entree",
    station: "kitchen",
    allergens: ["gluten", "dairy"],
    modifierGroupIds: ["mod_protein", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 14,
  },
  {
    id: "mi_chicken",
    name: "Herb Roast Chicken",
    categoryId: "cat_mains",
    priceCents: 2400,
    course: "entree",
    station: "kitchen",
    modifierGroupIds: ["mod_side", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 20,
  },
  {
    id: "mi_fish_chips",
    name: "Fish & Chips",
    categoryId: "cat_mains",
    priceCents: 2200,
    course: "entree",
    station: "kitchen",
    allergens: ["fish", "gluten"],
    modifierGroupIds: ["mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 15,
  },
  {
    id: "mi_risotto",
    name: "Mushroom Risotto",
    categoryId: "cat_mains",
    priceCents: 2300,
    course: "entree",
    station: "kitchen",
    allergens: ["dairy"],
    modifierGroupIds: ["mod_protein", "mod_cook_style"],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 18,
  },
  // Sides
  {
    id: "mi_fries",
    name: "Truffle Fries",
    categoryId: "cat_sides",
    priceCents: 900,
    course: "other",
    station: "kitchen",
    modifierGroupIds: [],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 8,
  },
  {
    id: "mi_mac",
    name: "Mac & Cheese",
    categoryId: "cat_sides",
    priceCents: 1000,
    course: "other",
    station: "kitchen",
    allergens: ["dairy", "gluten"],
    modifierGroupIds: [],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 6,
  },
  {
    id: "mi_asparagus",
    name: "Grilled Asparagus",
    categoryId: "cat_sides",
    priceCents: 800,
    course: "other",
    station: "kitchen",
    modifierGroupIds: [],
    vendorId: "vnd_hearth",
    available: true,
    prepMinutes: 7,
  },
  // Dessert
  {
    id: "mi_brownie",
    name: "Warm Brownie",
    categoryId: "cat_dessert",
    priceCents: 1100,
    course: "dessert",
    station: "kitchen",
    allergens: ["gluten", "dairy", "eggs"],
    modifierGroupIds: [],
    vendorId: "vnd_gelato",
    available: true,
    prepMinutes: 8,
  },
  {
    id: "mi_cheesecake",
    name: "Cheesecake",
    categoryId: "cat_dessert",
    priceCents: 1200,
    course: "dessert",
    station: "kitchen",
    allergens: ["dairy", "gluten", "eggs"],
    modifierGroupIds: [],
    vendorId: "vnd_gelato",
    available: true,
    prepMinutes: 3,
  },
  {
    id: "mi_icecream",
    name: "Gelato Trio",
    categoryId: "cat_dessert",
    priceCents: 1000,
    course: "dessert",
    station: "kitchen",
    allergens: ["dairy"],
    modifierGroupIds: [],
    vendorId: "vnd_gelato",
    available: true,
    prepMinutes: 2,
  },
  // --- Multi-vendor hall items ---
  {
    id: "mi_ramen",
    name: "Shoyu Ramen",
    categoryId: "cat_mains",
    priceCents: 1600,
    course: "entree",
    station: "kitchen",
    modifierGroupIds: ["mod_cook_style"],
    available: true,
    prepMinutes: 12,
    vendorId: "vnd_noodle",
    online: true,
  },
  {
    id: "mi_gyoza",
    name: "Gyoza (6)",
    categoryId: "cat_apps",
    priceCents: 900,
    course: "appetizer",
    station: "kitchen",
    modifierGroupIds: [],
    available: true,
    prepMinutes: 8,
    vendorId: "vnd_noodle",
    online: true,
  },
  {
    id: "mi_fish_tacos",
    name: "Fish Tacos (3)",
    categoryId: "cat_mains",
    priceCents: 1400,
    course: "entree",
    station: "kitchen",
    modifierGroupIds: ["mod_cook_style"],
    available: true,
    prepMinutes: 10,
    vendorId: "vnd_taco",
    online: true,
  },
  {
    id: "mi_elote",
    name: "Elote",
    categoryId: "cat_sides",
    priceCents: 700,
    course: "appetizer",
    station: "kitchen",
    modifierGroupIds: [],
    available: true,
    prepMinutes: 6,
    vendorId: "vnd_taco",
    online: true,
  },
  {
    id: "mi_gelato",
    name: "Gelato scoop",
    categoryId: "cat_dessert",
    priceCents: 500,
    course: "dessert",
    station: "kitchen",
    modifierGroupIds: [],
    available: true,
    prepMinutes: 2,
    vendorId: "vnd_gelato",
    online: true,
  },
  {
    id: "mi_affogato",
    name: "Affogato",
    categoryId: "cat_dessert",
    priceCents: 700,
    course: "dessert",
    station: "kitchen",
    modifierGroupIds: [],
    available: true,
    prepMinutes: 3,
    vendorId: "vnd_gelato",
    online: true,
  },

];

/** Floor plan: dining room + bar */
export const TABLES: Table[] = [
  // Patio / Section A
  { id: "t1", label: "1", section: "Dining", seats: 2, x: 6, y: 12, w: 10, h: 10, shape: "round", status: "available" },
  { id: "t2", label: "2", section: "Dining", seats: 2, x: 20, y: 12, w: 10, h: 10, shape: "round", status: "available" },
  { id: "t3", label: "3", section: "Dining", seats: 4, x: 36, y: 10, w: 14, h: 12, shape: "rect", status: "available" },
  { id: "t4", label: "4", section: "Dining", seats: 4, x: 54, y: 10, w: 14, h: 12, shape: "rect", status: "available" },
  { id: "t5", label: "5", section: "Dining", seats: 4, x: 72, y: 10, w: 14, h: 12, shape: "rect", status: "available" },
  { id: "t6", label: "6", section: "Dining", seats: 6, x: 6, y: 32, w: 18, h: 14, shape: "rect", status: "available" },
  { id: "t7", label: "7", section: "Dining", seats: 6, x: 30, y: 32, w: 18, h: 14, shape: "rect", status: "available" },
  { id: "t8", label: "8", section: "Dining", seats: 4, x: 54, y: 34, w: 14, h: 12, shape: "round", status: "available" },
  { id: "t9", label: "9", section: "Dining", seats: 4, x: 72, y: 34, w: 14, h: 12, shape: "round", status: "available" },
  { id: "t10", label: "10", section: "Dining", seats: 8, x: 12, y: 56, w: 22, h: 14, shape: "rect", status: "available" },
  { id: "t11", label: "11", section: "Dining", seats: 8, x: 42, y: 56, w: 22, h: 14, shape: "rect", status: "available" },
  { id: "t12", label: "12", section: "Booth", seats: 4, x: 70, y: 56, w: 16, h: 14, shape: "rect", status: "available" },
  // Bar seats
  { id: "b1", label: "B1", section: "Bar", seats: 1, x: 8, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
  { id: "b2", label: "B2", section: "Bar", seats: 1, x: 18, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
  { id: "b3", label: "B3", section: "Bar", seats: 1, x: 28, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
  { id: "b4", label: "B4", section: "Bar", seats: 1, x: 38, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
  { id: "b5", label: "B5", section: "Bar", seats: 1, x: 48, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
  { id: "b6", label: "B6", section: "Bar", seats: 1, x: 58, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
  { id: "b7", label: "B7", section: "Bar", seats: 1, x: 68, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
  { id: "b8", label: "B8", section: "Bar", seats: 1, x: 78, y: 80, w: 8, h: 8, shape: "bar", status: "available" },
];

export const WAITLIST: WaitlistEntry[] = [
  {
    id: "wl1",
    name: "Martinez",
    partySize: 4,
    phone: "555-0101",
    quotedMinutes: 25,
    status: "waiting",
    createdAt: Date.now() - 1000 * 60 * 12,
  },
  {
    id: "wl2",
    name: "Nguyen",
    partySize: 2,
    phone: "555-0102",
    quotedMinutes: 15,
    status: "notified",
    createdAt: Date.now() - 1000 * 60 * 22,
    notifiedAt: Date.now() - 1000 * 60 * 3,
  },
  {
    id: "wl3",
    name: "Patel",
    partySize: 6,
    phone: "555-0103",
    quotedMinutes: 40,
    notes: "High chair",
    status: "waiting",
    createdAt: Date.now() - 1000 * 60 * 5,
  },
];

export const RESERVATIONS: Reservation[] = [
  {
    id: "res1",
    name: "Thompson",
    partySize: 4,
    phone: "555-0201",
    time: (() => {
      const d = new Date();
      d.setHours(18, 30, 0, 0);
      return d.getTime();
    })(),
    tableId: "t6",
    status: "confirmed",
    notes: "Anniversary",
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: "res2",
    name: "Garcia",
    partySize: 2,
    phone: "555-0202",
    time: (() => {
      const d = new Date();
      d.setHours(19, 0, 0, 0);
      return d.getTime();
    })(),
    status: "booked",
    createdAt: Date.now() - 1000 * 60 * 60 * 48,
  },
  {
    id: "res3",
    name: "Williams",
    partySize: 8,
    phone: "555-0203",
    time: (() => {
      const d = new Date();
      d.setHours(20, 0, 0, 0);
      return d.getTime();
    })(),
    tableId: "t10",
    status: "confirmed",
    notes: "Birthday — cake",
    createdAt: Date.now() - 1000 * 60 * 60 * 72,
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "cus1",
    name: "Elena Martinez",
    phone: "555-0101",
    email: "elena@email.com",
    loyaltyPoints: 420,
    visitCount: 14,
    totalSpentCents: 186000,
    lastVisitAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: "cus2",
    name: "David Nguyen",
    phone: "555-0102",
    loyaltyPoints: 180,
    visitCount: 6,
    totalSpentCents: 54000,
    lastVisitAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: "cus3",
    name: "Priya Patel",
    phone: "555-0103",
    loyaltyPoints: 95,
    visitCount: 3,
    totalSpentCents: 28000,
    notes: "Allergic to shellfish",
  },
];

export const GIFT_CARDS: GiftCard[] = [
  {
    id: "gc1",
    code: "GIFT-2500",
    balanceCents: 2500,
    originalBalanceCents: 2500,
    active: true,
    status: "active",
    source: "summex",
    issuedToName: "Walk-in guest",
    issuedAt: Date.now() - 86400000 * 12,
  },
  {
    id: "gc2",
    code: "GIFT-5000",
    balanceCents: 5000,
    originalBalanceCents: 5000,
    active: true,
    status: "active",
    source: "summex",
    issuedToName: "Elena Martinez",
    issuedAt: Date.now() - 86400000 * 40,
  },
  {
    id: "gc3",
    code: "GIFT-1000",
    balanceCents: 1000,
    originalBalanceCents: 2500,
    active: true,
    status: "active",
    source: "summex",
    issuedToName: "Priya Patel",
    issuedAt: Date.now() - 86400000 * 8,
  },
];

export const INVENTORY: InventoryItem[] = [
  {
    id: "inv1",
    name: "Bourbon (bottle)",
    unit: "btl",
    onHand: 8,
    par: 12,
    costCents: 3200,
    linkedMenuItemIds: ["mi_old_fashioned"],
    lowStock: true,
  },
  {
    id: "inv2",
    name: "IPA Keg",
    unit: "keg",
    onHand: 2,
    par: 3,
    costCents: 18000,
    linkedMenuItemIds: ["mi_ipa"],
    lowStock: true,
  },
  {
    id: "inv3",
    name: "Ribeye (lb)",
    unit: "lb",
    onHand: 28,
    par: 20,
    costCents: 1800,
    linkedMenuItemIds: ["mi_steak"],
    lowStock: false,
  },
  {
    id: "inv4",
    name: "Salmon fillet",
    unit: "ea",
    onHand: 16,
    par: 18,
    costCents: 900,
    linkedMenuItemIds: ["mi_salmon"],
    lowStock: true,
  },
  {
    id: "inv5",
    name: "Oysters",
    unit: "dz",
    onHand: 4,
    par: 6,
    costCents: 2400,
    linkedMenuItemIds: ["mi_oysters"],
    lowStock: true,
  },
  {
    id: "inv6",
    name: "Burger buns",
    unit: "dz",
    onHand: 10,
    par: 8,
    costCents: 600,
    linkedMenuItemIds: ["mi_burger"],
    lowStock: false,
  },
  {
    id: "inv7",
    name: "Tequila (bottle)",
    unit: "btl",
    onHand: 6,
    par: 8,
    costCents: 2800,
    linkedMenuItemIds: ["mi_margarita"],
    lowStock: true,
  },
  {
    id: "inv8",
    name: "Fries (lb)",
    unit: "lb",
    onHand: 40,
    par: 25,
    costCents: 200,
    linkedMenuItemIds: ["mi_fries", "mi_burger", "mi_fish_chips"],
    lowStock: false,
  },
];

/** Demo: Dining server also covers booth 12 for this shift */
export const EXTRA_TABLE_GRANTS = [
  {
    id: "xg_demo_t12",
    employeeId: "emp_srv1",
    tableId: "t12",
    scope: "shift" as const,
    grantedById: "emp_mgr",
    grantedAt: Date.now() - 1000 * 60 * 40,
    reason: "Overflow booth",
  },
];
