export {
  SUMMEX_HOSTS,
  type SummexSurface,
  configuredHosts,
  resolveSurface,
  surfaceFromHost,
  surfaceFromPath,
  isMarketingPublicHost,
  isSingleOriginHost,
  appHref,
  explicitAppHost,
  appHostIsLiveAndDistinct,
  marketingHref,
  apiHref,
  sitesHref,
  absoluteAppHref,
  absoluteGuestHref,
  absoluteMarketingHref,
  originForSurface,
  isSingleOrigin,
  useSingleOrigin,
  staffGuestAccessPoints,
  currentHostname,
  currentOrigin,
} from "./hosts";
export type { AccessPoint } from "./hosts";
export type { ActiveTenantContext, WorkspaceLocation } from "./tenant-types";
export {
  RESERVED_VENUE_SLUGS,
  slugifyVenue,
  isReservedVenueSlug,
  normalizeVenueSlug,
  suggestVenueSlug,
  venueSlugFromHost,
  venueSlugFromPath,
  canUseVenueSubdomain,
  venueSubdomainHost,
  venuePublicOrigin,
  venuePosPath,
  venuePosHref,
  venueAwareHref,
} from "./venue-host";
