export {
  SUMMEX_HOSTS,
  type SummexSurface,
  configuredHosts,
  resolveSurface,
  surfaceFromHost,
  surfaceFromPath,
  isSingleOriginHost,
  appHref,
  explicitAppHost,
  appHostIsLiveAndDistinct,
  marketingHref,
  apiHref,
  sitesHref,
  absoluteAppHref,
  absoluteGuestHref,
  absoluteMarketingHref,
  originForSurface,
  useSingleOrigin,
  staffGuestAccessPoints,
  currentHostname,
  currentOrigin,
} from "./hosts";
export type { AccessPoint } from "./hosts";
export type { ActiveTenantContext, WorkspaceLocation } from "./tenant-types";
